Uninett/nav

doc/howto/api_parameters.rst, python/nav/web/api/v1/serializers.py, python/nav/web/api/v1/urls.py, python/nav/web/api/v1/views.py
=> Unrecognized neighbors API

python/nav/ipdevpoll/control.py, python/nav/ipdevpoll/daemon.py, python/nav/ipdevpoll/dataloader.py, python/nav/ipdevpoll/jobs.py, python/nav/ipdevpoll/log.py, python/nav/ipdevpoll/plugins/__init__.py, python/nav/ipdevpoll/plugins/arp.py, python/nav/ipdevpoll/pool.py, python/nav/ipdevpoll/schedule.py, requirements.txt
Work in progress, does not handle cancel job yet
=> Ipdevpoll multiprocess

AUTHORS.rst, python/nav/statemon/__init__.py, python/nav/statemon/circbuf.py, python/nav/statemon/debug.py, python/nav/statemon/event.py, python/nav/statemon/netbox.py, python/nav/statemon/service.py
Remove author names and CVS tags.
Also double-checked for which period Magnus T. worked on the code.
=> Header cleanup

python/nav/ipdevpoll/daemon.py, python/nav/ipdevpoll/pool.py, python/nav/ipdevpoll/schedule.py
=> Ipdevpoll max tasks per worker

python/nav/web/maintenance/utils.py
=> Changed default maintenance from 1 week to 1 day

htdocs/static/js/src/portadmin.js, templates/portadmin/trunk_edit.html
Fixes #1533 but is ugly as hell. Should probably be improved with some CSS before merge, which I will do when I have some free time.
=> Implemented toggle_all checkbox in trunk_edit

python/nav/statemon/checker/HttpChecker.py, python/nav/statemon/checker/HttpsChecker.py
Added credentials to HTTPChecker and made HTTPSChecker inherit from it. A new function used for connection was created, for easier overriding.
Fixes #1225
=> Added credentials to HTTPChecker

python/nav/ipdevpoll/plugins/bridge.py, python/nav/mibs/bridge_mib.py, sql/changes/sc.04.08.0020.sql
=> Collect base bridge address from BRIDGE-MIB as part of the bridge plugin

python/nav/web/portadmin/views.py
=> Fixed IndexError in portadmin search

htdocs/static/js/src/info_location.js, python/nav/models/manage.py, python/nav/web/ajax/urls.py, python/nav/web/ajax/views.py, python/nav/web/devicehistory/urls.py, python/nav/web/info/location/urls.py, python/nav/web/info/location/views.py, python/nav/web/info/searchproviders.py, python/nav/web/info/views.py, templates/info/base.html, templates/info/location/base.html, templates/info/location/fragment_sublocation.html, templates/info/location/locationinfo.html, templates/info/location/locationinfo_main.html, templates/info/location/locationinfo_rooms.html, templates/info/location/locationinfo_sublocations.html, templates/info/room/roominfo_main.html
Added info view pages for locations similar to rooms.
Fixes #1503
=> Added info system for locations

python/nav/web/portadmin/views.py
Also fixed the error message displayed when no audits exist.
=> Added auditlog for trunk edit in portadmin

templates/ipdevinfo/base.html, templates/seeddb/list_netbox.html, templates/seeddb/netbox_wizard.html
Added some GUI elements in seeddb and ipdevinfo that that shows that a netbox has been deleted.
=> Added GUI elements for showing netbox deletion

python/nav/ipdevpoll/storage.py, python/nav/mibs/mibretriever.py, python/nav/models/fields.py
These were the only usage of __metaclass__ I found.
Fixed as per
https://pythonhosted.org/six/index.html?highlight=metaclass#six.with_metaclass
and used as Django does it, with only six.with_metaclass used.
=> Sixify metaclasses

python/nav/django/settings.py, python/nav/web/info/views.py
This makes it easier for contributions to add additional providers with local_settings.py
=> Moved searchproviderlist to settings

python/nav/web/ipam/prefix_tree.py
I added some sanity checks for dealing with prefixes with no associated VLAN relation. I'm told this isn't supposed to happen, but it does, so I just deal with the problem by passing a mock object into the IPAM and logging the anomaly as a warning. Also fixed some Pylint violations, which should allow the build to pass. (I might look into refactoring some of this code, it's getting a bit hairy and could use a configuration object to avoid passing in all these scary parameters).
=> IPAM: Add quickfix, logging for prefixes with no VLAN

python/nav/web/report/views.py
IMHO, cache handling was too interwoven in the `make_report()` function. It bugged out in strange ways, causing intermittent Django e-mails to be sent from customer installs.
There was also the strange issue of search arguments not being part of the cache key, but instead part of the cache data, causing cache items to be invalidated each time some report was searched with different arguments.
=> refactor cache handling in report to separate concerns

python/nav/django/settings.py, python/nav/models/fields.py, python/nav/web/macwatch/__init__.py, python/nav/web/macwatch/apps.py
Modernizations done while working on other things, mostly in `nav.models.fields`.
=> Spurious modernization

CHANGES, Jenkinsfile, python/nav/django/utils.py, python/nav/eventengine/alerts.py, python/nav/report/generator.py, python/nav/web/devicehistory/views.py, python/nav/web/maintenance/views.py, python/nav/web/seeddb/utils/delete.py, requirements/base.txt, requirements/django.txt, requirements/django110.txt, requirements/django111.txt, requirements/django18.txt, requirements/django19.txt, tests/integration/conftest.py, tests/integration/eventengine/alerts_test.py, tests/integration/ipdevpoll/db_test.py, tests/unittests/django/utils_test.py, tox.ini, version.m4
Adding tests and fixes for things I've found to fail under Django 1.8
=> Django 1.8 compatibility fixes

python/nav/models/profiles.py, python/nav/web/business/reportengine.py, python/nav/web/business/utils.py, python/nav/web/business/views.py, sql/changes/sc.04.09.0050.sql, templates/business/base.html, templates/business/email.html, templates/business/email.txt, templates/business/report-availability.html, tests/unittests/business/business_test.py
Fixes #1662 as an alternative to #1671 (but based on that PR) - an attempt to remove some complicated code, by pushing more of the logic down to PostgreSQL, among other things.
=> Consider maintenance periods in Business reports

python/nav/django/forms.py, python/nav/django/validators.py, tests/unittests/django/forms_test.py, tests/unittests/django/validators_test.py
Ensures that what is put inside a textarea is valid json.
This should solve #1689.
=> Make a json-widget for forms

bin/autoenable.py, bin/collect_active_ip.py, bin/macwatch.py, bin/navdf, bin/navstats, bin/netbiostracker.py, bin/powersupplywatch.py, bin/start_arnold.py, bin/t1000.py, python/nav/logengine.py, python/nav/web/macwatch/models.py
Clean code (especially logging handling) in various NAV programs that do not run as daemons.
Works as a small followup to the changes in #1736
=> various cleaning of NAV programs

python/nav/macaddress.py, python/nav/web/api/v1/views.py
This fixes crash on invalid mac address filtering, but also enables wildcard filtering on mac.
=> Fix crash on invalid mac

python/nav/pgsync.py
Have navsyncdb use the pkg_resources framework to find the SQL schema files, as these data files are now located within the `nav.models` package.
=> use pkg_resources framework to find sql schema files.

python/nav/models/profiles.py, python/nav/web/netmap/api.py, python/nav/web/netmap/graph.py, python/nav/web/netmap/serializers.py, python/nav/web/netmap/urls.py, python/nav/web/netmap/views.py
I have tried to make clean atomic commits here, but the ultimate commit is a mess that needs to be reworked later.  Leaving it here for temporary review until I can get back to it over the weekend.
=> Migrate Netmap private API to Django Request Framework >= 3

python/nav/startstop.py
Bugfix to support options and arguments to command.
=> Command line argument support for nav daemon startup config

python/nav/web/useradmin/views.py
=> Fix breadcrumbs in API token views

python/nav/web/ipam/prefix_tree.py
=> Fix handling of missing usage attribute on vlans in ipam code

python/nav/Snmp/__init__.py, python/nav/Snmp/pynetsnmp.py, python/nav/ipdevpoll/plugins/interfaces.py, python/nav/ipdevpoll/plugins/sensors.py, python/nav/ipdevpoll/shadows/interface.py, python/nav/web/seeddb/page/netbox/edit.py, tests/unittests/Snmp/encodings_test.py, tests/unittests/ipdevpoll/interfaces_test.py
I don't really understand what this code was doing, and how it is supposed to work, so these changes require proper review.
=> Fix connectivity check for snmp with write access in seeddb on python3

python/nav/mibs/mg_snmp_ups_mib.py, python/nav/mibs/ups_mib.py, python/nav/mibs/xups_mib.py
Completely untested, but the code does at least import
=> Fix units and percision of Eaton UPS sensors

.gitignore, Makefile
Use a Makefile to get rid of known generated files.
=> add Makefile for cleaning

python/nav/auditlog/utils.py, tests/integration/auditlog_test.py
Improving coverage sometimes leads to yak-shaving.
=> Simple auditlog improvements

Makefile, python/nav/web/static/js/test/karma.conf.buildserver.js
An empty "untacked files" is a good "untracked files".
=> clean away more generated stuff

python/nav/auditlog/__init__.py, python/nav/django/auth.py, python/nav/django/views.py, python/nav/models/fields.py, python/nav/smsd/httpgetdispatcher.py, python/nav/web/api/v1/views.py, python/nav/web/devicehistory/views.py, python/nav/web/geomap/features.py, python/nav/web/maintenance/views.py, python/nav/web/portadmin/views.py, tests/integration/api_test.py, tests/integration/web/templatesyntax_test.py
All tests green on both Django 1.8 and Django 1.11, both Python 2.7 and Python 3.5.
=> Make all tests pass on Django 1.11

python/nav/models/profiles.py, tests/integration/models/alertsubscription_test.py
=> Delete queued alerts on a subscription when deleting a subscription

python/nav/web/info/room/views.py, python/nav/web/quickselect.py
Get rid of the last few places that use request.REQUEST.
=> Replace request.REQUEST

python/nav/models/fields.py, tests/unittests/models/fields_test.py
Some code rescued when cleaning up old branches.
=> Forgotten code

requirements/base.txt
fix the pip install problem: #1909 
Error: could not determine PostgreSQL version from ...
=> upgrade psycopg2 to ver 2.7.7

python/nav/web/static/js/src/plugins/gauge.js
=> Handle arbitrary number of thresholds for a given sensor

python/nav/mibs/itw_mibv4.py
=> Add support for most external sensors on newer watchdog products

python/nav/mibs/lldp_mib.py
This is an attempt at fixing #1903. It should not disrupt functionality that was already there, but offering it up as a PR so that @pstolpe may be able to test it on his Alcatel switches.
=> Add LLDP port number translation for Alcatel devices.

python/nav/web/static/js/resources/vue/environment_rack_item.html, python/nav/web/static/js/resources/vue/environment_rack_pdu_item.html, python/nav/web/static/js/src/plugins/vue_rack.js
=> Fix sensor links in Environment Rack navlet

doc/reference/ldap.rst, python/nav/etc/webfront/webfront.conf, python/nav/web/ldapauth.py, tests/unittests/general/webfront_test.py
This implements simple verification of user object entitlements in the LDAP authentication phase.
Suggestion came from @jornane, so a review would be nice :)
=> Verify LDAP entitlements

python/nav/portadmin/snmputils.py, python/nav/web/templates/portadmin/portlist.html
=> Show net ident for vlans in the portadmin vlan dropdown box

python/nav/mibs/itw_mib.py, python/nav/mibs/itw_mibv3.py, python/nav/mibs/itw_mibv4.py, tests/unittests/ipdevpoll/mibs_test.py
The fixes for #1919 added some refactorings that could also be used by itw_mib and itw_mibv3. This changeset adds that plus bugfixes, cleanups, and other general yak shavings
=> Refactor IT-WATCHDOGS-MIB MibRetriever implementations

python/nav/ipdevpoll/plugins/lldp.py, python/nav/mibs/mibretriever.py, python/nav/models/sql/changes/sc.04.10.0020.sql
=> Store local chassis ids from LLDP-MIB and use for neighbor lookups

python/nav/ipdevpoll/plugins/sensors.py, python/nav/mibs/comet.py, python/nav/mibs/eltek_distributed_mib.py, python/nav/mibs/pdu2_mib.py, python/nav/models/manage.py, python/nav/models/rack.py, python/nav/models/sql/changes/sc.04.10.0050.sql, python/nav/web/api/v1/serializers.py, python/nav/web/ipdevinfo/forms.py, python/nav/web/ipdevinfo/views.py, python/nav/web/navlets/__init__.py, python/nav/web/sass/nav/rack.scss, python/nav/web/static/js/resources/vue/environment_rack_item.html, python/nav/web/static/js/src/info_room_rack.js, python/nav/web/static/js/src/plugins/vue_rack.js, python/nav/web/static/js/src/sensor_details.js, python/nav/web/templates/info/room/fragment_racksensor.html, python/nav/web/templates/ipdevinfo/sensor-details.html
=> Improve support for boolean sensors in racks

python/nav/django/auth.py, python/nav/web/__init__.py, tests/unittests/general/web_middleware_test.py
- Auditlog and log sudo/desudo
- Debug-logging for AuthenticationMiddleware and refresh-hack
- Explicit testing of AuthenticationMiddleware
=> Improve logging for web auth

python/nav/models/manage.py, python/nav/models/sql/changes/sc.04.10.0030.sql, python/nav/web/api/v1/serializers.py
=> Disallow blank sysnames

python/nav/models/manage.py, python/nav/web/api/v1/filter_backends.py, python/nav/web/api/v1/views.py, tests/integration/querysets_test.py
=> Add maintenance filter to Netbox API endpoint

python/nav/etc/portadmin/portadmin.conf, python/nav/portadmin/snmputils.py, python/nav/web/portadmin/views.py
=> enabling CDP when a voice port is set using portadmin

python/nav/web/seeddb/forms/bulk.py, python/nav/web/templates/seeddb/bulk_import.html
=> Fix broken file uploads in SeedDB bulk imports under NAV 5.0.0

python/nav/util.py, python/nav/web/geomap/db.py
=> Fix Geomap brokenness under Python 3

python/nav/ipdevpoll/plugins/statsensors.py, python/nav/mibs/coriant_groove_mib.py
Under Python 3, the collected sensor names and descriptions of Coriant Groove devices look like `b'och-os-1/1/1 differential group delay'`, etc., i.e. as representations of bytes objects rather than proper strings.
This appears to be due to the fact that most of the text columns in the MIB module aren't actually marked as display strings, but as plain octet strings.
This PR seeks to mitigate that.
=> [BUG] Coriant Groove sensors names appear as reprs of bytes objects under Python 3

python/nav/web/info/room/views.py
=> Fix TypeError when making CSV

python/nav/models/fields.py, tests/unittests/models/fields_test.py
=> Feed DictAsJsonField pickle with bytes, not str

python/nav/bulkimport.py, tests/integration/bulkimport_test.py
=> Don't crash when bulk importing netboxes without management profiles

python/nav/arnold.py, python/nav/netbiostracker/tracker.py
Also standardize on nbtscan for getting netbios data.
Fixes #2090.
=> Fix TypeError in live netbios workstation lookup

python/nav/web/geomap/db.py
This fixes #2101 and makes a slight cleanup as well (separated commits)
=> Fix broken value comparison in Geomap

python/nav/models/manage.py, tests/unittests/models/sensor_test.py
=> Fix broken use-case of Sensor.normalized_unit property 

python/nav/web/webfront/views.py
Fixes #2130 (at least problem no. 1 it)
=> Import dashboard even if locale is not UTF-8

python/nav/logs.py
=> Fix unicode logging error

python/nav/web/seeddb/utils/delete.py, python/nav/web/templates/seeddb/management-profile/edit.html, python/nav/web/templates/seeddb/netbox_wizard.html
First step of standardizing how deletion looks and feels in SeedDB. This specific PR moves the buttons on IP Device and Management Profile but otherwise should not change anything else visible to the end user.
For #2138.
=> Refactor deletion in SeedDB

python/nav/alertengine/base.py, tests/unittests/alertengine/base_test.py
=> Fix missing import that causes alertengine crash in certain scenarios

NOTES.rst, python/nav/etc/daemons.yml, python/nav/startstop.py
=> Distinguish between privileged and non-privileged NAV processes

python/nav/statemon/checker/FtpChecker.py
=> Fix bug in ftp service check

.dockerignore, Dockerfile, docker-compose.yml
Born out of several frustrations I've had with the current setup of the development environment using `docker-compose.yml` and `Dockerfile`, I decided to make a few changes. These changes include:
- Increased transparency of how the image is built
- Increased configurability for individual developer whims
- Improved use of the Docker cache
- Considerably reduced build context sent to Docker daemon.
=> Clean up and improve Docker development container

python/nav/web/seeddb/page/management_profile/__init__.py, python/nav/web/seeddb/page/netbox/forms.py, python/nav/web/seeddb/utils/list.py, python/nav/web/templates/seeddb/management-profile/edit.html
=> Add a link in the UI from a managment profile to a list of its netboxes

python/nav/statemon/checker/HttpChecker.py
Because:
- Less configuration = better :-)
Closes #2199
=> Override HttpsChecker port from URL

python/nav/mibs/qbridge_mib.py, tests/unittests/mibs/qbridge_mib_test.py
=> Strip nullbytes from vlan names pulled from Q-BRIDGE-MIB

.readthedocs.yaml, doc/requirements.txt, python/nav/buildconf.py, requirements.txt, requirements/base.txt, requirements/optional.txt, tox.ini
Building on previous work by @hmpf, here is an updated version that configures doc builds to work properly on Read The Docs:  https://nav.readthedocs.io/
=> Publish documentation on Read The Docs

python/nav/models/manage.py, python/nav/web/seeddb/page/netbox/forms.py
=> Fix  for intermittently disappering netbox function values

python/nav/ipdevpoll/plugins/poe.py
While researching for #2163 I found this jarring code snippet which I felt the need to refactor.
- The mapping algorithm is Cisco specific, and it seems very jarring to have this code block within the main `handle()` method.
- Why this strange code is even needed may be a complete mystery to a novice contributor, so it deserves a longer explanation, provided in this case as a docstring.
=> Extract Cisco PoE port mapping method

doc/reference/portadmin.rst
Fixes #1928
Depends on #2301 - keeping in draft mode until merged
=> Document the 802.1 options of portadmin.conf

python/nav/statemon/db.py, tests/integration/pping_test.py
=> Always post a severity value for events from pping

python/nav/web/navlets/report.py
Previously only reports from "reports.conf" could be selected to be shown in the widget
This commit adds reports from "report.local.conf"
=> Also list local conf reports in report widget

doc/reference/eventengine.rst, python/nav/etc/severity.yml
=> Fix broken example severity rules

python/nav/ipdevpoll/plugins/prefix.py, tests/unittests/ipdevpoll/prefix_test.py
=>  Juniper VLAN interfaces are not properly associated with their VLANs

python/nav/web/info/images/utils.py
=> Rotate room thumbnails according to EXIF tags

python/nav/web/seeddb/page/netboxtype.py
Similar to https://github.com/Uninett/nav/pull/2384 in regards to https://github.com/Uninett/nav/issues/2156 this PR optimizes the netboxtype listing queries of SeedDB.
=> Optimize SeedDB netboxtype listing queries

python/nav/models/manage.py
=> Change import of JSONField

python/nav/web/report/views.py
=> Get rid of CacheKeyWarning

python/nav/web/static/js/geomap/Permalink.js
=> Fix geomap link to this configuration results in alert

python/nav/mibs/entity_mib.py, python/nav/models/sql/changes/sc.05.04.0001.sql, tests/unittests/mibs/entity_mib_test.py
=> Stop classifying transceivers as modules

python/nav/web/api/v1/serializers.py
=> Add LAG information to NAV Api

bin/navcheckservice
=> Add a flag to navcheckservice that shows all available handler plugins

python/nav/activeipcollector/manager.py
=> Delete unnecessary carbon data chunking from activeipcollector

python/nav/web/sortedstats/views.py, python/nav/web/templates/sortedstats/sortedstats.html
Closes #2442 
Test for this is still missing.
=> Fix error handling when Graphite can not be reached in ranked statistics

python/nav/web/api/v1/filter_backends.py, python/nav/web/status2/forms.py
=> Filter by severity value in the status tool

CHANGELOG.md, python/nav/web/maintenance/forms.py, python/nav/web/maintenance/views.py, python/nav/web/templates/maintenance/calendar.html, tests/integration/web/maintenance/views_test.py, tests/unittests/web/maintenance/forms_test.py
=> Validate maintenance calendar form input using Django forms

tools/buglog.py
The `buglog.py` script normally compiles a list of closed issues and merged pull requests from a GitHub milestone, but with the added overhead of three more people on the dev team over the last year or so, our GitHub milestones aren't always up to date.
However, we can pretty much fetch the same information from the git commit messages itself, based on our workflow that uses GitHub pull requests for 99% of all code changes. Most merged pull requests and fixed issues will be referenced in the git log messages.
The added `--gitlog` option will scan the git commit messages from the given version tag up until the current head, extract references to closed/resolved issues and pull requests, and also check pull requests for linked issues that weren't directly referenced in the commit messages.
=> Add `buglog.py` option to fetch issue numbers from git reflog

contrib/scripts/isc_dhpcd_graphite.py, contrib/scripts/isc_dhpcd_graphite/README.rst, contrib/scripts/isc_dhpcd_graphite/isc_dhpcd_graphite.py
=> Fix dhcpd pool script

bin/navdump, python/nav/models/rack.py, python/nav/models/service.py, python/nav/models/thresholds.py, python/nav/web/info/room/views.py, python/nav/web/ipdevinfo/views.py, python/nav/web/networkexplorer/mixins.py, python/nav/web/templates/ipdevinfo/frag-services.html
This is the fourth part of splitting up https://github.com/Uninett/nav/pull/2423.
=>  Add related names to django models (rack, service, treshold)

CHANGELOG.md, python/nav/web/templates/navlets/alert_view.html
=> Mark data URL as HTML safe

python/nav/napalm.py, python/nav/portadmin/napalm/juniper.py, python/nav/web/seeddb/page/management_profile/forms.py, tests/unittests/napalm_test.py, tests/unittests/portadmin/napalm/juniper_test.py
Closes #2390. 
Unclear currently how to manually test it.
=>  Timeout values should be configurable in NAPALM profiles

tests/integration/ipdevpoll/plugins/snmpcheck_test.py
=> Improve ipdevpoll snmpcheck test assumptions

python/nav/web/macwatch/models.py
This is the sixth part of splitting up https://github.com/Uninett/nav/pull/2423.
=> Add related names to django models (macwatch)

python/nav/web/navlets/navblog.py
Similar to Uninett/nav-landing-page#40 - can be merged when redirecting works.
=> Change blog url in widget

python/nav/alertengine/base.py, python/nav/django/utils.py, python/nav/models/profiles.py, python/nav/web/alertprofiles/forms.py, python/nav/web/alertprofiles/utils.py, python/nav/web/alertprofiles/views.py, python/nav/web/api/v1/serializers.py, python/nav/web/auth.py, python/nav/web/netmap/serializers.py, python/nav/web/templates/business/frag-report-items.html, python/nav/web/templates/useradmin/account_detail.html, python/nav/web/templates/useradmin/account_list.html, python/nav/web/templates/useradmin/group_detail.html, python/nav/web/templates/useradmin/userinfo.html, python/nav/web/templates/webfront/index.html, python/nav/web/templates/webfront/preferences.html, python/nav/web/useradmin/forms.py, python/nav/web/useradmin/views.py, python/nav/web/webfront/utils.py
This is the fifth part of splitting up https://github.com/Uninett/nav/pull/2423.
=> Add related names to django models (profiles)

python/nav/ipdevpoll/neighbor.py, python/nav/ipdevpoll/plugins/lldp.py, python/nav/ipdevpoll/shadows/__init__.py, python/nav/models/manage.py, python/nav/models/profiles.py, python/nav/topology/detector.py, python/nav/topology/vlan.py, python/nav/web/api/v1/filter_backends.py, python/nav/web/api/v1/views.py, python/nav/web/info/vlan/views.py, python/nav/web/ipam/views.py, python/nav/web/l2trace/__init__.py, python/nav/web/networkexplorer/mixins.py, python/nav/web/networkexplorer/search.py, python/nav/web/portadmin/utils.py, python/nav/web/seeddb/page/vlan.py, python/nav/web/templates/ipdevinfo/port-details-vlan-frag.html, tests/unittests/portadmin/portadmin_util_test.py
This is the eighth part of splitting up https://github.com/Uninett/nav/pull/2423.
=> Add related names to django models (manage - Router/topology)

CHANGELOG.md, python/nav/ipdevpoll/plugins/entity.py, tests/integration/ipdevpoll/plugins/entity_test.py
=> Set device sw/hw/fw version by netbox entity with lowest index

CHANGELOG.md, python/nav/web/ipdevinfo/views.py, python/nav/web/templates/ipdevinfo/ipdev-details.html
=> Show error message on invalid ip address in ipdevinfo

CHANGELOG.md, doc/hacking/index.rst, doc/hacking/snmp-tunnels.rst
=> Document a recipe for establishing SNMP tunnels using socat/SSH

python/nav/models/manage.py
=>  Fix typo in Device.get_related_objects()

python/nav/ipdevpoll/shadows/__init__.py, python/nav/models/manage.py, tests/integration/models/netbox_type_test.py
=> Make get_enterprise_id more flexible when parsing sysObjectID values

.readthedocs.yaml
=> Fix .readthedocs.yaml

python/nav/mibs/juniper_mib.py
=> Fix incorrect load average object names

bin/alertengine.py, python/nav/alertengine/base.py, python/nav/alertengine/dispatchers/__init__.py, python/nav/models/profiles.py, python/nav/models/sql/changes/sc.05.07.0002.sql, tests/integration/models/alert_test.py
Replaces #2670 due to GitHub shenanigans.
Fixes #2664
=>  Add blacklisted reason field to alert sender

python/nav/Snmp/profile.py, python/nav/web/seeddb/page/netbox/edit.py, tests/unittests/Snmp/profile_test.py
Closes #2704 
Replaces #2711 (which got closed for silly Git-f***ery reasons)
=> Enable SNMPv3 reachability verification in SeedDB

tests/integration/web/alertprofiles_test.py
First step of tidying up the alert profile tests, more to come...
=> Use admin account fixture in alert profile tests

tests/integration/web/alertprofiles_test.py
Another PR to improve testing of the alert profile views.
=>  Add tests for overview of alert profiles page 

tests/integration/web/alertprofiles_test.py
Another PR to improve testing of the alert profile views.
=>  Add tests for accessing non existent profile 

python/nav/web/navlets/forms.py, tests/integration/widget_test.py
Sadly another bug caused by #2544...
=> Fix related names in PDU widget

NOTES.rst, doc/faq/faq.rst, doc/hacking/adding-environment-probe-support.rst, doc/reference/alerttypes.rst, doc/reference/index.rst, doc/reference/ipdevpoll.rst, python/nav/mibs/mibretriever.py, tox.ini
Another part of the cleanup process of the docs.
=> Remove warnings when building docs

.pre-commit-config.yaml
As mentioned in https://github.com/Uninett/nav/pull/2859#discussion_r1516290469.
=> Add end of file fixer to pre-commit hooks

CHANGELOG.md
Something that was overlooked in #2869...
=> Fix link to changelog fragment directory

.pre-commit-config.yaml
To stay up-to-date with MegaLinter.
=> Upgrade linter versions in pre-commit 

python/nav/web/seeddb/forms/__init__.py
This isn't actually referenced by any code, and hasn't been for the last 8 years.
Closes #2984
=> Remove unused `OrganizationFilterForm`

tools/eventgenerators/moduleevent.py
=> Fix invalid severity value in moduleevents.py

python/nav/Snmp/profile.py, python/nav/arnold.py, python/nav/bin/pping.py, python/nav/bin/snmptrapd.py, python/nav/bin/t1000.py, python/nav/ipdevpoll/__init__.py, python/nav/ipdevpoll/plugins/entity.py, python/nav/mibs/juniper_alarm_mib.py, python/nav/web/report/views.py, python/nav/web/seeddb/page/netbox/edit.py, python/nav/web/seeddb/page/netboxgroup.py
This PR I have split into two commits: The first one I was able to find out that code that used these imports was removed and am quite certain they are not needed and can be removed without causing problems.
The second commit contains the problem children that need a closer look and help from someone who understands these parts of the codebase a bit better.
=> Remove unused local imports

python/nav/web/seeddb/page/netbox/forms.py, python/nav/web/templates/seeddb/list.html
Closes #3062. 
Url: http://localhost/seeddb/netbox/
=> Uncrispify `NetboxFilterForm` from SeedDB

python/nav/web/templates/webfront/login.html, python/nav/web/webfront/forms.py
Fixes #3087 
url: http://localhost/index/login/
=> Uncrispify LoginForm

python/nav/web/alertprofiles/forms.py
Fixes #3083 
URL: http://localhost/alertprofiles/filters/
=> Uncrispify FilterForm

python/nav/web/alertprofiles/forms.py, python/nav/web/templates/alertprofiles/timeperiod_edit.html, python/nav/web/templates/alertprofiles/timeperiod_form.html
Fixes #3081 
To get to this form you first need to make a profile at http://localhost/alertprofiles/profile/ then click on that profile, and at the bottom of that page should be the TimePeriodForm
=> Uncrispify TimePeriodForm

python/nav/web/ipdevinfo/forms.py, python/nav/web/templates/ipdevinfo/sensor-details.html
Closes #3093. 
Url: ipdevinfo/sensor/\<id>
=> Uncrispify `BooleanSensorForm` in ipdevpoll

python/nav/web/portadmin/forms.py, python/nav/web/templates/portadmin/base.html
Fixes #3111 
http://localhost/portadmin/
=> Uncrispify portadmin SearchForm

python/nav/web/messages/forms.py, python/nav/web/templates/messages/save.html
Fixes #3112 
http://localhost/messages/create/
=> Uncrispify MessageForm

python/nav/web/templates/useradmin/group_detail.html, python/nav/web/useradmin/forms.py
Closes #3151.
Urls:
http://localhost/useradmin/group/<id\>
=> Uncrispify PrivilegeForm in useradmin

python/nav/web/templates/useradmin/account_detail.html, python/nav/web/useradmin/forms.py
Closes #3152.
Url: http://localhost/useradmin/account/<id\>/
=> Uncrispify OrganizationAddForm in useradmin

python/nav/web/templates/custom_crispy_templates/flat_fieldset.html
#3106 needs this to function properly. Split into separate PR since its a general change that can be used by anything
=> Make contents of legend tag in fieldset template overridable

python/nav/web/crispyforms.py
#3106 needs this to function properly. Split into separate PR since its a general change that can be used by anything
=> Make template in FlatFieldset overridable

python/nav/web/l2trace/forms.py, python/nav/web/templates/l2trace/l2trace.html
Fixes #3120 
http://localhost/l2trace/
=> Uncrispify L2TraceForm

python/nav/web/templates/useradmin/token_edit.html, python/nav/web/useradmin/forms.py
Closes #3156. 
Urls: 
http://localhost/useradmin/tokens/create/
http://localhost/useradmin/tokens/edit/<id\>
=> Uncrispify TokenForm in user admin

python/nav/web/templates/useradmin/account_detail.html, python/nav/web/useradmin/forms.py
Closes #3155. 
Url: http://localhost/useradmin/account/<id\>/
=> Uncrispify `GroupAddForm` in useradmin

python/nav/web/radius/forms.py, python/nav/web/templates/radius/account_log.html
Fixes #3124 
http://localhost/radius/acctsearch
=> Uncrispify AccountLogSearchForm

python/nav/web/radius/forms.py, python/nav/web/templates/radius/account_charts.html
Fixes #3125
http://localhost/radius/acctcharts
=> Uncrispify AccountChartsForm

python/nav/web/arnold/forms.py, python/nav/web/templates/arnold/quarantinevlans.html
Fixes #3163 
http://localhost/arnold/addquarantinevlan/
and http://localhost/arnold/addquarantinevlan/edit/<id> (can be reached by first creating a quarantine rule, then clicking the edit button that shows up next to its entry in the list)
=> Uncrispify QuarantineVlanForm

python/nav/web/arnold/forms.py, python/nav/web/templates/arnold/search.html
Fixes #3172
http://localhost/arnold/search/
=> Uncrispify Arnold SearchForm

python/nav/web/syslogger/forms.py, python/nav/web/templates/syslogger/frag-search-form-fieldset.html, python/nav/web/templates/syslogger/frag-search.html
Fixes #3101 
http://localhost/syslogger/
=> Uncrispify LoggerGroupSearchForm

python/nav/web/templates/navlets/graph_edit.html
How to get there:
Add a widget of the type "Chart" to the dashboard
Click "Edit"
=> Uncrispify graph edit navlet html template

python/nav/web/templates/navlets/room_map_view.html
This was forgotten in #3036. 
Add a widget of the type "Room Map" to your dashboard.
=> Uncrispify room map navlet html template

python/nav/web/templates/navlets/room_location_status_edit.html
This was overlooked in #3137. 
Add a widget "Locations with active alerts"/"Rooms with active alerts" and click on edit
=> Uncrispify room/location status navlet html template

python/nav/web/arnold/forms.py, python/nav/web/arnold/urls.py, python/nav/web/arnold/views.py, python/nav/web/templates/arnold/justifications.html, python/nav/web/templates/arnold/tabs.html
I noticed this when reviewing #3039.
=> Fix typo in arnold justifications

.pre-commit-config.yaml
To stay up-to-date with MegaLinter
=> Update ruff in pre-commit to newest version

tests/docker/Dockerfile
To make the functional tests run again locally.
=> Upgrade chrome-driver version in docker image to 131.0.6778.69

.github/workflows/towncrier.yml
Very fitting that this PR is also proof that it works.
=> Skip towncrier check on `github_action` label

changelog.d/3242.fixed.md, python/nav/web/ipdevinfo/forms.py
=> Limit interval in switch port activity to 10000

changelog.d/3242.fixed.md, python/nav/web/ipdevinfo/forms.py, tests/integration/web/ipdevinfo_test.py
=>  Clean/check number of days in activity interval form 

Dockerfile, changelog.d/3284.changed.md, docker-compose.snmp.yml, docker-compose.yml, tools/docker/build.sh, tools/docker/doc-watch.sh
=> Upgrade development Docker environment to Debian Bookworm / Python 3.11

changelog.d/+auxiliary-docker-bookworm.changed.md, tools/docker/graphite/Dockerfile, tools/forward/Dockerfile
Dependent on #3286 and in conjunction with it replaces #2723 and fixes #2695
=> Upgrade auxiliary Docker images to Debian Bookworm

changelog.d/3244.fixed.md, python/nav/web/arnold/forms.py, tests/integration/web/arnold_test.py
=> Check that vlan is not already quarantined in Arnold

changelog.d/3245.fixed.md, python/nav/web/radius/forms.py, tests/integration/web/radius_test.py
Dependent on #3295. Closes #3245.
=> Clean number of days in account charts form

changelog.d/3247.fixed.md, python/nav/web/radius/forms.py, tests/integration/web/radius_test.py
Closes #3247. Dependent on #3295.
=>  Validate number of days in account log search form 

changelog.d/3016.changed.md, python/nav/etc/webfront/jwt.conf, python/nav/jwtconf.py, python/nav/web/jwtgen.py, tests/unittests/jwtconf_test.py, tests/unittests/web/jwtgen_test.py
=> Make JWT token expiration time configurable

NOTES.rst, changelog.d/2358.changed.md, pyproject.toml, requirements/base.txt
Fixes #2538 
Tested against real equipment and still seems to work.
=> Upgrade NAPALM to 5.0

python/nav/web/templates/base.html, python/nav/web/templates/useradmin/account_detail.html, python/nav/web/templates/useradmin/delete.html, python/nav/web/templates/useradmin/token_edit.html
Contributes to https://github.com/Uninett/campus-tasks/issues/45.
**Where to find the forms (ordered by commit):**
Operate as user form: Go to http://localhost/useradmin/, click on a user, see form around "Operate as this user" button
Stop operating as user form: After clicking on previous "Operate as this user" button, see banner (form)
Delete account form: Go to http://localhost/useradmin/, click on a user, click on "Delete account", see form
Expire token form: Go to http://localhost/useradmin/tokens/, click on a token, click "Edit token", see form around "Expire token" button
=> Add csrf token to forms in useradmin

doc/hacking/hacking.rst
The hacking docs section on running test suites was becoming slightly stale and needed an update.
* ~~[ ] Added a changelog fragment for [towncrier](https://nav.readthedocs.io/en/latest/hacking/hacking.html#adding-a-changelog-entry)~~
* ~~[ ] Added/amended tests for new/changed code~~
* ~~[ ] If applicable: Created new issues if this PR does not fix the issue completely/there is further work to be done~~
* ~~[ ] If this results in changes in the UI: Added screenshots of the before and after~~
* ~~[ ] If this adds a new Python source code …
=> Slightly update information about test suites

Makefile, changelog.d/3398.added.md, doc/hacking/hacking.rst, doc/hacking/index.rst, doc/hacking/using-devcontainers.rst, doc/howto/commandline-utilities.rst
Fixes #3398, while also adding some small niceties for building documentation inside the devcontainer.
* ~~[ ] Added/amended tests for new/changed code~~
* ~~[ ] If applicable: Created new issues if this PR does not fix the issue completely/there is further work to be done~~
* ~~[ ] If this results in changes in the UI: Added screenshots of the before and after~~
* ~~[ ] If this adds a new Python source code file: Added the [boilerplate header](https://nav.readthedocs.io/en/latest/hacking/hacking.html#python-boilerplate-headers) to that …
=> Document practical usage of devcontainer

changelog.d/3346.added.md, python/nav/django/context_processors.py, python/nav/models/profiles.py, python/nav/web/auth/utils.py, python/nav/web/sass/nav/custom.scss, python/nav/web/templates/base.html, python/nav/web/useradmin/views.py, tests/integration/web/auth/utils_test.py, tests/integration/web/webfront_test.py
Fixes #3346. Dependent on #3407.
Screenshots:
Before:
After:
=> Show banner to admins for other users' password issues 

changelog.d/3350.added.md, python/nav/web/ipdevinfo/urls.py, python/nav/web/ipdevinfo/views.py, python/nav/web/sass/nav/ipdevinfo.scss, python/nav/web/static/js/src/ipdevinfo.js, python/nav/web/templates/ipdevinfo/frag-ipdevinfo-alert-box.html, python/nav/web/templates/ipdevinfo/frag-ipdevinfo-refresh-button.html, python/nav/web/templates/ipdevinfo/frag-ipdevinfo-refresh-ongoing-button.html, python/nav/web/templates/ipdevinfo/frag-ipdevinfo.html
This PR represents a mob effort of working out an implementation for #3350. Since it reached maturity, its history has been rebased and edited to present cleanly.
All involved in the mob effort are happy with it, we're just waiting for @hmpf to review it, since she wasn't present at the mob meetings.
Follow up issue #3448.
=> Implement ipdevinfo UI for ipdevpoll job refreshing

doc/hacking/using-devcontainers.rst, tools/reset-jwt-keys.sh
This adds and documents another developer tool script to the `tools/` directory: `reset-jwt-keys.sh`.  This script can be used (mainly inside the devcontainer environment) to generate a new pair of JWT signing keys and configuring NAV to use them.
* ~~[ ] Added a changelog fragment for [towncrier](https://nav.readthedocs.io/en/latest/hacking/hacking.html#adding-a-changelog-entry)~~
* ~~[ ] Added/amended tests for new/changed code~~
* ~~[ ] If applicable: Created new issues if this PR does not fix the issue completely/there is further work …
=> Add developer script to re-generate JWT signing keys

python/nav/bin/radiusparser.py, python/nav/smidumps/DNOS-SWITCHING-MIB.py
Fixes some `SyntaxWarning` issues detected in #3266.  Some of these are merely warnings in Python 3.12, but become errors in Python 3.13.
=> Fix Python 3.12 SyntaxWarnings

tests/unittests/dhcpstats/kea_dhcp_test.py
This ensures pytest doesn't try to collect this object as a potential testcase just because the name pattern matches.  I.e. make pytest stop warning about this object not being a valid test.
One of the things noted in #3467
=> Mark TestData namedtuple as *not a test case*

changelog.d/3477.changed.md, python/nav/web/static/js/src/netmap/control_view.js
Part of #2972. Resolves #3459.
Replaces a small piece of foundation with a jquery implementation. It could probably be replaced by some simple Alpine/Hyperscript later.
You can view the changes in the Netmap tool. The "View options" button shows a panel, and makes sure that all elements have the same height (equalizing). 
* Replaces the foundation equalizer in control view with a jquery implementation
Removes this line of foundation js:
https://github.com/Uninett/nav/blob/813b12a2773b5f8d07ec9b580ec236f239abf733/python/nav/web/static/js/src/netmap/control_view.js#L129
[Hacker's guide to …
=> Replace foundation equalizer with jquery

.devcontainer/Dockerfile, .devcontainer/devcontainer.json, .devcontainer/docker-compose.yml
This fixes several issues with the devcontainer definition, after experiencing a Docker caching dumpster fire on my dev machine.
* cleans up `devcontainer.json` indentation/syntax
* Removes unused variables and unused build stages
* Moves container build arguments to `docker-compose.yml` where they actually have an effect.
=> Clean up devcontainer dumpster fire

changelog.d/3222.added.md, python/nav/web/ipdevinfo/views.py, python/nav/web/templates/ipdevinfo/frag-ipdevinfo.html
Fixes #3222 
Adds MAC address of the device on the ipdevinfo Device Info tab.
Draft because: Is there a better source for MAC address? If there are multiple, should all be shown? Currently it should use the most recent ARP record
=> Show MAC address in ipdevinfo

python/nav/web/auth/__init__.py, python/nav/web/auth/ldap.py, python/nav/web/auth/middleware.py, python/nav/web/auth/sudo.py, python/nav/web/webfront/views.py
As part of moving towards MFA (#2248, #2688) and more modularization/Django-ification of the NAV authentication and authorization system, this adds type annotations to the involved functions - mostly as an attempt to slightly ease the understanding of what is going on in the current incarnation.
=> Add type annotations to authentication system

changelog.d/3494.changed.md, python/nav/web/radius/urls.py, python/nav/web/radius/views.py, python/nav/web/templates/radius/_account_chart_hints_modal.html, python/nav/web/templates/radius/_account_log_hints_modal.html, python/nav/web/templates/radius/_error_log_hints_modal.html, python/nav/web/templates/radius/account_charts.html, python/nav/web/templates/radius/account_log.html, python/nav/web/templates/radius/error_log.html, tests/integration/web/radius_test.py
Part of #2972, based on #3454.
Uses HTMX modals to replace foundation implementation on search hints for the following tabs:
* Account Log: /radius/acctsearch
* Error Log: /radius/logsearch
* Top Talkers: /radius/acctcharts
There is another usage of foundation in the Status tool, namely the #details_modal in `account_log.html`. 
However, I do not have any test data to display at the moment, and the modal is used to display details about a given result.
Edit: 040925 10:30 (post review by @johannaengland) 
Made the modals smaller to better fit the text content and increase usability. They are also using the current max size (large). The modal could be made wider by using the "fit-content" size, but a lot of long single lines of text is not very user friendly.
Every pull request should have …
=> Replace search hint modals in Radius tool

changelog.d/+da97b5a4.changed.md, python/nav/web/ipdevinfo/urls.py, python/nav/web/ipdevinfo/views.py, python/nav/web/templates/ipdevinfo/_poe_classification_hint_modal.html, python/nav/web/templates/ipdevinfo/_poe_status_hint_modal.html, python/nav/web/templates/ipdevinfo/frag-hostinfo.html, python/nav/web/templates/ipdevinfo/frag-ipdevinfo.html, python/nav/web/templates/ipdevinfo/poegroup-details.html, tests/integration/web/ipdevinfo_test.py
Part of #2972. 
This PR replaces the "DNS" modal on the ipdevinfo details page for a Netbox, and the status/classification hints in the PoeGroup tab.
The changes can be verified at the following locations:
* DNS modal: [/ipdevinfo/sikt-bgo-6101-sw1.c.uninett.no](http://localhost:8000/ipdevinfo/sikt-bgo-6101-sw1.c.uninett.no/)
* Status and Classification Hint: [/ipdevinfo/sikt-bgo-6101-sw1.c.uninett.no/poegroup=1/](http://localhost:8000/ipdevinfo/sikt-bgo-6101-sw1.c.uninett.no/poegroup=1/)
=> Replace ipdevinfo modals

changelog.d/+9652911e.changed.md, python/nav/web/templates/threshold/_threshold_help_modal.html, python/nav/web/templates/threshold/set_threshold.html, python/nav/web/threshold/urls.py, python/nav/web/threshold/views.py, tests/integration/web/threshold_test.py
Part of #2972.
This PR replaces the "Help" modal in the Add Threshold and Edit Threshold views.
* Replace threshold help modal with HTMX implementation
=> Replace threshold help modal with htmx

changelog.d/3523.fixed.md, python/nav/web/alertprofiles/views.py
When reviewing #3497 I noticed that in the "Alerts you have permissions to receive" in the "Groups and Permissions" modal in alert profiles duplicate entries were shown to me. This cleans this up by using the `distinct()` method to the query set. 
To reproduce: 
You need to be part of different groups that have permissions to see the same filter groups. 
Go to http://localhost:8000/alertprofiles/, click on the "Groups and Permissions" link, see duplicate filter groups in the "Alerts you have permissions to receive"  column.
based on master …
=> Show distinct filter groups in "Groups and Permissions" modal in alert profiles

changelog.d/+cc270e47.fixed.md, python/nav/web/static/js/src/main.js
This PR fixes a bug introduced by removing the `[data-topbar]` plugin in #3476. Some magic is done in `_topbar.scss`, requiring the `.hover` class to be present on the `.has-dropdown` container in order for elements to be considered visible and thus processable by HTMX.
Fixed the bug by toggling the `.hover` class on the `.has-dropdown` container when clicking the trigger, and removing the `.hover` class when clicking outside.
=> Fix bug where QR Code button is not clickable

.devcontainer/devcontainer.json
I noticed that every time I rebuild my devcontainer I have to install the ruff extension manually, which is annoying and when I forget about it VSCode chooses to format the code with autopep instead, which leads to a lot of unintended changes. 
=> Add ruff extention to vscode part in devcontainer

python/nav/web/static/js/src/networkexplorer.js
Follow-up to #3534, adding logic to show an error message from the backend, with "Search failed!" as the fallback.
No-news as this is part 2, and #3534 already added a news fragment.
**Specific error message is shown in the frontend**
=> Show error messages from backend in network explorer

python/nav/web/sass/nav/custom.scss, python/nav/web/templates/webfront/index.html, python/nav/web/webfront/urls.py, python/nav/web/webfront/views.py, tests/integration/web/webfront_test.py
Resolves #3558, part of #2344. 
Dependent on #3553.
This PR adds support for exporting shared dashboards, and an export action to the widget actions. I also added tests for the export view, as there were none.
In addition, I fixed a weird bug where a non-admin can't open the import modal due to this fun typo: `/îndex/dashboard/importmodal` instead of `/index/dashboard/importmodal`.
=> Shared dashboards: Export and import of shared dashboards

python/nav/web/templates/webfront/_dashboard_nav.html, python/nav/web/templates/webfront/_dashboard_nav_shared_indicator.html, python/nav/web/templates/webfront/_dashboard_settings_shared_form.html, python/nav/web/webfront/views.py
Part of #3554. Fix for #3551, from comment by @lunkwill42.
I implemented this change as a separate PR, since the base branch is quite large now with merged code from dependents.
This PR updates the shared indicator in the dashboard nav when the shared setting is changed in the settings form
https://github.com/user-attachments/assets/4141c867-bf5a-457f-b195-cbb92e6da3c6
=> Update shared indicator after changing shared settings
