python/nav/ipdevpoll/plugins/statports.py, python/nav/web/ipdevinfo/utils.py, python/nav/web/ipdevinfo/views.py
Hi all, I added broadcast & multicast counters to interfaces counters collection & web display (ipdevinfo), as per unicast counters these can be short or long format (OCTET_COUNTERS or HC_OCTET_COUNTERS). These kind of counters are standard defined, so are included in common MIBs. AlexDF
=> added broadcast & multicast counters to interfaces (ipdevinfo)

python/nav/report/IPtools.py, python/nav/report/matrixIPv4.py
This allows us to show "available addresses" for scopes with no sub-scopes. Ideally we would just return an error to the user, as this makes no sense, but the subnet matrix is sufficiently complex that we probably might risk running into edge-cases.
Signed-off-by: Emil Henry <emilhf@stud.ntnu.no>
=> Fix invariant error, resolves #1414

python/nav/mibs/powernet_mib.py
Quote from the MIB: The bank number to which this record refers. A
value of 0 will be returned if any bank is not present or if it is
phase related.
This makes the sensor descriptions more informative and better aligned
with the web interface for APC AP8886 PDUs
=> Powernet: Distinguish between phase load and bank load sensors.

htdocs/sass/nav/ipam.scss, htdocs/static/js/src/ipam/app.js, htdocs/static/js/src/ipam/models.js, htdocs/static/js/src/ipam/views/control.js, htdocs/static/js/src/ipam/views/prefixmap.js, htdocs/static/js/src/ipam/views/subnetallocator.js, htdocs/static/js/src/ipam/views/tree.js, htdocs/static/js/src/subnetmatrix.js, python/nav/web/api/v1/helpers/prefix_collector.py, python/nav/web/api/v1/serializers.py, python/nav/web/api/v1/views.py, python/nav/web/ipam/prefix_tree.py, python/nav/web/ipam/util.py, templates/ipam/includes/allocate-subnet.html, templates/ipam/includes/tree-form-advanced.html, templates/ipam/includes/tree-node.html, templates/report/frag_matrix_report.html
This fixes a couple of minor visual aspects of the IPAM, adding the description to the prefix listing itself (allowing for quick perusal) and providing more useful context in the tooltips (VLAN, description). This should make it more comfortable to crawl prefixes with many sub-allocations.
Also fixes a minor API bug where information about the top-level prefix is not returned when searching for available address space for delegation purposes. This allows us to draw more stuff in the prefix allocation viz, for example a tooltip displaying the VLAN id.
=> Minor IPAM improvements

NOTES.rst, bin/dump.py, htdocs/sass/nav/seeddb.scss, htdocs/static/js/src/seeddb_netbox.js, python/nav/bulkimport.py, python/nav/bulkparse.py, python/nav/eventengine/plugins/linkstate.py, python/nav/ipdevpoll/__init__.py, python/nav/ipdevpoll/plugins/linkstate.py, python/nav/ipdevpoll/plugins/statports.py, python/nav/ipdevpoll/plugins/statsensors.py, python/nav/ipdevpoll/plugins/statsystem.py, python/nav/models/manage.py, python/nav/web/seeddb/page/netbox/__init__.py, python/nav/web/seeddb/page/netbox/forms.py, python/nav/web/seeddb/utils/list.py, sql/changes/sc.04.07.0011.sql, templates/ipdevinfo/frag-ipdevinfo.html, templates/seeddb/list.html, templates/seeddb/list_netbox.html, templates/seeddb/netbox_wizard.html, tests/integration/bulkimport_test.py, tests/unittests/general/bulkparse_test.py
Fixes #1489 
This pull request is not complete yet. A few adjustments are needed on the UI after feedback, and the entire functionality should be reviewed by @mdiehm.
=> Avoid redundant port counter collection from virtualized instances, such as Cisco VRF

docker-compose.yml
While working with NAV this summer I noticed an edge-case where the nav-container would quit because postgres had not started properly yet. This should fix the problem.
=> Added dependency in docker-compose

python/nav/web/machinetracker/forms.py, python/nav/web/machinetracker/views.py, templates/machinetracker/ip_search.html, templates/machinetracker/ip_tracker.html
Added a checkbox for displaying which router the data originated from.
Fixes #1506
=> Added option for showing origin in machinetracker

python/nav/arnold.py, python/nav/portadmin/snmputils.py, python/nav/web/portadmin/views.py, tests/unittests/portadmin/portadmin_test.py
The base SNMPHandler's get_vlan and set_vlan methods accepted a baseport as argument, while the cisco subclass accepted an ifindex. Various callers called these with ifindex. Changed both versions to accept an Interface as arguments and hide the details from the caller
Fixes #1560
=> (portadmin) Fix confusion regarding baseport vs ifindex

python/nav/pgsync.py, sql/changes/sc.03.08.0000.sql, sql/changes/sc.03.13.0001.sql, sql/changes/sc.03.14.0001.sql, sql/changes/sc.03.15.0002.sql, sql/changes/sc.03.15.0070.sql, sql/changes/sc.04.03.0002.sql, sql/changes/sc.04.06.0052.sql, sql/changes/sc.04.07.0001.sql, sql/changes/sc.04.07.0060.sql, sql/changes/sc.04.07.0100.sql
Fixes so that pgsync correctly inserts existing non-required schemas to the search_path
=> Fixed deleting non-required schemas in search_path

python/nav/django/auth.py, python/nav/models/api.py, python/nav/models/arnold.py, python/nav/models/cabling.py, python/nav/models/event.py, python/nav/models/logger.py, python/nav/models/manage.py, python/nav/models/msgmaint.py, python/nav/models/profiles.py, python/nav/models/rack.py, python/nav/models/service.py, python/nav/portadmin/snmputils.py, python/nav/watchdog/tests.py, python/nav/web/macwatch/models.py, python/nav/web/webfront/utils.py
All places where it was easy to convert `__unicode__` to work on python3.
There's still usage of `__unicode__` in:
```
nav/netmap/stubs/__init__.py
nav/macaddress.py
tests/unittests/netmap/metaclass_testcase.py
tests/unittests/portadmin/portadmin_test.py
```
These will take slightly more effort.
=> Sixify dunder unicode, easy pickings

python/nav/django/settings.py
The following should work on both 1.7 and 1.8, and should be easy to clean up after moving to 1.8+.
=> Update template settings to work on Django 1.8+

Jenkinsfile, Jenkinsfile-common, Jenkinsfile3, requirements/base.txt, tests/docker/Dockerfile, tests/docker/Dockerfile3, tests/docker/Makefile, tests/docker/scripts/build.sh
A separate multibranch pipelinejob has been established in Jenkins, to look for branches with their pipeline defined in `Jenkinsfile3`. This file should script whatever is necessary to run the pipeline in a Python 3 environment.
Would like some feedback before merging.
=> Split Jenkinsfile into Python 2 and Python 3 testing environments

python/nav/web/netmap/cache.py
This fixes #1583 by attempting to keep everything in unicode. It's not particularly portable to Python 3 as it stands, though. Some feedback would be appreciated :)
=> Netmap cache unicode fix

python/nav/mibs/entity_sensor_mib.py
…n entPhySensorUnitsDisplay in shared parent plugin
This fixes a regression introduced in b3ae9b767b8dd0e2ef006d7eefa3a8869520518b
=> Unbreak CiscoEntrySensorMIB by not trying to fetch unused snmp column

NOTES.rst, python/nav/util.py, python/nav/web/api/v1/views.py, python/nav/web/useradmin/forms.py, requirements/base.txt
This removes the dependency to the external library, which is now non-maintained for several years.
The function may ideally be replaced in the future by something using the `secrets` module to generate the token.
=> Remove django-oauth2-provider library dependency

sql/baseline/arnold.sql, sql/baseline/manage.sql, sql/baseline/manage2.sql, sql/baseline/navprofiles.sql, sql/baseline/types.sql, sql/changes/sc.04.07.0110.sql, sql/changes/sc.04.08.0001.sql, sql/changes/sc.04.08.0020.sql, sql/changes/sc.04.08.0050.sql, sql/changes/sc.04.08.0410.sql, sql/changes/sc.04.08.1000.sql, sql/changes/sc.04.08.1001.sql
I did a bad job of reviewing #1544 - as it turns out, even though the new baseline passes the "diff test", the actual implementation is quite messy - altering table definitions after the fact, and trying to clean up data that just isn't there, since the baseline always represents a clean install. 
It seems all the mess stems from uncritically copy+pasting change scripts into the baseline, without actually consolidating the changes they represent with the existing definitions.
So, this is basically a work-in-progress to clean up the results of #1544, so we can have a proper implementation of #1510.
=> SQL baseline cleanup

etc/toolbox/auditlog.tool, htdocs/static/js/src/porttable.js, python/nav/auditlog/api.py, python/nav/auditlog/models.py, python/nav/auditlog/urls.py, python/nav/auditlog/utils.py, python/nav/auditlog/views.py, python/nav/web/auth.py, python/nav/web/ipdevinfo/urls.py, python/nav/web/ipdevinfo/views.py, python/nav/web/portadmin/views.py, python/nav/web/seeddb/page/netbox/edit.py, python/nav/web/seeddb/utils/delete.py, python/nav/web/useradmin/views.py, python/nav/web/webfront/views.py, sql/changes/sc.04.08.0085.sql, templates/auditlog/_logentry_list.html, templates/auditlog/base.html, templates/auditlog/logentry_list.html, templates/auditlog/overview.html, templates/ipdevinfo/frag-alerts.html, templates/ipdevinfo/frag-auditlog.html, templates/ipdevinfo/ipdev-details.html, templates/portadmin/netbox.html, templates/useradmin/account_detail.html, templates/useradmin/account_list.html, templates/useradmin/base.html, templates/useradmin/frag-auditlog.html
Auditlog did not display log entries properly. There were inconsitencies between getting data from context or api.
Changes done:
- Add log entries on crud of profiles
- Add log entries on crud of devices
- Add log entries when logging in and out
DataTable
- Use api only for data
- Add filters, sorting and searching
- Add DataTable to ipdevinfo (new tab)
- Fix DataTable for portadmin
- Fix DataTable main tool
- Add DataTable to user info (list and details)
=> Fix broken auditlog browsing and auditlog more things

python/nav/topology/analyze.py, python/nav/topology/detector.py, python/nav/topology/diff.py
Proposition to fix #1669 
There is, however, a further problematic issue: In most cases of link-aggregation, the L2 topology will appear disjunct from the VLAN topology, since L2 is discovered for the physical ports, while the VLAN layer is on the logical ports. Further changes to VLAN discovery are needed.
=> Do not consider CAM data from aggregator ports when there is LLDP/CDP topology available from its aggregated ports

Dockerfile3, bin/servicemon.py, bin/snmptrapd.py, doc/conf.py, docker-compose.yml, python/nav/logs.py, python/nav/startstop.py, python/nav/util.py, tests/integration/logs_test.py
Added a Docker environment for running the NAV development container under Python 3 and Django 1.8.
More importantly, offers a way to switch between the environments using `docker-compose` builtin mechanisms.
Fixed various Py3-related bugs found while trying to deploy NAV inside the new container.
=> More python3

python/nav/django/auth.py, python/nav/models/profiles.py
By setting the `sudo_operator` attribute of an Account object, its string
representation will reflect which account is operating as this account.
The AuthenticationMiddleware sets this attribute when necessary, and the
resulting string representation of the apparent logged-in user will be
reflected in the audit logs.
This fixes #1706 (as an alternative to #1707)
=> make Account objects "sudo operator aware"

NOTES.rst, python/nav/auditlog/api.py, python/nav/django/settings.py, python/nav/models/profiles.py, python/nav/web/api/v1/alert_serializers.py, python/nav/web/api/v1/filter_backends.py, python/nav/web/api/v1/serializers.py, python/nav/web/api/v1/urls.py, python/nav/web/api/v1/views.py, python/nav/web/ipam/api.py, python/nav/web/navlets/status2.py, python/nav/web/netmap/serializers.py, python/nav/web/netmap/views.py, python/nav/web/useradmin/forms.py, requirements/base.txt, requirements/django.txt, requirements/django110.txt, requirements/django111.txt, requirements/django18.txt, requirements/django19.txt, templates/base.html, templates/status2/status.html, tests/integration/api_test.py, tests/integration/conftest.py
Upgrade Django Rest Framework to at least support Django 1.8
As tests are passing now I consider this complete. For the reviewers - verify model-changes and take a look at the tests to see if they are sane.
=> Upgrade Django Rest Framework

python/nav/report/dbresult.py, python/nav/report/generator.py, templates/report/frag_report_filters.html
After fixing bugs in Report, I was compelled to refactor and clean some of the code I found.
Primarily, this cleans the method responsible for parsing report query arguments from the web page, by breaking it into a set of smaller methods, improving variable names and removing dead or useless code.
It also fixes a problem wherein any errors flagged by the query argument parsing were never passed up to the user interface, but happily ignored with potentially strange consequences for the search result.
=> Clean Report code

NOTES.rst, bin/alertengine.py, bin/pping.py, bin/servicemon.py, bin/smsd.py, bin/snmptrapd.py, etc/alertengine.conf.in, etc/init.d/snmptrapd.in, etc/smsd.conf.in, python/nav/eventengine/daemon.py, tests/integration/pping_test.py
Goals of this PR:
* Ensure all NAV daemons have the same command line options to select "foreground mode"
* Ensure all NAV daemons log to `stderr` until they eventually daemonize, at which point `stderr` will be redirected into the configured log file
* No daemons need to reload log files on `SIGHUP` while running in the foreground, since they arent logging to a file.
* All daemons that can be run in the foreground should be able to handle `SIGINT` without crashing with a traceback.
Motivation for these changes is mainly to allow for external control of how daemons are started and where their logs are sent - which is a big factor if NAV is being run in container systems likes Kubernetes.
=> Make logging and daemonization options more consistent across NAV daemons

python/nav/models/fields.py, python/nav/web/devicehistory/utils/history.py, python/nav/web/devicehistory/views.py, python/nav/web/machinetracker/utils.py, python/nav/web/machinetracker/views.py, tests/integration/models/model_test.py
This PR gets rid of the remaining warnings for running NAV on Django 1.8, in code that we control.
=> No warnings for Django 1.8

python/nav/django/auth.py, python/nav/django/legacy.py
I get an ImportMismatchError when testing locally again so here's to hoping the official CI is sufficiently different.
=> Make middlewares work correctly on Django 1.10+

etc/geomap/popup_network.html, etc/geomap/popup_network_open.html, etc/geomap/popup_place.html, etc/geomap/popup_place_open.html, python/nav/django/settings.py, python/nav/web/geomap/features.py, python/nav/web/geomap/output_formats.py, python/nav/web/geomap/templatetags/geomap.py, tests/integration/web/geomap_test.py
Remove strange Geomap hack used to provide two template tags to its popup templates. The setup-py branch added a test that uncovered this problem for Django >= 1.8.
=> Fix geomap templatetags

python/nav/web/info/views.py, templates/info/base.html, tests/integration/web/info_test.py
This fixes #1796 by catching unhandled exceptions in individual search providers, and providing this information to the user (as well as logging the actual tracebacks to the logging system).
=> Gracefully handle exceptions from individual search providers

python/nav/web/api/v1/filter_backends.py, python/nav/web/api/v1/views.py, tests/integration/api_test.py
The problem seems to stem from upgrading the Django REST Framework dependency on the _master_ branch.
I'm not entirely sure of how to solve this quite yet, but  I'm adding a test to expose the issue here.
=> The /alert API endpoint crashes with a TypeError

htdocs/sass/nav/custom.scss, htdocs/static/js/src/plugins/delegate_tooltip.js, python/nav/web/api/v1/views.py, templates/ipdevinfo/port-details-api-frag.html, templates/navlets/status2_view.html
Fixes #1667 
Create a template for the API interface endpoint that is returned when using the special text/x-nav-html accept header.
Use this to render a tooltip displaying information about an interface in the status widget when hovering above the interface name.
=> WIP: Interface tooltip

doc/hacking/index.rst, doc/hacking/web-interface-customization.rst, python/nav/web/templates/info/room/roominfo.html, python/nav/web/templates/ipdevinfo/ipdev-details.html
We need to add hooks to include custom tabs on the ipdevinfo and room/info pages, as several users are already using "unhealthy" practices by overriding entire NAV templates - a behavior that will likely break their NAV sites, at worst, or render new functionality missing on upgrades, at best
This adds and documents a simple hook for including third party templates into the tabbing code of these pages.
=> Add hook to customize tabs in ipdevinfo and info/room

python/nav/portadmin/snmputils.py
=> Save config to non volatile memory in portadmin for dell switches

python/nav/ipdevpoll/timestamps.py
Django on python3 will not allow pickle data in a text column.
As a backwards compatibility we still try to read the values as pickle if json decoding fails
=> (ipdevpoll) Save netbox poll timestamps in database as json

python/nav/bitvector.py, python/nav/oidparsers.py, python/nav/six.py
DeprecationWarning: tostring() is deprecated. Use tobytes() instead.
This was not solved in six.
Note: this gives a deprecation warning all the way up to and including python 3.7, so it is not exactly a high priority to fix, but warnings are annoying and can hide real problems, so..
=> get rid of DeprecationWarning, array.tostring()

bin/navdump
The non-header lines were circumfixed with ``b'``, ``'`` because
``print()`` casts ``bytes()`` to ``str()`` on python 3.
Output of navdump isn't checked in tests, I've added ticket #1868 to discuss/address that.
=> fix navdump output on python3

python/nav/web/ipam/api.py, python/nav/web/ipam/util.py, python/nav/web/static/js/src/ipam/views/subnetallocator.js, python/nav/web/templates/ipam/includes/allocate-subnet.html, requirements/base.txt, tests/unittests/web/ipam/util_test.py
Changes UI to ask for a prefix length, rather than number of addresses wanted. Assume NAV users are networking people and know how this works. Asking for number of addresses makes no sense for ipv6.
The `partition_subnet()` function is essensially the same as the ipaddress modules `IPXNetwork.subnets()` function, so use that (include polyfill on python2)
Fixes #1594
=> Fix IPAM subnet allocation suggestions for ipv6

Jenkinsfile, tox.ini
This should remove the need to completely rebuild tox environments from scratch when NAV requirements  change.
`pip-compile` is used to build a complete requirements manifest for each tox environment, and `pip-sync` is used to keep the environment in sync with this manifest.
=> Use pip-tools to keep test environment dependencies in sync

python/nav/eventengine/topology.py, python/nav/netmap/topology.py, python/nav/topology/analyze.py, python/nav/topology/vlan.py, python/nav/web/netmap/graph.py, requirements/base.txt, tests/unittests/netmap/multidigraph_to_undirect_test.py
This fixes a bunch of warnings when running tests. The version we were using did not officially support python 3.5+
=> Update to most recent version of networkx

NOTES.rst, bin/nav, doc/intro/install.rst, python/nav/config.py
To avoid having every NAV daemon individually fail on startup because of faulty or missing options in `nav.conf`, the `nav start` command should make some attempt to verify the validity of the minimally required options and refuse to start NAV if the requirements aren't met.
Required options were added to NAV 4.9, but several users have been confused as to why NAV would not start, when they forgot to update their `nav.conf` as part of the upgrade.
=> Verify nav.conf values as part of nav start

bin/alertengine.py, bin/macwatch.py, bin/maintengine.py, bin/smsd.py, python/nav/activeipcollector/collector.py, python/nav/activeipcollector/manager.py, python/nav/alertengine/base.py, python/nav/eventengine/engine.py, python/nav/ipdevpoll/schedule.py, python/nav/logs.py, python/nav/models/profiles.py, python/nav/topology/detector.py, python/nav/web/auth.py
Some of these are really weird. It might be necessary to split the easy ones out, and deal with the true weirdos separately. 
Things found: setting the logger in a function or method with `global`, passing a logger around, functions with their own separate loggers, etc.
Remains: mucho magic in `nav.logs`, and usage of that magic.
=> Standardize even more logging-statements

python/nav/models/manage.py
The argument `on_delete` is obligatory (and positional, second position) in Django 2.2, for every ForeignKey/OneToOneKey. The previous implicit default was `on_delete=models.CASCADE`.
Adding this to the new models will make for a simpler merge of the Django 2.2 branch and this PR itself serves as a reminder that all new models with ForeignKey/OneToOneKey should have an explicit `on_delete` from now on.
=> Make fresh code forwards compatible with Django2.2

doc/reference/ldap.rst, python/nav/etc/webfront/webfront.conf, python/nav/web/auth.py, python/nav/web/ldapauth.py, tests/unittests/general/webfront_test.py
This adds the `admin_entitlement` option to the `[ldap]` section of `webfront.conf`. The new option enables using LDAP entitlements to configure which users should receive administrator privileges in NAV.
This is basically a newly discovered requirement of the CNaaS pilot project.
=> Add option to control user administrator privileges from LDAP

python/nav/ipdevpoll/timestamps.py, tests/unittests/ipdevpoll/timestamps_test.py
I don't really see the value of keeping support for old pickle values in the timestampchecker. The timestampchecker is only part of a "caching" mechanism. It's okay to invalidate the cache when upgrading to the next NAV version (sometimes, even necessary, when collector bugs have been fixed).
=> Drop support for old pickled timestamps.

python/nav/ipdevpoll/neighbor.py, python/nav/ipdevpoll/plugins/cdp.py, python/nav/ipdevpoll/plugins/lldp.py, python/nav/ipdevpoll/shadows/__init__.py, python/nav/ipdevpoll/shadows/adjacency.py, python/nav/ipdevpoll/utils.py, python/nav/mibs/lldp_mib.py, tests/unittests/ipdevpoll/neighbor_test.py
@sigmunau initiated #1957 - but there were multiple problems running the unaltered LLDP and CDP plugins under Python 3 on the master branch. These issues had to be fixed first.
This PR also incorporates part of Sigmund's PR (specifically, the `CDPNeighbor` and `LLDPNeighbor` classes have been moved to their respective plugins).
=> Fix binary/string/unicode issues in the neighbor discovery system when running under Python 3

python/nav/models/sql/changes/sc.04.09.0200.sql
These unique constraints never had explicit names in the NAV schema, causing their names to become inconsistent between PostgreSQL versions.  This explicitly renames those constraints that still have the implicit names given by old PostgreSQL versions, to match those implicit names given by newer versions.
=> Ensure PostgreSQL unique constraints are consistently named

python/nav/pgsync.py
pl/pgSQL has been installed in all databases by default for many, many versions of PostgreSQL now. This routine was written while NAV still supported PostgreSQL 8.3, and has likely been superfluous since around PostgreSQL 9.1.
Now, this routine will fail on PostgreSQL 11, since the `createlang` command line has been removed, so it's time to retire this piece of code.
=> Stop explicitly installing pl/pgSQL during db init.

python/nav/web/templates/ipdevinfo/sensor-details.html
There was a typo in the attribute name, causing the scale attribute to always be displayed as empty.
=> Properly display sensor data scale on sensor details page.

python/nav/etc/ipdevpoll.conf
More and more people use NAV with Juniper switches. The presence of the juniperdot1 plugin, and the option to use it instead of the regular dot1q plugin in Juniper shops is not very obvious to the user. Since the plugin does not break functionality for non-Juniper-devices, this example config change will apply it as the default implementation for dot1q in ipdevpoll.conf - which should be more user friendly to Juniper users.
=> Use Juniper 802.1X VLAN workaround in default configuration

python/nav/netmap/traffic.py, python/nav/util.py, python/nav/web/geomap/db.py, python/nav/web/geomap/utils.py, python/nav/web/netmap/graph.py
I set out to fix an issue with failing Graphite-web requests from Netmap, and ended up discovering a hive of bad code, having been groped by multiple developers over time, with several issues that I fixed along the way.
The triggering issue was this: On a customer's installation, every Netmap layer 2 map generated would cause Graphite-web to produce a **400 Bad Request** response, as the request Netmap created would exceed Django's limit of 1000 variables in a single GET/POST-request (due to the fact that the generated request would contain a single `target` variable for *each traffic counter for each interface involved*, resulting in a request with **2200 targets**).
To fix this problem, I did two things:
1. I changed the code to split graphite requests into chunks of 500 targets each. …
=> Netmap layer 2 traffic data requests to Graphite are too slow and too large

doc/hacking/using-docker.rst, docker-compose.yml, tools/docker/run.sh, tools/docker/source-watch.sh, tools/docker/supervisord.conf, tools/docker/web.sh
To improve process isolation, and to enable having the log output of the development server more up-front when using Docker Compose, this PR moves the development server out of the nav service container and into a dedicated web container.
=> Run Django development server as a separate docker compose service

doc/contents.rst, doc/howto/generic-install-from-source.rst, doc/howto/installing-graphite-on-debian.rst, doc/howto/integrating-graphite-with-nav.rst, doc/howto/manual-install-on-debian.rst, doc/intro/getting-started.rst, doc/intro/install.rst
In reference to #2001, and to previous internal developer discussions, the installation docs need to be brushed up. Most people install NAV from pre-packaged versions, not from source code, so the official docs should present all the various installation options.
A potential further improvement might be to move the contents of https://nav.uninett.no/install-instructions/ into the Sphinx-based documentation also.
=> Refactor installation documentation.

python/nav/ipdevpoll/plugins/typeoid.py, tests/integration/ipdevpoll/plugins/typeoid_test.py, tests/integration/ipdevpoll/typeoid_test.py, tests/unittests/ipdevpoll/typeoid_test.py
The `typeoid` plugin had a bug in which a Netbox would not have its type properly set on the first run if a new type was created. The result of which would be that when a new device was added to NAV, its type would not be properly set for 6 hours (until the next inventory run). Lots of NAV code paths are selected based on the registered device vendor, and so the wrong code-paths would be chosen for the new device for these 6 hours, resulting in loss of proper monitoring.
The code of the plugin was hard to follow, as it was written before inlineCallbacks were a thing (hello callback hell), so I modernized the entire thing to use said inlineCallbacks model.
To fix the issues of the proper creation and assignment of a new type (and vendor), I changed the code to bypass the storage framework …
=> Make type changes immediately when unknown types are encountered

doc/conf.py, doc/exts/xref.py, doc/howto/generic-install-from-source.rst, doc/howto/integrating-graphite-with-nav.rst, doc/howto/manual-install-on-debian.rst, doc/intro/install.rst
Implements a Sphinx extension to define external links in the configuration, so we don't need to update lots of doc pages when the external link changes.
=> Remove external link redundancies in docs

python/nav/web/static/js/src/watchdog.js, python/nav/web/templates/watchdog/frag_overview.html, python/nav/web/watchdog/urls.py, python/nav/web/watchdog/views.py
Adds these elements to the "NAV by the numbers" info box in the Watchdog tool:
- The date of the oldest, closed ARP record
- The date of the oldest, closed CAM record
- A "pretty-printed" on-disk size estimate of the underlying PostgreSQL database.
=> Add more database stats to Watchdog's "NAV by the numbers"

NOTES.rst, doc/reference/backend-processes.rst, doc/reference/eventengine.rst, doc/reference/index.rst, python/nav/etc/eventengine.conf, python/nav/eventengine/alerts.py, python/nav/eventengine/engine.py, python/nav/eventengine/export.py, python/nav/eventengine/plugins/aggregatelinkstate.py, python/nav/eventengine/plugins/delayedstate.py, python/nav/eventengine/plugins/servicestate.py, python/nav/web/api/v1/alert_serializers.py
This implements basic functionality into eventengine to start an external process and feed a stream of serialized alert objects it has generated into that process' STDIN.
This can be used to integrate 3rd party software (such as an alert aggregator console) with the NAV event/alert system (as is identified as a requirement in the CNaaS project)
Further work:
=> Export stream of serialized alerts from the event engine

python/nav/web/seeddb/page/netbox/forms.py
The old way is correct for Python 2 but does not work in Python 3
because the signature of Exception.__init__ has changed.
The way that works for python 3 also works for python 2, so the old code
was more complex than necessary.
=> Fix faulty handling of exception message

python/nav/mibs/entity_mib.py, tests/unittests/ipdevpoll/mibs_test.py
Fixes #2016 and makes for safer code overall.
=> Log wrong type for `parse_dateandtime_tc()` value

doc/hacking/using-docker.rst, docker-compose.yml, tools/docker/build.sh
Because:
- It gets tedious to have two separate sets of config files to relate to when developing.
=> Share a configuration volume between nav and web dev containers

python/nav/web/portadmin/views.py
Because:
- Searching for a partial IP address causes a DataError
Using `IPy` to validate IP addresses can validate incomplete addresses. `IPy.IP` can deal with these. PostgreSQL, however, cannot. PortAdmin will generate a SQL statement comparing the raw query against an `INET` type field, which crashes.
Sample traceback:
```pytb
Internal Server Error: /portadmin/
Traceback (most recent call last):
File "/opt/venvs/nav/local/lib/python2.7/site-packages/django/core/handlers/base.py", line 132, in get_response
response = wrapped_callback(request, *callback_args, **callback_kwargs)
File "/opt/venvs/nav/local/lib/python2.7/site-packages/nav/web/portadmin/views.py", line 95, in index
if len(netboxes) == 1 and not interfaces:
File "/opt/venvs/nav/local/lib/python2.7/site-packages/django/db/models …
```
=> Fix PortAdmin crash on invalid IP search

python/nav/ipdevpoll/plugins/snmpcheck.py, tests/integration/ipdevpoll/plugins/snmpcheck_test.py, tests/unittests/ipdevpoll/plugins_snmpcheck_test.py
Because:
- The internal persisted state of the plugin may become out-of-sync with the official state in the alerthist table, at which point the snmpcheck plugin may stop sending the relevant alerts.
A more sane approach is to always send down-events if a device isn't responding - event engine will ignore the duplicates. In the normal case, when a device keeps responding, we only need to post UP events if there is an actual down-state to resolve in alerthist.
This was all supposed to have been fixed in #1782, but there were still corner cases if the eventengine processing malfunctions, which might cause an snmpAgentState alert to never be resolved.
This is a second stab at this fix, after realizing #2010 didn't cut it. The main difference is that this PR keeps the internal state, but uses …
=> Ensure internal snmp agent check state stays in sync with global snmpAgentState

python/nav/django/templatetags/info.py, python/nav/web/seeddb/page/netbox/__init__.py, python/nav/web/seeddb/utils/list.py, python/nav/web/templates/seeddb/list.html, python/nav/web/templates/seeddb/list_netbox.html
This implements both a replacement column for the SeedDB netbox list, but also improves the performance of the SeedDB netbox list page, by reducing the number of SQL queries from approximately **6+(5*N)** to **7** (which on a test data set of 259 netboxes amounts to a reduction **factor of 368**!)
=> Replace SNMP community columns in SeedDB netbox listing with management profile lists

python/nav/models/profiles.py
Some user accounts still have old-style password hashes in the NAV account database (meaning their password has not been changed in years!).
Under Python 3, the verification of such old-style hashes will crash during the web login phase, since a string object is fed to a `hashlib` hash function that expects a bytes object.
Ultimately, support for old-style password hashes should be phased out. This PR will re-hash a user's password whenever an old-style password hash is found and verified.
=> Don't crash when logging in users with old-style password hashes

python/nav/web/api/v1/serializers.py
Because:
- For some unexplained reason, the room locations were not writeable in the API, which they really should be in a full-fledged API.
Ideally, there should be a better representation of latitude/longitude in the API, such as the one available from `drf-extra-fields`: https://github.com/Hipo/drf-extra-fields#pointfield . However, we shouldn't change the API in a point release, and several pieces of frontend code rely on the existing serialization format.
=> Enable room geo positions to be writeable in API

python/nav/natsort.py, tests/unittests/natsort_test.py
Depending on the data set of any given NAV installation, multiple subsystems may break when using the `nav.natsort` library to sort strings in "natural" order, as Python 3 will not permit comparisons between integers and strings: A feature of Python 2 that `nav.natsort.split()` relies heavily on.
A traceback example from Portadmin:
```pytb
Traceback:
File "/opt/venvs/nav/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
41.             response = get_response(request)
File "/opt/venvs/nav/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
187.                 response = self.process_exception_by_middleware(e, request)
File "/opt/venvs/nav/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
185.                 response = …
```
=> Fix broken natural sort implementation on Python 3 

doc/hacking/hacking.rst, python/nav/django/urls.py, python/nav/django/views.py
Because:
- We need some way to test our 500 error handling.
=> Add a view to force a 500 error.

python/nav/web/api/v1/views.py
`AlertHistoryViewSet`, if the action is `retrieve`, adds the renderer `AlertFragmentRenderer`.
`AlertFragmentRenderer` adds to the context if `id` is in the serialized alert. It swaps out a netbox-id with a netbox, and adds the alert belonging to the id.
As of drf 3.6, the old method `resolve_context` is deprecated in favor of `get_template_context`. The former returns a `RequestContext` while the latter returns a `dict`.
There seems to be no tests covering `AlertHistoryViewSet.retrieve`, the closest seems to be `test_alert_should_be_visible_in_api'.
Fixes #2045
=> Switch to correct drf method

python/nav/web/geomap/features.py
The *best* way would be to ensure that all the popup templates can be
loaded like normal templates so that we instead could use
`django.template.loader.get_template`. Something for a minor release
though, not a patch.
Fixes #2041
=> Create the template a better way for Django 1.11

bin/navclean, python/nav/db/__init__.py
Fixes #2044 
`nav.db.escape()` still sucks.
=> Make navclean work properly on Python 3

python/nav/ipdevpoll/neighbor.py, python/nav/ipdevpoll/plugins/cdp.py, python/nav/ipdevpoll/plugins/lldp.py, python/nav/macaddress.py
Discovered and fixed while researching #2047, Cisco devices will oftentimes not return a sysname in a CDP record's deviceid field, but rather a 6-octet binary MAC address string. NAV uses the deviceid string to attempt to look up a sysname from the NAV database.
This:
1. Makes no sense if the deviceid is a MAC address. It could be looked up as MAC address instead.
2. Will crash if the MAC address string contains NUL bytes, which it often does, since the database layer will not support queries containing NUL bytes.
Typically, the problem is seen as the ipdevpoll `topo` job crashes and logs this:
> Job 'topo' for example-sw.example.org aborted: Job aborted due to plugin failure (cause=ValueError('A string literal cannot contain NUL (0x00) characters.',))
Since CDP records do not contain any …
=> Support MAC address device IDs from CDP records

python/nav/models/fields.py, tests/unittests/models/fields_test.py
Under Python 3, users with navlets whose config is stored in legacy pickle formats may experience failure to load these navlets in the NAV dashboard.
This is due to a crash bug where the pickle value is fed to `pickle.loads()` as a `str` object, rather than a `bytes`-like object.
**Traceback**
```pytb
Traceback:  
File "/usr/lib/python3.5/json/decoder.py" in raw_decode
355.             obj, end = self.scan_once(s, idx)
During handling of the above exception (0), another exception occurred:
File "/opt/venvs/nav/lib/python3.5/site-packages/nav/models/fields.py" in to_python
87.                 return json.loads(value)
File "/usr/lib/python3.5/json/__init__.py" in loads
319.         return _default_decoder.decode(s)
File "/usr/lib/python3.5/json/decoder.py" in decode
339.         obj, end = …
```
=> [BUG] Navlets crash/appear blank if their config is stored as legacy pickles

python/nav/statemon/RunQueue.py, python/nav/statemon/checker/MysqlChecker.py, python/nav/statemon/checker/SshChecker.py, python/nav/statemon/checkermap.py
Servicemon will not load any plugins when running on Python 3.
This fixes two problems with Python 3 compatibility in the servicemon engine itself, and two minor issues in individual Servicemon plugins.
=> Make servicemon run on Python 3

python/nav/mibs/lldp_mib.py, tests/unittests/mibs/lldp_mib_test.py
Fixes #2015 by ignoring the `LLDP-MIB::lldpRemTable` response from broken agents.
=> Ignore lldpRemTable results with broken row indexes

python/nav/web/static/js/src/status2/views.js, python/nav/web/templates/status2/status.html
The Status page will currently only show a maximum of 100 active alerts, since it does not take into account the API paging mechanism.
Ideally, the status page would also include paging, but implementing that seems to have a much larger scope than just artificially increasing the limit to 1000, which is what this PR does.
Implementing paging in the status page (which is based on Backbone, and not on datatables) seems to entail upgrading the Backbone version for all of NAV, and including backbone.paginator into the mix. Understanding Backbone at all is a plus.
=> Increase the max number of shown alerts in Status page to 1000 and provide feedback spinner when loading data

python/nav/portadmin/snmputils.py, tests/unittests/portadmin/portadmin_test.py
Because:
- Under Python 3, the strings retrieved using SNMP will actually be bytes objects.
- Whereas most of the other SNMP data PortAdmin works with is either integers or actual bytestrings, the aliases are human-readable (and human-configured) text.
Although SNMP is only defined for ASCII, some devices let you enter non-ASCII data as port aliases. Rarely through SNMP, but often through the CLI. This patch uses the existing safestring implementation to ensure the retrieved ifAlias values are decoded using one of the "supported" encodings.
Patch tested on affected customer installs.
Fixes #2093
=> Ensure ifAlias values are treated as strings

python/nav/models/manage.py, python/nav/web/ipdevinfo/views.py, python/nav/web/static/js/src/ipdevinfo.js
Fixes #2092 - but also reduces the number of ipdevinfo SQL queries generated to get `Sensor` objects.
=> Reduce the size of ipdevinfo's Graphite request to get the latest sensor data

python/nav/ipdevpoll/pool.py
I'm working on debugging a potential problem in NAV 5.0 where ipdevpoll workers sometimes just freeze, leaving jobs "running" indefinitely.
The (debug) log output from the ipdevpoll multiprocess pool module leaves a lot to be desired. This PR seeks to improve these logs to aid in the debugging of the issue.
Especially sad was the buffered log output from worker processes. I suspect this might even be part of the cause of frozen workers.
=> Improve ipdevpoll worker pool logging

tests/docker/Dockerfile, tests/requirements.txt, tests/unittests/netmap/multidigraph_to_undirect_test.py, tox.ini
We no longer need to run the test suite on Python 2.7 for NAV 5.1, but we *do* want to be able to run the suite on multiple Python 3 versions.
Debian isn't well suited for that; however, we can utilize the deadsnakes PPA to have multiple Python versions installed on an Ubuntu system.
This PR attempts to replace the CI container with a Ubuntu Bionic image, utilizing deadsnakes PPA to test on both Python 3.5 and 3.7 (and potentially other versions, once we get this to work).
=> Run test suite on Python 3.5 and 3.7

python/nav/portadmin/config.py, python/nav/web/portadmin/utils.py, python/nav/web/portadmin/views.py
Because:
- portadmin is weirdly split into the `nav.portadmin` and `nav.web.portadmin` packages.
- Config parsing code was kept in the `nav.web.portadmin` package, but will soon be needed also in `nav.portadmin`.
- It's, IMHO, best to coalesce everything config-parsing related into a module of its own.
- There may be import cycles if `nav.portadmin` modules begin importing stuff from the `nav.web.portadmin` package.
=> Refactor portadmin configuration parsing bits

python/nav/web/seeddb/utils/list.py
**Describe the bug**
The SeedDB room listing would display geographical coordinates like e.g. `(Decimal('63.414868887417'), Decimal('10.4065664274869'))`, which is just confusing to the end-user (this looks like a simple `repr()` of the internal storage format, which is a tuple of Decimal objects).
A more natural display value would be just `63.414868887417, 10.4065664274869`.
This PR sets out to do just that.
**Environment (please complete the following information):**
- NAV version installed: 5.0.4
=> [BUG] Latitude/Longitude is displayed weirdly in the SeedDB room list

python/nav/portadmin/snmp/base.py, python/nav/web/portadmin/utils.py, tests/unittests/portadmin/portadmin_test.py
Because:
- The ugly `create_dict_from_tuplelist()` function was only ever used to convert the output of `get_all_vlans()` and `get_all_if_alias()` to dicts.
- The `get_all_vlans()` and `get_all_if_alias()` methods were only ever used by `get_and_populate_livedata()`, so it made sense to change the API to just return the desired dicts in the first place.
=> Factor out unnecessary dict conversion function

python/nav/portadmin/config.py, python/nav/web/portadmin/utils.py, python/nav/web/portadmin/views.py
This refactors all configuration parsing/access in PortAdmin to use the more standardized `nav.config.NAVConfigParser`, which also offers a way to document default values more clearly.
Because:
- Config access was still all over the place in the PortAdmin code.
- Config access contained lots of redundant code.
- Almost every config access function would read the complete config file over again, just to get a single option.
- It's best to have a single pattern for parsing config files in NAV, and `nav.config.NAVConfigParser` is it.
For the end-user, these changes have only a single implication: _Any config changes to portadmin.conf will now require a restart of the web/wsgi server to take effect._
=> Use nav.config.NAVConfigParser for PortAdmin configuration

python/nav/portadmin/handlers.py, python/nav/portadmin/snmp/base.py, tests/unittests/portadmin/portadmin_test.py
Up until now, the `SNMPHandler` class was a base class for generic SNMP operations used by PortAdmin. 
To avoid redundancies when we write support for multiple protocols, it's best to define a common interface of the operations that must/should be supported by any implementing class. This PR sets out to do exactly that, without breaking any of the existing functionality.
Some code cleanup along the way. More will probably come in other PRs.
=> Extract an interface from PortAdmin's SNMPHandler class

python/nav/web/status2/views.py
Because:
- Status filter preferences aren't critical and can be easily re-created by the
users who still have them.
- Unpickling the preferences string as a fallback will crash on Python 3, since
the unpickler requires a bytes object. Keeping support would require encoding
the string as e.g. UTF-8, but why do we want to keep doing this ourselves?
=> Drop support for legacy status preference pickles

python/nav/ipdevpoll/config.py, python/nav/ipdevpoll/pool.py, requirements/base.txt
Since the cause of #2105 still has not been found, I'm taking the time to produce a potential workaround (which may still be useful if the cause of #2105 is found):
This PR implements a `Ping` command to the ipdevpoll worker AMP protocol, and uses this to regularly ping all running workers. Any worker who is not known to be done, and does not respond to a  ping request will be euthanized using a `SIGTERM` signal. The existing ipdevpoll scheduler will automatically reschedule the jobs that are lost/frozen as a consequence.
Please see comments in individual commits for various rationales.
=> Euthanize unresponsive ipdevpoll workers

python/nav/util.py, python/nav/web/ipdevinfo/host_information.py, python/nav/web/ipdevinfo/views.py, tests/integration/web/ipdevinfo_test.py
The ipdevinfo view `ipdev-details-by-name` will crash if fed certain device name in the URL.
Mostly, users will not enter the URL manually, but get there from clicking on various links from the UI. Two examples of crashing URLs came from the same customer data set:
LLDP/CDP neighbor records sometimes contains device identifiers that 
1. Look like binary garbage
2. Or, could be parsed as valid (although they aren't) valid IP addresses by  `IPy.IP`.
The ipdevinfo "Neighbors" tab, if the "unrecognized neighbors" checkbox is checked, will happily generated ipdevinfo device links from broken neighbor names.
This PR implements tests and fixes for both cases.
=> Prevent ipdevinfo from crashing on weird device names

python/nav/alertengine/base.py
Fixes #2165 
The malfunctioning code was in the overly huge and complicated `handle_queued_alerts()` function. I found the best way to reason about the logic of this code was to factor out much of the code into smaller pieces. This made it easier to track down the actual bug and fix it.
There seem to be no tests attached to this code, so my only guide to refactoring was to reason about how I know this is supposed to work from my many years of NAV experience. It would be easier to actually write some tests, now that it consists of smaller functions, but I did not take the time to do so.
I'm sure the code could stand a lot more refactoring too, but that could easily be posted as a separate issue.
=> Refactor and fix permanent delay bug in AlertEngine's processing of queued/delayed notifications

python/nav/web/useradmin/forms.py
Changing the login name or password of what is essentially a  pseudo-account can wreak on the NAV system and its security - so why not try to prevent it?
=> Prevent login/password changes to default account

python/nav/models/profiles.py, python/nav/web/sass/nav/useradmin.scss, python/nav/web/templates/useradmin/account_list.html, python/nav/web/templates/useradmin/base.html, python/nav/web/useradmin/views.py
This adds the following warnings about password issues in the Useradmin tool:
* Locked accounts
* Accounts with plaintext passwords
* Accounts with insecure password hashes
* Accounts with deprecated password hash methods
* Warnings about tampering with the `default` account.
These warnings are added as small icons (with tooltips) to the account list, and as session warning messages to the "edit account" page.
Methods for testing the password issues are added to the `Account` model class, and can be reused for scripting checks.
=> Warn about user accounts that have issues with their passwords

python/nav/ipdevpoll/plugins/lldp.py, python/nav/models/manage.py
Fixes #2106 .
This ensures the LLDP remote table contents can be cached in the NAV db, and that neighbor identification processing is always run at the end of the LLDP plugin, regardless of whether a cached table was available or a new table was retrieved.
=> Implement LLDP remote table caching and processing

python/nav/ipdevpoll/plugins/cdp.py
This mirrors #2192 and also fixes #2106 (the CDP part).
This ensures the CDP cache table contents can be cached in the NAV db, and that neighbor identification processing is always run at the end of the CDP plugin, regardless of whether a cached table was available or a new table was retrieved.
This depends on #2192, and will therefore stay in draft mode until #2192 is merged.
=> Implement CDP neighbor table caching and processing

Dockerfile, doc/howto/generic-install-from-source.rst, doc/howto/manual-install-on-debian.rst, python/nav/models/manage.py, python/nav/napalm.py, python/nav/web/seeddb/page/management_profile/forms.py, python/nav/web/seeddb/page/netbox/edit.py, requirements/base.txt, setup.py, tests/docker/Dockerfile, tox.ini
This implements [NAPALM](https://napalm.readthedocs.io/) as a new type of available management protocol in NAV.
NAPALM provides us with management connectivity on multiple vendor platforms where the SNMP operations we need are not available.
Initially, we need management of ports on Juniper switches in PortAdmin. Much of what we need here can be implemented by using Juniper's PyEZ library directly, and many of the operations we need are not actually available in the standard NAPALM API - however, we plan to improve our support for other platforms than JunOS in the future, so we might as well go for NAPALM.
Several of NAPALM's drivers, including the one for JunOS, will use NETCONF under the hood - so the connectivity details we need for NETCONF access are about the same as those put into …
=> Implement NAPALM management profiles and connectivity

python/nav/mibs/entity_sensor_mib.py
It seems Arista switches do not supply any values for the `entPhysicalName` column. NAV uses this column's value as a unique identifer for sensors, and any sensor entity missing this value will be ignored. Thus, all sensors on Arista switches will be ignored by ipdevpoll collection.
This workaround uses the `entPhysicalDescr` value as a fallback if there is no entity name. However: 
* The workaround is always applied
* `entPhysicalDescr` is less likely than `entPhysicalName` to be a unique value on a device.
This PR is provided mainly as a workaround to those affected, but if found useful and not damaging to operation on other vendor's devices, it should be merged into NAV.
=> Work around lack of entity names when collecting sensors from Arista devices

python/nav/ipdevpoll/plugins/psuwatch.py
Fixes #2139 
An event's varmap is stored as multiple rows in an auxiliary table, and if `event.save()` isn't run inside a transaction, the complete event details may not have hit the database when eventengine reads the event queue.
The event engine does not have a specific plugin for `psuState` or `fanState` events, and is entirely dependent on the `alerttype` variable in the event's varmap to pick the correct alert type and matching alert message template.
Instrumenting the varmap saving code with a `time.sleep(1)` between each variable saved quickly revealed the problem and made it reproducible.
This PR ensures everything takes place inside a transaction.
=> Save psu/fanState events in transactions

python/nav/statemon/checker/MysqlChecker.py
The MysqlChecker reads and writes low-level network binary packets to MySQL, but assumed everything could be done with regular strings - because that's the Python 2 way.
This updates the code to be more or less compatible with both Python 2 and 3 (I hope!)
Fixes #2190
=> Make servicemon MysqlChecker Python 3 compatible

python/nav/web/ipdevinfo/views.py
The documentation [mentions how to add custom information to ipdevinfo's "What if" tab](https://nav.uninett.no/doc/5.0/hacking/web-interface-customization.html#adding-custom-information-to-the-ipdevinfo-what-if-tab), however the provided example will not work, because the `netbox` variable is never passed into the template.
This PR fixes that problem.
=> Netbox reference is not passed to customization template for the ipdevinfo "What if" tab

NOTES.rst, requirements.txt, requirements/base.txt, requirements/django111.txt, requirements/django20.txt, requirements/django21.txt, tox.ini
The master branch still targeted all the old requirements of NAV 5.0 - these needed an update to be inline with our goals for the 5.1 release and beyond. 
Mainly, this is about dropping support for Python 2 and moving on to newer Django versions (Django 2.2 LTS this time around, some Django 3 version later).
=> Cleanup and update requirements for upcoming NAV 5.1

python/nav/web/netmap/views.py, tests/functional/netmap_test.py
The Netmap index page outputs a Javascript snippet with config variables for the Netmap JS application. Part of this configuration dictionary contains JSON-serialized data from the NAV backend, but in NAV 5.1 the serialized string has become broken, i.e. invalid JSON.
Apparently, the backend serializer used comes from Django Rest Framework, and now outputs bytes rather than strings. bytes objects are rendered by the Django template as a `repr()` of the object, which is NOT valid JSON (i.e. prefixed with a `b'`, etc.).
The data structure is not complicated, so this PR just switches to use Python's built in json serializer.
Fixes #2221.
=> Fix broken JSON output from Netmap index page

python/nav/eventengine/alerts.py
Export to an external script should be considered secondary, and any errors should not have an impact of the further internal processing of  the event.
Fixes #2225
=> Ignore export errors in eventengine

python/nav/eventengine/alerts.py
Because:
- If, for some reason, an AlertQueue or AlertHistory object already has a message that matches the uniqueness criteria of the one we are trying to post, then we should not hard fail, but optionally edit the existing message (though this code does not change existing messages).
- Hard fails are bad during event processing, as you might get into a situation where an alert is never closed.
This situation would normally never happen, as processing of each event in the queue will run fully inside a transaction, for example preventing the end messages from being persisted to the database if updating the end_time of the alerthist entry fails. Yet, this seems to have happened on at least one customer install - so this attemps to take precautions against that situation occurring again. …
=> Edit existing alert messages in case of dupes

python/nav/models/manage.py, python/nav/models/sql/changes/sc.05.01.0001.sql
Because:
- RFC 6793 extends the BGP protocol to allow for 4-byte (unsigned) AS numbers, as opposed to the old 2-byte numbers.
- The BGP peering session table in PostgreSQL uses INT data types to store the AS numbers, but these are signed, and will therefore only allow a maximum AS of 2,147,483,647, not 4,294,967,295 as the new standard specifies.
Fixes #2216
=> Allow big AS numbers in BGP peering sessions

python/nav/web/api/v1/alert_serializers.py
**Describe the bug**
Enabling an export script in `eventengine.conf` (as one would do to export alerts to Argus) causes the eventengine to sometimes fail to process alerts due to a serialization error.
Apparently, Django 2.2 changes the behavior of `QuerySet.values_list()`, so that it no longer returns a `list`, but a `ValuesListQuerySet` object. NAV's serializer definitions for alerts uses a call to `values_list` to generate a list of Device Groups that a device is a member of. If the result is an empty QuerySet, everything is just peachy. If, however, the alert comes from a device that is a member of any device group, `json.dumps` will be asked to dump a `ValuesListQuerySet` instead of a `None` value, which it can't, and a `TypeError` is raised.
**To Reproduce**
Steps to reproduce the …
=> [BUG] EventEngine alert export crashes on any alert from a device that is a member of a device group

python/nav/statemon/checker/HttpChecker.py
- base64 is no longer supported among the regular codecs of Python 3, causing the HttpChecker to crash if any attempt is made to configure an http service monitor with a username/password combo.
Fixes #2200
(thanks to @olemb for the debug info)
=>  Fix broken base64 encoding usage in HttpChecker

python/nav/mibs/hp_httpmanageable_mib.py, python/nav/mibs/juniper_mib.py, python/nav/mibs/powernet_mib.py
Due to the shift to Python 3, lots of collected serial numbers would now appear as `b'actual-serial-number'` in NAV, particularly for Juniper device, APC PDUs and older HP switches.
Table-based MIB object retrieval will compensate for this by recognizing retrieved columns that have a syntax equivalent to `DisplayString`, converting these bytestrings on the fly to Python strings.
However, the methods used to retrieve serial numbers for these devices/vendors used a more low-level SNMP call, which is not imbued with MIB object syntax knowledge, and hence did not attempt to translate the result values to actual strings.
=> Fix broken serial numbers for Juniper, APC PowerNet and old HP devices

python/nav/web/static/js/src/plugins/rickshaw-utils.js
A user who was recording error ratios in the nano-scale complained that the Rickshaw-based sensor graphs in NAV consistently showed any non-zero values as "0.00 µ"  (in the popup that appears when hovering above the graph line in these graphs).
It turns out, the number formatting code used in the popup does not support any scale below micro numbers. Additionally, it turned out it didn't support formatting negative numbers at all, which we also have in some sensors.
This PR fixes both issues (supporting formatting down to the pico scale, but no further until we have a practical use case)
The logic could also probably use some cleaning up, but I don't want to spend more time with Javascript than strictly necessary ;-)
=> Fix formatting of small and negative numbers in Rickshaw graphs

python/nav/mibs/coriant_groove_mib.py
Our NOC reports issues with creating generic threshold alert rules on DOM values from Coriant Groove devices: 
Unused ports are administratively disabled, but the Groove devices still report DOM sensor values for them. These values are usually non-sensical (like `-99dBm`) and tend to cause the threshold rules to alert on things that aren't errors.
They requested that NAV only registers sensors for ports that are administratively up.
=> Exclude Coriant Groove port sensors from collection based on portAdminStatus

python/nav/models/manage.py, python/nav/web/devicehistory/views.py, python/nav/web/quickselect.py, tests/integration/models/netbox_test.py
The (ancient) QuickSelect component will by default populate itself with a list of all netboxes in the database upon initialization. It also tries to annotate each of these netbox records with a device serial number.
However, due to schema changes that took place years ago by now, this leads to N(netbox) auxiliary queries against the NetboxEntity and Device models, which can become horribly inefficient as N grows.
This PR implements serial number annotations as a new method in the `NetboxQuerySet` manager, and makes QuickSelect use this new method. This should alleviate some of the performance issues described in #2251
It seems I'm too lazy to figure out how to accomplish this using pure Django ORM acrobatics, so this is implemented partially using raw SQL, so tests are included to ensure …
=> Drastically improve page load times on maintenance edit form

python/nav/web/navlets/ups.py
Fixes #2159.
The HTML/frontend is only told the metric name to fetch from Graphite, and what the sensor unit is, so makes the backend fill the template with a Graphite scale function.
=> Scale second values to minutes in UPS widget

python/nav/ipdevpoll/plugins/poe.py, python/nav/models/manage.py
- Vendor names can be changed by users in SeedDB.
- The correct way to identify a vendor for SNMP purposes is to use the enterprise ID as derived from the sysObjectID.
Fixes #2264
=> Use enterprise IDs to identify Cisco equipment

python/nav/etc/ipdevpoll.conf, python/nav/ipdevpoll/__init__.py, python/nav/ipdevpoll/config.py, python/nav/ipdevpoll/plugins/interfaces.py, tests/unittests/ipdevpoll/interfaces_test.py
This closes #2240 by
- Refactoring the `ifSpeed`/`ifHighSpeed` logic to a unit-testable function
- Implementing tests
- Working around vendor issues by using `ifHighSpeed` if `ifSpeed=ifHighSpeed`.
=> Work around buggy ifSpeed/ifHighSpeed implementations in IF-MIB

tools/docker/graphite/Dockerfile
Because:
- The Graphite image used for the docker-compose based development environment would no longer build from scratch.
- The problem seems to be that the image still ran on Python 2 on Debian Stretch, but some of Graphite's Python dependencies would no longer run on Python 2.
This re-uses the basic OS setup from the top-level Dockerfile used for NAV.
=> Update Graphite docker container to Debian Buster

python/nav/portadmin/snmp/base.py, python/nav/portadmin/snmp/cisco.py, python/nav/portadmin/snmp/dell.py, python/nav/portadmin/snmp/h3c.py, python/nav/portadmin/snmp/hp.py
Handling of various SNMP errors that can occur is pretty broken in many places in PortAdmin, up to NAV 5.1.3.
Requests against SNMP agents may time out, agents may not accept specific configuration values in some running modes, and so forth. Most of the `SNMPHandler` classes in PortAdmin will not handle these errors, letting them bleed through to the PortAdmin API views. Even worse, the Cisco SNMP handler seems to log and ignore many SNMPErrors, which results in success reports to the end user, even in the face of total failure.
The API views, however, are only equipped to give proper JSON error responses for "official" PortAdmin exception classes. Most of the `SNMPError`s would fall in to the `ProtocolError`. Anything outside the expected will bleed through to the Django 500 handler …
=> PortAdmin SNMP error handling is broken in several ways

python/nav/web/templates/portadmin/portlist.html
This ensures the form checkbox to shutdown or enable an interface in PortAdmin
is *disabled* when the interface is mark as non-editable, just as all the other form components in that row are.
**Because:**
- When an interface was non-editable, the UI would still allow the user to check/uncheck the "Enable" checkbox, and thus marking the interface row as a config change to be committed. Yet, since the interface is non-editable, there was no Save-button to actually commit the changes. This is only good for confusing users...
**Screenshot**
The checkbox is still checked, to show that the interface is in fact enabled, but can no longer be changed by the user, just as none of the attributes on that row can.
=> Disable the PortAdmin "Enable" checkbox for interfaces that aren't editable

doc/reference/portadmin.rst, python/nav/etc/portadmin/portadmin.conf, python/nav/portadmin/config.py, python/nav/web/portadmin/utils.py, python/nav/web/templates/portadmin/portlist.html
This was requested by SUNET.
There is already a config option to prevent trunk port editing, but not all uplinks are trunks - and sometimes you want to be able to edit trunks to client devices but still prevent messing about with uplinks.
=> Add config option to disallow editing of uplinks and downlinks in PortAdmin

tests/docker/Dockerfile, tests/docker/Makefile
This PR updates the Docker CI image (used for running the test suite locally and in Jenkins) to Ubuntu 20.04, which is currently the same as `ubuntu-latest` on GitHub Actions.
It depends on #2293, so I will take this out of draft mode once #2293 is merged.
=> Upgrade Docker CI image to Ubuntu 20.04

Makefile, doc/exts/alerttypes.py, doc/exts/alerttypes.rst.j2, doc/hacking/release-procedure.rst, doc/reference/alerttypes.rst, doc/reference/eventengine.rst, doc/reference/index.rst
The only complete "documentation" of NAV's event and alert type hierarchy exists in the SQL schema definitions (and [this once-generated Wiki page](https://nav.uninett.no/wiki/nav-ref:navref_230221:alerttypes?s[]=boxdownwarning) ).
This information needs to be out there in the Sphinx-based user documentation, as part of the reference material. The simplest way to get it there is to just generate this documentation source text as necessary, when the event and alert type hierarchy changes (which is a rare event).
This PR sets out to do that.
A more viable solution for the future might be to actually define the hierarchy as Python code and use that to both seed the initial SQL database *and* to generate documentation. Why? Because the generator introduced in this PR needs access to an …
=> Document the event and alert type hierarchy

python/nav/junos/nav_views.yml, python/nav/portadmin/napalm/juniper.py
Fixes #2298
- JunOS changed the name of the `get-ethernet-switching-interface-information` command to `get-ethernet-switching-details` in JunOS 20, although their output is exactly the same.
- The old command will crash with an RpcError if the switch is running on JunOS >= 20, and we still need to support older versions.
=> Support renamed RPC command on JunOS>=20

requirements/base.txt
ReadTheDocs seems to be unable to successfully install the feedparser dependency during doc builds. This PR tries to upgrade the dependency, to see if it still works for us and satisfies RTD as well.
The actual error in RTD is during the installation of the feedparser package:
>    error in feedparser setup command: use_2to3 is invalid.
=> Upgrade feedparser dependency

doc/conf.py, doc/reference/models-event.rst, doc/reference/models-manage.rst, requirements/base.txt
We've added several features that lets users configure hyperlinks, templates or severity values based on matching the values of various data model objects in NAV.
In order for users to be able to figure which models and attributes are available to use, and what they mean, *without* requiring them to read NAV's source code, we should use Sphinx' autodoc features to document these models.
This PR introduces the `sphinxcontrib-django` dependency, which improves the autodoc output of Django models, and adds autodoc reference sections for some of the central NAV models, so they can be  properly cross-referenced by other documentation sections.
=> Add Sphinx autodoc of central ORM models

python/nav/django/templatetags/info.py, python/nav/web/templates/ipdevinfo/frag-ipdevinfo.html
Closes #2274 by completely hiding attributes where key starts with double underscore.
=> Completely hide all attributes starting with "__"

python/nav/web/auth.py
Currently when we click on the login button we are met with the messages "You need to log in to access this resource" and " After successfully logging in, you will be redirected to: /"
These are useful if the user tries to access other parts of nav, but not when logging in normally. 
This will fix that and we will be shown a message-free login in screen.
=> Remove "no access" message from login page during normal login

python/nav/web/seeddb/page/location.py, python/nav/web/seeddb/page/netboxgroup.py, python/nav/web/seeddb/page/prefix.py, python/nav/web/seeddb/page/room.py, python/nav/web/seeddb/page/vlan.py, python/nav/web/seeddb/utils/edit.py, python/nav/web/templates/seeddb/edit.html
Resolves #2245 
Also changes the SeedDB edit page for prefixes to the same style as rooms, locations, etc..
=> Link SeeDB edit pages to detail views for locations, rooms, device groups, prefixes and vlans

NOTES.rst, requirements/base.txt
This fixes a recently arisen dependency conflict:
* NAV depends on napalm==3.0.1 and dnspython==1.15.0
* Napalm depends on ciscoconfparse (not sure which version, but it's maybe not properly version locked)
* ciscoconfparse depends on dnspython<3.0.0,>=2.1.0
Only the DnsChecker handler for servicemon seems to require dnspython, so it's time to see if we can live with a newer dnspython.
Manual testing seems to indicate it works as before (there is no advance usage of the library).
=> Upgrade to dnspython 2.1

bin/smsd.py, python/nav/alertengine/base.py, python/nav/auditlog/models.py, python/nav/auditlog/utils.py, python/nav/compatibility.py, python/nav/django/utils.py, python/nav/metrics/lookup.py, python/nav/mibs/cisco_process_mib.py, python/nav/mibs/itw_mib.py, python/nav/web/api/v1/alert_serializers.py, python/nav/web/api/v1/views.py, python/nav/web/ipdevinfo/host_information.py, python/nav/web/seeddb/utils/list.py, python/nav/web/useradmin/forms.py, tests/integration/api_test.py, tests/integration/web/alertprofiles_test.py, tests/integration/web/ipdevinfo_test.py
While the code currently runs on 2.2, it is not doing everything as 2.2 would prefer.
Merging this PR will improve code quality on 2.2 and prevent exceptions on 3.2.
A new module `nav.compatibility` is introduced, to do some conditional imports in a single location, similar to `six.moves`. When 2.2 is no longer supported this file can be removed after updating to the modern locations: `lru_cache` from `functools`, `force_str`/`smart_str` from `django.utils.encoding`.
=> Properly upgrade to Django 2.2

.github/workflows/build-and-test.yml
This adds the action to the main testing workflow, but it may still need some tweaking
=> Upload coverage reports to CodeCov

python/nav/smsd/gammudispatcher.py, tests/unittests/smsd/gammudispatcher_test.py
Playing with using CodeCov for the NAV repo, I picked a module with low test coverage, with the goal of increasing its test coverage. I picked GammuDispatcher, the smsd dispatcher plugin that can dispatch SMS messages using the Gammu library.
This PR:
* Rewrites the existing tests to become pure pytest tests.
* Adds more tests for the actual GammuDispatcher plugin code
* Removes the GammuDispatcher's obsolete dependency on `six`, since NAV code is now Python 3-only.
The tests were designed to run even when then gammu library isn't present, but since the mock library's patch framework doesn't work well when the code to patch doesn't exist, the test module needs to mock the bare minimum of the gammu library if it isn't present.
=> Increase test coverage for GammuDispatcher

.github/workflows/linter.yml, tox.ini
This adds GitHub superlinter to the GitHub actions workflow, mainly to verify that developers have actually installed the pre-commit hooks documented by the NAV hacker's guide: It validates all changed Python code using Black and Flake8.
=> Use GitHub superlinter to validate Python code using Black and Flake8

python/nav/django/settings.py
Fixes #2341 
logs a warning if something goes wrong while defining DATABASES.
Struggled a bit as the warning never showed up in the log when refreshing the site. I think my PHP experiences
have infected my brain, as I guess I assumed all code would be rerun for each refresh.
But the warning shows up when starting up (with docker-compose up) or after making changes to the code.
This is shown in the log during docker-compose up when I cause an error to happen.
Is this something along the lines of what is wanted?
=> log warning if DATABASES cannot be defined

NOTES.rst, README.rst, doc/conf.py, doc/hacking/hacking-with-pycharm.rst, doc/hacking/hacking.rst, doc/overview.rst, doc/reference/smsd.rst
This PR just updates the docs and release notes to reflect the name change from Uninett to Sikt, which we need for the next NAV release.
=> Document the name change from Uninett to Sikt

.github/workflows/build-and-test.yml, Dockerfile, NOTES.rst, bin/ipdevpolld, python/nav/ipdevpoll/epollreactor2.py, python/nav/ipdevpoll/jobs.py, python/nav/web/api/v1/views.py, requirements/base.txt, tests/docker/Dockerfile, tests/integration/conftest.py, tests/unittests/netmap/metadata_nx_test.py, tox.ini
It was apparent that NAV was not compatible with Python 3.9, which is the default Python version on our current target production platform of Debian 11 (Bullseye).
This PR sets out to:
* Enable testing on Python 3.9 in our CI matrix
* Fix any compatibility issues discovered by our test suite
* Update the Docker Compose-based development environment containers to run on Python 3.9.
The major showstopper appears to be the changed behavior of [select.epoll.unregister()](https://docs.python.org/dev/library/select.html#select.epoll.unregister) in Python 3.9. See [issue 39239 in the Python bug tracker](https://bugs.python.org/issue39239) for the rationale behind this change. This caused an incompatibility between `pynetsnmp-2`, Twisted and NAV that this PR resolves within NAV by introducing a …
=> Fix Python 3.9 compatibility

python/nav/web/netmap/graph.py
Newer Python versions issue a SyntaxWarning when this code is being run in the test suite. This code is old, and this logic is entirely broken, as suggested by the SyntaxWarning. Not exactly sure if or how this has affected production code, but it's been there for the last 8 years without raising any eyebrows :-P
=> Fix syntax warning (and likely broken logic)

python/nav/models/manage.py, python/nav/web/info/room/views.py
- Although RFC 3635 specifies that implementations MUST use `ifType=ethernetCsmacd(6)` for all ethernet-like interface types, many fielded implementations have incorrectly used other values that were never reserved by the IETF.
- D-Link is one such vendor, where interfaces would not be listed in the room interface list because of this.
Fixes #2280
Replaces #2283, which was accidentally closed beyond recovery when the old stable branch was removed
=> Include all ethernet interface types used in the wild in the room interface listing

python/nav/portadmin/napalm/juniper.py, tests/unittests/portadmin/napalm/juniper_test.py
This PR adds a wrapper function to translate an unhandled `RpcError` exception into a PortAdmin `ProtocolError`, and decorates all the config-changing methods of the Juniper Napalm/Netconf management handler with it.
A `ProtocolError` is handled  more gracefully by the interaction between backend and frontend, causing the UI to display a more friendly error to the end user.
Fixes #2362
The config-saving feedback dialog now looks like this:
The status of the changed row looks like this afterwards:
=> Wrap RpcErrors in PortAdmin ProtocolErrors, for more user-friendly error reporting

python/nav/util.py
=> Generate more secure API tokens

python/nav/ipdevpoll/plugins/statsystem.py, python/nav/mibs/juniper_mib.py
Closes #2359.
Name of memory entity is already being escaped by using the function ```metric_prefix_for_memory``` in ```StatSystem```.
=> Log memory usage on juniper devices

python/nav/mibs/spagent_mib.py, python/nav/smidumps/SPAGENT-MIB.py
Fixes #2107 
Updates AKCP MIB and reads from a different branch of the tree for SP2+.
Unsure if we previously supported anything other than the sensorProbe 8, so anything that is not a sensorprobe8 or SP2+ will attempt to use the sensorProbe8 tables.
=> Add support for AKCP SP2+

.github/workflows/build-and-test.yml
Forks will not have the necessary CodeCov token to upload coverage
results, causing this workflow to fail.
=> Restrict CodeCov uploads to Uninett upstream repos

doc/requirements.txt
As noticed in #2396 nav runs on django 3.2, but the docs use django 2.2.
This changes it so that #2396 works.
=> Migrate to django 3.2 for docs

python/nav/web/seeddb/page/vlan.py
Similar to https://github.com/Uninett/nav/pull/2384 in regards to https://github.com/Uninett/nav/issues/2156 this PR optimizes the vlan listing queries of SeedDB.
=> Optimize SeedDB vlan listing queries

python/nav/web/seeddb/page/room.py
Similar to #2384 in regards to #2156 this PR optimizes the room listing queries of SeedDB.
=> Optimize SeedDB room listing queries

requirements/base.txt
Closes #2381. 
The old version resulted it the warning
`DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working`
`from collections import Iterable`
Upgrading it to 3.4.1 fixes that and doesn't seem to influence anything else
=> Upgrade to napalm 3.4.1

python/nav/models/rack.py, tests/integration/models/rack_test.py
Since version 5.3.0, NAV has been unable to properly decode existing Rack item information from the database, due to changes in Django. This was only discovered this week by an internal NAV user who uses Rack definitions for environment monitoring of their server rooms.
The display configuration for a Rack is stored in the PostgreSQL database as a `JSONB` field. Older versions of Django would apparently allow such fields to be defined as text fields in the Django Model and then magically make them dicts when fetching from the database (but still requiring conversion magic during save).
This no longer works in Django 3 (introduced in NAV 5.3), where the text field is returned as a string, even when the underlying data is a JSONB field. The code tries to access the field as if it was a …
=> Fix broken deserialization of Rack data

python/nav/event2.py
Seems to be a bug. It previosuly set event.event_type in a place
where it (probably) should set event.state instead.
Found this by getting an error while trying
to create a stateless event. Seems this notify method is not
called anywhere, so makes sense it hasnt been found
=> Set stateless state in EventFactory notify

doc/reference/geomap.rst
Also fix a type and remove a possible issue that is fixed already.
=> Change dead links in Geomap documentation

python/nav/web/seeddb/utils/edit.py
As evidenced by #2410, SeedDB's `render_edit` (`nav.web.seedddb.utils.edit.render_edit`) was broken. The prefix edit page provides its own `form` value in the `extra_context`. However, `render_edit()` would override the contents of `extra_context` with its defaults.
This really needs to be the other way around, which this commit fixes.
Fixes #2410
=> Allow net_address GET argument to be filled in SeedDB's Prefix edit form

python/nav/models/manage.py
To supplement #2413 and #2414 this PR provided new methods that will return all related objects, which generally should only one objects. 
Since the data model allows multiple ones and it can't be guaranteed it also provides a method that return the preferred related object, which in this case is just the first of the related objects since we couldn't think of a more reasonable way to determine the preferred object.
It also introduces a method that returns an extended description, which is the string representation of the preferred object if it exists or the normal string representation of the device.
=> Add functions to get related objects and extended description

CHANGELOG.md, doc/faq/faq.rst, doc/index.rst
Mailing lists are moving from Sympa at uninett.no to Mailman at lister.sikt.no.
=> Update references to NAV mailing lists

python/nav/ipdevpoll/plugins/typeoid.py
This would run synchronously in the MainThread, which is a big no-no. It would block the entire MainThread while waiting for the ORM result from PostgreSQL, and also potentially attempt to use closed database connections withouth the connection re-establishment precautions that come with the database thread.
In short: MainThread is not designed to access the database at all!
Fixes #2478
=> Ensure NetboxType is loaded in a db thread

python/nav/snmptrapd/trap.py
=> Make snmptrapd able to identify trap agents that use a different IP to send traps than to receive SNMP queries

python/nav/portadmin/napalm/juniper.py, tests/unittests/portadmin/napalm/juniper_test.py
PortAdmin only cares about VLANs that can be identified through a proper 12-bit integer tag, so it should be safe to ignore ones that do not conform to the expected response from Juniper switches.
Fixes #2452
=> Ignore VLANs with non-numerical tags in Juniper NETCONF responses.

python/nav/models/manage.py, python/nav/web/api/v1/serializers.py, python/nav/web/api/v1/views.py, tests/integration/models/netbox_test.py
By request from the CNaaS core team at Sikt, the main chassis mac address (of which there may be more than one) must be made available through the `/netbox` API endpoint, so that IP Devices can be matched with inventory records from 3rd party systems (such as CMDBs).
This PR adds an extra Netbox attribute containing a unique set of  base/chassis addresses collected via `BRIDGE-MIB` or `LLDP-MIB`. 
MAC addresses of individual physical ports are not considered in this API, as these are available through the `/interfaces` endpoint.
=> Add list of chassis mac addresses to /netbox API endpoint

python/nav/web/api/v1/serializers.py
This attribute is not writeable, since it's a computed property of the Netbox model. Without these options, the API would require a client to include the mac_addresses field when posting new netboxes.
This just fixes #2487 - where three integration tests failed because of this, and still we didn't notice :-D
=> Make mac_address non-required and read-only

python/nav/web/static/js/geomap/GeomapPlugin.js
Function zoomToBounds() updates zoom correctly in accordance with the parameters it receives. This applies to several use cases, and specifically to a scenario when user requests a link to the current configuration.
Before, zoom value was ignored in view, but was present in the url, when user requested a link to current configuration. This commit makes zoomToBound() apply changes to zoom, when parameters are present. Parameters are present if the url with zoom, lon, lat values is present, ie when user requests link to current configuration.
Closes #2412
=>  Update zoom correctly when requesting link to this configuration

README.rst
Example target is a web client for libera.chat, but we could potentially go with a plain old irc scheme url (and potentially confuse the young folks ;) )
=> Add README badge for our IRC channel

python/nav/config.py
This should fix the annoying ResourceWarnings coming through during the test suite:
```
/source/python/nav/config.py:339: ResourceWarning: unclosed file <_io.TextIOWrapper name='/source/.tox/integration-py37-django32/etc/nav.conf' mode='r' encoding='utf-8'>
NAV_CONFIG = read_flat_config('nav.conf')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/source/python/nav/django/settings.py:36: ResourceWarning: unclosed file <_io.TextIOWrapper name='/source/.tox/integration-py37-django32/etc/webfront/webfront.conf' mode='r' encoding='utf-8'>
_webfront_config = getconfig('webfront/webfront.conf')
ResourceWarning: Enable tracemalloc to get the object allocation traceback
/source/python/nav/db/__init__.py:104: ResourceWarning: unclosed file <_io.TextIOWrapper …
```
=> Stop resource leakage when reading conf files

python/nav/etc/ipdevpoll.conf, python/nav/ipdevpoll/plugins/entity.py, python/nav/ipdevpoll/plugins/modules.py, python/nav/models/sql/changes/sc.05.05.0001.sql, tests/unittests/ipdevpoll/modules_test.py
This adds a config option to list device serial numbers that ipdevpoll should mostly ignore: I.e. it should not create modules for devices that have these serial numbers, and no Device entries either.
The default value of the serial number list is `BUILTIN`, which corresponds with the fake serial numbers lots of Juniper JunOS devices report. Making NAV Device entries out of these results in multiple Netboxes having modules and entities that point to the same Device entry, and they will compete against each other for updates to the Device entry's attributes.
This is a proposed hotfix that closes #2491
=> Ignore devices with fake serial number 'BUILTIN'

python/nav/smidumps/CISCO-ENHANCED-MEMPOOL-MIB.py
Not sure what when wrong with the first smidump, since it was full of broken OIDs.
This only contains the re-generated smidump file. This is intended for a patch release. Further work needs to be done to ensure this kind of thing is caught early next time.
Fixes #2494
=> Re-generate CISCO-ENHANCED-MEMPOOL-MIB.py

python/nav/snmptrapd/trap.py, tests/integration/snmptrapd_test.py
This:
1. Adds a regression test to detect the problem
2. Fixes the silly syntax problem
3. Rewrites the SQL statement to one that actually gives results (as the test revealed that the method did not return the expected result even when the syntax problem was fixed).
Fixes #2497
=> Fix broken SNMP trap agent lookup method

Dockerfile, tox.ini
The CI pipeline began failing three days ago, due some dependency changes in an upstream dependency.
It seems the pip-compile step of our tox environments became unable to resolve a full dependency graph from this point on (related to versions of pylint, it seems).
Using the backtracking resolver of pip-compile allows it to select older dependencies as long our pinned requirements are satisfied.
=> Use pip-compile's backtracking dependency resolver to fix failing CI pipelines

bin/naventity, bin/navoidverify, bin/navsnmp, python/nav/arnold.py, python/nav/models/manage.py, python/nav/portadmin/snmp/base.py, python/nav/web/portadmin/views.py, tests/unittests/arnold/arnold_snmp_test.py, tests/unittests/portadmin/portadmin_test.py
Fixes #2389.
Introduces a new function `get_preferred_snmp_management_profile` that return the profile with the highest snmp version, which then can be used to get the profiles snmp version or community.
Also replaces the occurrences of `netbox.read_only`, `netbox.read_write` and `netbox.snmp_version` using the new function everywhere expect in ipdevpoll. In ipdevpoll it is not clear yet how to do that since shadow classes are used there, which only copy the attributes, but not functions.
=> Fix scripts so they no longer use Netbox.snmp_version

.github/workflows/build-and-test.yml
It seems the upstream `ubuntu-latest` action runner was updated by GitHub 4 days ago. The latest ubuntu is now 22.04, which features libsnmp40 rather than libsnmp35.
=> Update libsnmp dependency for newer ubuntu

tests/integration/smidump_test.py
Adds a parametrized test to verify that every OID in every smidumped MIB module (from the `nav.smidumps` namespace) is encodeable by NET-SNMP
Fixes #2501
=> Add test for smidump modules OID validity

.github/workflows/build-and-test.yml, tests/requirements.txt, tox.ini
Several changes in upstream dependencies caused our test suite to break down over X-mas vacation, making the first workday of 2023 a pain.
This resolves multiple of these issues and cleans up a few things along the way.
Since these problems will also affect the current stable branch, this PR is against the stable branch, which should be merged to master as soon as the PR is approved.
Tox 4 breaks compatibility with several bits of our tox.ini (and they must have had a lot of problems with this release, they've had 23 new releases in the month that has passed since the release of 4.0.0): https://pypi.org/project/tox/#history
Primarily, this bites us hard, in a non-compatible way: https://github.com/tox-dev/tox/issues/2635
Also, the `passenv` option seems to require comma-separated …
=> Fix a slew of new CI pipeline / test suite problems that appear after new years

tox.ini
When running various local tests I noticed that pylint doesn't run due to conflicting dependencies. 
Using Django 3.2 instead of Django 2.2 fixes that problem.
=> Use Django 3.2 for pylint

python/nav/ipdevpoll/shadows/__init__.py
As mentioned by @lunkwill42 in https://github.com/Uninett/nav/pull/2515#discussion_r1062402937 the new version for a sw/hw/fw upgrade should also be saved in the event varmap in the same place as the old version.
=> Copy new version to event varmap on sw/hw/fw upgrade

python/nav/models/images.py, python/nav/models/logger.py, python/nav/models/msgmaint.py, python/nav/web/info/images/utils.py, python/nav/web/info/location/views.py, python/nav/web/info/room/views.py, python/nav/web/maintenance/views.py, python/nav/web/templates/info/images/upload.html
This is the third part of splitting up https://github.com/Uninett/nav/pull/2423.
=>  Add related names to django models (images, logger, msgmaint)

python/nav/web/api/v1/serializers.py, python/nav/web/api/v1/urls.py, python/nav/web/api/v1/views.py
Fixes #2517 
Adds endpoint /api/module/ that gives information about modules.
This PR updates the ModuleSerializer to include more information: 
- Includes the related Device object
- sysname for the related netbox
This will cause other endpoints that use ModuleSerializer to include this information as well (only one I could find is the interface endpoint). I figured this might be a good thing for consistencies sake, but if its better that only the module endpoint has this extra information then I will make it so.
Example of how the module endpoint looks like:
```
curl  -s -H "Authorization: Token $TOKEN"  localhost:8080/api/module/10/ | jq
{
"id": 10,
"object_url": "/ipdevinfo/teknobyen-5etg-sw1.uninett.no/module=I/",
"sysname": "teknobyen-5etg-sw1.uninett.no",
"device": {
"id": 15, …
```
=> Module endpoint

bin/start_arnold.py, bin/t1000.py, python/nav/models/api.py, python/nav/models/arnold.py, python/nav/web/arnold/views.py, python/nav/web/ipdevinfo/views.py, python/nav/web/portadmin/utils.py, python/nav/web/templates/arnold/details.html
This is the first part of splitting up #2423.
=> Add related names to django models (api, arnold)

python/nav/models/cabling.py, python/nav/models/event.py, python/nav/models/manage.py, python/nav/models/service.py, python/nav/web/ipdevinfo/views.py
This is the second part of splitting up https://github.com/Uninett/nav/pull/2423.
=>  Add related names to django models (cabling, event)

doc/reference/alerttypes.rst, python/nav/etc/alertmsg/deviceState/deviceNewChassis-email.txt, python/nav/etc/alertmsg/deviceState/deviceNewChassis-sms.txt, python/nav/etc/alertmsg/deviceState/deviceNewFan-email.txt, python/nav/etc/alertmsg/deviceState/deviceNewFan-sms.txt, python/nav/etc/alertmsg/deviceState/deviceNewModule-email.txt, python/nav/etc/alertmsg/deviceState/deviceNewModule-sms.txt, python/nav/etc/alertmsg/deviceState/deviceNewPsu-email.txt, python/nav/etc/alertmsg/deviceState/deviceNewPsu-sms.txt, python/nav/ipdevpoll/shadows/__init__.py, python/nav/ipdevpoll/shadows/entity.py, python/nav/models/manage.py, python/nav/models/sql/changes/sc.05.04.0003.sql
Fixes #2391 
Creates alerts when discovering new devices. The alert type depends on what type of device it is, e.g. chassis, module etc.
Also fixes a small bug in EventFactory.
=> Create event when new device is discovered

python/nav/eventengine/plugins/upgrade.py, tests/integration/eventengine/upgrade_test.py
The plugin copies the variables `old_version` and `new_version` (if exists) to alert history to use in reports (#2466)
I decided to not just do it for software upgrades, but also firmware and hardware in case we also want to create reports for that.
Also fixes #2533 as a side effect.
=> Implement an sw/hw/fw upgrade event handler plugin

requirements/base.txt, tests/integration/web/info_test.py
Vulnerabilities have been reported in the version we're locked to. Pillow has never introduced backwards incompatibilities in the small part of the library we use, so this removes the upper bound and introduces a regression test for the small functionality used.
=> Remove upper version bound for Pillow to fix security warnings

python/nav/web/ldapauth.py, tests/unittests/web/ldapauth_test.py
Following referrals is disabled, to work around the error caused by Active Directory's referrals to other servers.  #1166
I don't have another LDAP authentication source to test whether it breaks non-AD LDAP integration.
=> Update ldapauth.py to disable following referrals, to fix Active Directory login failures

python/nav/etc/alertmsg/deviceNotice/deviceFwUpgrade-email.txt, python/nav/etc/alertmsg/deviceNotice/deviceFwUpgrade-sms.txt, python/nav/etc/alertmsg/deviceNotice/deviceHwUpgrade-email.txt, python/nav/etc/alertmsg/deviceNotice/deviceHwUpgrade-sms.txt, python/nav/etc/alertmsg/deviceNotice/deviceSwUpgrade-email.txt, python/nav/etc/alertmsg/deviceNotice/deviceSwUpgrade-sms.txt
One thing I forgot since we added the variable `new_version` to the varmap in #2545 was to also use that in the alert message templates.
=> Use new_version in alert message templates

tests/docker/Dockerfile, tox.ini
Running pip-compile and pip-sync on every tox run is quite expensive, and reduces the incentive for developers to repeatedly run tests locally.
This brings us back to the inconvenience in the other end of the scale: If you change any of the requirements files, tox (`<4`) will not recognize this as a change, and the test environment is not updated. The developer who needs an updated test environment must endure a manual environment rebuild using `tox --recreate -e <env-of-choice>`
The GitHub workflows will cache the tox environments between runs. However, no changes should be necessary here, as checksums of all the requirements files are part of the cache key.
This PR also updates the test environment Dockerfile to explicitly install `tox < 4`, just as we do in the GitHub workflows (as tox …
=> Revert to having tox run its own dependency installer

python/nav/eventengine/plugins/linkstate.py, python/nav/models/manage.py, python/nav/models/profiles.py, python/nav/portadmin/napalm/juniper.py, python/nav/portadmin/snmp/base.py, python/nav/topology/detector.py, python/nav/topology/vlan.py, python/nav/web/ipdevinfo/utils.py, python/nav/web/networkexplorer/mixins.py, python/nav/web/networkexplorer/search.py, python/nav/web/portadmin/views.py
This is the ninth part of splitting up https://github.com/Uninett/nav/pull/2423.
=> Add related names to django models (manage - Switch/topology)

python/nav/web/devicehistory/views.py, tests/integration/web/devicehistory_test.py
=> Fix registering device error with empty comment

CHANGELOG.md, python/nav/models/event.py, tools/eventgenerators/devicenotice.py
After merging #2413 and everything related to it (#2515, #2545, #2560, #2565, #2580) it happened occasionally that notifications were sent out with the error
```
no templates defined for <AlertGenerator: source=<Subsystem: ipdevpoll> device=<Device: redacted> netbox=None subid='' time=datetime.datetime(2023, 3, 17, 9, 41, 24, 79802) event_type=<EventType: deviceNotice> state='x' value=100 severity=3 history_vars={} alert_type=None varmap={}>, sending generic alert message
```
We could pinpoint that this happened due to the eventengine being notified about a new event in the EventQueue and processing it without the varmap being saved yet, which lead to this error, since the alert type is saved in the varmap.
Making the save function atomic prevents this from happening since the eventengine …
=> Make save function of Alert/EventQueue and AlertHistory atomic

doc/howto/api_parameters.rst, python/nav/web/api/v1/serializers.py, python/nav/web/api/v1/views.py, tests/integration/web/prefixviewset_test.py
Fixes #2577 
- Adds a filter `contains_address` to the `Prefix` endpoint. The endpoint takes a CIDR address, and returns the prefixes that contains the given address.
- Updates the Prefix serializer to include `Vlan` information inline under the key `vlan_data`. the key `vlan` that contains the `Vlan` id is still included for backwards compatability
=> Add endpoint for finding prefixes containing given CIDR address

python/nav/web/sortedstats/views.py, python/nav/web/templates/sortedstats/sortedstats.html, tests/unittests/web/sortedstats/sortedstats_test.py
Fixes #2561 
Error from cache not being configured should not be handled. When trying to get data from cache, it will now behave as if the cache is empty. When trying to write, it will now just skip the writing step instead of crashing.
An error message will be displayed on the ranked statistics page as well.
=> Add errorhandling for missing cache in ranked statistics

docker-compose.snmp.yml, docker-compose.yml, tools/forward/Dockerfile
As mentioned in #2435, there already existed some undocumented examples of how to achieve SNMP proxying in the Docker Compose based development environment.
Since I recently had the need to use SNMP proxying to reach a closed-off network, I found an opportunity to clean up the examples.
This complements #2435 - and perhaps #2435 can be updated to mention these examples.
=> Update SNMP forwarding/proxying examples in docker-compose environment

tests/unittests/ipdevpoll/pool_test.py
Explicit coverage of the worker ping and euthanization methods did not exist.  Instead, these methods would "accidentally" receive coverage in some test runs, and not at all in others.  This would cause coverage stats to flip back and forth, and codecov.io would fail seemingly random PRs for decreasing coverage of these methods.
Fixes #2548
=> Add unit tests for ipdevpoll worker euthanization

python/nav/eventengine/alerts.py
This was introduced by 16536ab4ba9de4d122ea0045fb8329c304fd6cda . It hasn't been needed since NAV dropped support for Python 2.
=> Drop obsolete Python 2 compatibility statement

python/nav/config.py
Detection of current active virtualenv (used during detection of where NAV's config files may be located) broke down horribly during a bit of reorganization of how the tests are run, and under which versions of virtualenv they run.
See https://stackoverflow.com/a/1883251 for details on why this needs to change.
=> Detect current virtualenv in a more compatible way

.github/workflows/build-and-test.yml
The installed dependencies in tox environments are no longer automatically synced using pip-tools, which means they do not update if they are stale.
We should therefore never use prefix matching for the cache Action for the tox environments, or we will end up restoring a stale environment every time the requirements files change.
This ensures we only restore tox environments when the cache key matches exactly - meaning that all the tox environments should be rebuilt if any of the requirements files changed.
=> Never restore stale tox environment caches in GitHub workflows

CHANGELOG.md, bin/nav, tests/integration/bin_test.py
=> Show help text when running nav command without arguments

CHANGELOG.md, python/nav/web/info/netboxgroup/views.py
When writing a test for the bug that will be fixed in #2595 I also realized that something similar happened in device group search. This PR fixes that.
=> Fix backwards relation references in group search

CHANGELOG.md, python/nav/web/seeddb/forms/__init__.py, tests/integration/web/netboxtype_test.py
=> Validate and clean sysobjectid in NetboxTypeForm

python/nav/web/api/v1/views.py
When adding related names to the models this was overlooked. To reproduce the bug visit `api/1/cabling/?available=1`.
=> Fix related name in cabling search in api

.github/workflows/build-and-test.yml, tests/docker/Dockerfile, tests/requirements.txt
A couple of the libraries we utilize as part of our test suite have seen their dependencies be released in new versions that are no longer compatible.
This PR locks those indirect dependencies to versions that are know to work for us.
Fixes #2617
=> Version lock indirect dependencies of our test suites

python/nav/bootstrap.py
Closes #2168
Explains why it is needed in the first place.
=> Add a docstring to "bootstrap_django"

python/nav/web/info/room/views.py, python/nav/web/templates/info/room/base.html
17ef4e0 broke things by adding a related name that was used otherwise (netboxes) and me changing `location` to `child_locations`, where it was actually incorrect, which resulted in the room search not working. 
Luckily I caught this before it was included in a release.
=> Fix backwards relation references in room search

tools/docker/web.sh
The development web container doesn't work properly if `DJANGO_DEBUG=False` is set in `nav.conf`, since the staticfiles app would not serve most static resources in that case.  This would prevent us from seeing what a non-debug site looks like while developing.
=> Run development web server in insecure mode

CHANGELOG.md, tests/integration/web/search_test.py
As mentioned before in #2595 adding related names broke something in the room search. This PR adds tests for the different searches. As a nice side effect I also discovered a bug that was fixed in #2596.
=> Add simple tests for search

doc/hacking/snmp-tunnels.rst, tools/forward/Dockerfile, tools/forward/snmp_forward.sh
The SNMP forwarder container setup had three main drawbacks that this PR aims to fix:
1. The remote `socat` process on the hop-host was never terminated, keeping the forwarding port bound indefinitely, causing every subsequent attempt to start the forwarding container to fail with "address already in use" errors.
2. The forwarding container would never exit if there was a problem with setting up the tunnels - it would at best log the errors and keep running forever.  Exiting is the best way to signal a real problem.
3. The forwarding container did not support forwarding SNMP requests to agents on IPv6 addresses.
Docs are also slighty updated to clarify on *what* host the problem resides when the "address already in use" error appears.
=> Various improvements to the SNMP forwarding/proxying container setup

tests/integration/web/crawler_test.py
The web crawler would generate HTML validation tests for all reachable pages, and marked them as *skipped* if the page is blacklisted or the retrieved page has a content-type that doesn't appear to be HTML-related.
Skipped tests should be an indicator of some unusual situation or missing condition that prevents the test from running.  However, non-HTML pages can never be validated as such, and the *normal* situation is that these tests are useless.  Since a lot of the crawled content isn't actually HTML, a large number of SKIP results is produced in test reports.  These results only serve to hide the results of tests that were skipped for *factually* unexpected or extraordinary reasons.
This change will filter crawled pages based on blacklist status and content-type before the result is …
=> Stop making validation tests for non HTML content

python/nav/ipdevpoll/daemon.py, python/nav/ipdevpoll/db.py
In working on #1073, some needs for improved logging in ipdevpoll appeared.  These were extracted as a separate PR to make for a smaller review :)
=> Improve ipdevpoll logging of SQL queries and from Twisted library

python/nav/asyncdns.py, tests/unittests/asyncdns_test.py
=> Ignore case in DNS forwards lookup results

python/nav/web/api/v1/views.py, tests/integration/api_test.py
Without this fix the API throws an error when filtering on invalid IPs.
To replicate access the url `/api/netbox/?ip=10`:
```
DataError at /api/1/netbox/
invalid input syntax for type inet: "10"
LINE 1: ... AS "__count" FROM "netbox" WHERE "netbox"."ip" = '10'::inet
```
=> Filter by ip manually instead of using django in netbox api

python/nav/models/profiles.py
One log entry is created for each alert every 30 seconds. The debug level is changed to debug since no new error is discovered, since we already have set the address type to blacklisted.
Closes #1787.
=> Log refusing to send alerts to addresses of blacklisted types as debug instead of warning

python/nav/napalm.py
=> Use default if timeout in napalm profile is None

doc/howto/setting-up-logging.rst, doc/index.rst
The NAV docs did not contain extensive information about controlling log output, only a few references to it here and there.  This adds a howto guide for controlling log output (though most users will never touch this).
=> Write missing howto for log configuration

python/nav/alertengine/dispatchers/slack_dispatcher.py, python/nav/web/alertprofiles/forms.py, tests/integration/web/alertprofiles_test.py
Just one of the many incoming alert engine tasks sparked by #1787.
=> Validate slack address in alert addresses

tests/unittests/portadmin/portadmin_test.py
Portadmin tests need a revamp. Had issues writing new tests in #2635 because of how these tests are written. 
This PR swaps from using unittest and setup/teardown to using fixtures, groups tests together better and fixes some other bad practices (importing all from a module using * for example)
=> Update portadmin tests to use fixtures

python/nav/eventengine/__init__.py, python/nav/eventengine/plugins/juniperalertcount.py, tests/integration/eventengine/boxdown_test.py, tests/integration/eventengine/juniper_alert_count_test.py
=> Add eventengine plugin for juniper alert count

python/nav/portadmin/handlers.py
For #1938.
Adds empty functions to ManagementHandler that should be implemented by vendor specific handlers in different ways. Different
vendors support different PoE states, so `get_poe_state_options` should return all available options. These options should then be displayed in PortAdmin and be selectable.
=> Add abstract functions for PoE enabling

tests/integration/web/alertprofiles_test.py
Adding to the tests added in #2657 this adds the same type of tests for email and sms. 
If we decide to go ahead with #2662 these can be expanded to test for numbers that are not valid phone numbers.
=> Add tests for validation of sms and email

python/nav/alertengine/dispatchers/__init__.py, python/nav/models/profiles.py, tests/integration/alertengine_test.py, tests/integration/models/alert_test.py
When we try to send an alert, but the alert address is empty currently no alert is sent, an error is logged, but it is reported back as a successful sending, which can become very confusing. 
This PR fixes that and even widens the application. Before sending an alert the address it is to be sent to is validated and in case it is invalid an error is logged and an `InvalidAlertAddressError` is thrown. That is caught further up and the alert is deleted in that case and the sending is reported back as failed.
This popped up due to #1787.
=> Handle invalid alert address in alert sending

Dockerfile, Makefile, pyproject.toml, setup.py, tools/docker/build.sh, tools/docker/doc-watch.sh, tox.ini
First steps in modernizing how nav is built and packaged.
=> Modernize nav packaging

doc/howto/setting-up-logging.rst, python/nav/logs.py, tests/unittests/logs_test.py
This adds the ability to override most of NAV's logging config with the more flexible dictConfig format, as read from an optional `logging.yml` file (which can also be overriden by environment variable, just like `logging.conf`)
This could be used to customize NAV logging in your deployment to a much larger degree. It should also be possible to have NAV keep logging to its normal log files by configuring a default StreamHandler, as most NAV daemons will redirect stderr to its log file on daemonization.
=> Read logging config from logging.yml if available

python/nav/web/templates/alertprofiles/address_list.html, python/nav/web/templates/alertprofiles/subscription_form.html, python/nav/web/templates/alertprofiles/timeperiods.html
Closes #2653. 
I modeled it after how it is shown when an alert sender is no longer supported, but used the warning box instead of the error box.
(basically copied https://github.com/Uninett/nav/commit/8b2700c3c4c5a2371314e96f2148d313313d0870) 
Dependent on #2678.
=> Show blacklisted reason of alert address in alert profiles

python/nav/netmap/topology.py
=> Fix related names of NetmapView

python/nav/web/webfront/views.py, tests/integration/api_test.py, tests/integration/conftest.py, tests/integration/models/alert_test.py, tests/integration/seeddb_test.py, tests/integration/web/info_test.py, tests/integration/web/webfront_test.py
For some reason it happened that for multiple dashboards the `is_default` field is set to True, which leads to an error when trying to set a new dashboard as the default. This fixes that situation without doing anything about the underlying problem.
=> Prevent error when setting new default for multiple existing default dashboards

python/nav/alertengine/dispatchers/sms_dispatcher.py, tests/integration/web/alertprofiles_test.py
=> Add proper validation for phone numbers

python/nav/Snmp/defines.py, python/nav/Snmp/errors.py, python/nav/Snmp/pynetsnmp.py
This adds the necessary arguments, validation and a reworked command line builder for SNMPv3 communication to the synchronous SNMP implementation in `nav.Snmp.pynetsnmp.Snmp`.
Closes #2700
=> Add SNMPv3 support to `nav.Snmp.pynetsnmp` implementation

pyproject.toml, tox.ini
Discovered during #2716 
Closes #2714
=> Fix broken docs environment in tox.ini

docker-compose.snmp.yml, tools/snmpdv3/Dockerfile, tools/snmpdv3/README.md, tools/snmpdv3/snmpd.conf
As part of working on #2692, this adds useful examples to the developer tools directory and docker example files to run a local `snmpd` entity capable of responding to SNMPv3 requests while developing support for SNMPv3.
=> Add an snmpd service container for SNMPv3 comms

doc/contents.rst, doc/howto/index.rst
=> Collect links to all howtos in one place

python/nav/etc/webfront/webfront.conf, python/nav/web/auth/remote_user.py
Add a new flag to the remote user config that by default is off. If remote users is enabled and the new flag is toggled on, the username in REMOTE_USER will be used to automatically create a new user with that username. Automatic creation regardless used to be the default behavior.
Because the default behavior for remote users has changed this needs to be flagged well in NOTES.
Depends on #2706.
For https://github.com/Uninett/campus-tasks/issues/22
=> Add toggle for automatic creation of remote users

python/nav/models/manage.py, python/nav/web/seeddb/page/management_profile/forms.py, python/nav/web/templates/seeddb/management-profile/edit.html, tests/unittests/seeddb/management_profile_test.py
While there is already a profile type for SNMP with a v1/v2c protocol version choice, none of the other attributes of this profile are relevant for SNMPv3, and it hardly serves us to complicate these profiles with reams of attributes that don't belong in v1/v2c.
This therefore adds a new profile type for SNMPv3, with the corresponding definition in a SeedDB management profile form.
It also adds the option to add generic warning messages to protocol forms as a whole, so that the SNMPv3 protocol form can be marked as experimental/not-yet-fully-implemented-in-the-backend
Closes #2693
=> Add an SNMPv3 management profile type

python/nav/web/alertprofiles/views.py, tests/integration/web/alertprofiles_test.py
@ingeborgoh sent us a very helpful mail letting us know that it is not possible to deactivate alert profiles. 
This PR fixes that bug by avoiding deleting elements of a dictionary that is iterated over and also adds tests for that case.
=> Fix (de)activating alert profiles

python/nav/Snmp/defines.py, python/nav/Snmp/errors.py, python/nav/Snmp/pynetsnmp.py
This adds the necessary arguments, validation and a reworked command line builder for SNMPv3 communication to the synchronous SNMP implementation in `nav.Snmp.pynetsnmp.Snmp`.
Closes #2700 
This replaces #2703, which got "merged" due to an error, and cannot be reopened.
=>  Add SNMPv3 support to nav.Snmp.pynetsnmp implementation #2703 

python/nav/web/alertprofiles/views.py, tests/integration/web/alertprofiles_test.py
Another thing I overlooked in #2544...
=> Fix related name when deleting filter group in alert profiles

python/nav/portadmin/handlers.py, python/nav/portadmin/snmp/cisco.py, tests/unittests/portadmin/conftest.py, tests/unittests/portadmin/portadmin_poe_cisco_test.py, tests/unittests/portadmin/portadmin_test.py
Fixes #2632.
Adds backend for getting current PoE state for interfaces and changing the state.
=> Add support for configuring PoE for cisco equipment

bin/navoidverify
While working on SNMPv3 implementation for the async/ipdevpoll parts of NAV, I incidentally found the `navoidverify` command to be broken before I started.
For the same reasons as documented in `nav.ipdevpoll.epollreactor2`, `navoidverify` seems to have stopped working (at least on Linux), due to incompatibilites between the default epollreactor implementation and pynetsnmp.
This change installs NAV's epollreactor2 in Twisted before any of the twisted imports run and install the default reactor.  ipdevpoll does the same, but since this is an all-in-one script, this mucks about with code in between imports to ensure it runs before twisted, while a multi-module system like ipdevpoll can simply do it before calling the `main()` function. …
=> Fix broken navoidverify on Linux

bin/navsnmp
The navsnmp command needed to be able to output NET-SNMP command line parameters for SNMPv3 profiles too.  Slightly restructured the code, since outputting SNMPv3 arguments is slightly more complex that just outputting a community string :)
Closes #2724
=> Add SNMPv3 support to navsnmp command

python/nav/web/seeddb/page/netbox/edit.py, tools/snmpdv3/Dockerfile, tools/snmpdv3/README.md, tools/snmpdv3/snmpd.conf
This augments #2734 and closes #2727.
This includes reworking the snmpdv3 example container to allow for testing write operations.
=> Enable SNMPv3 write profile checks in SeedDB

python/nav/arnold.py, tests/unittests/arnold/arnold_snmp_test.py
=>  Add SNMPv3 support to Arnold

tests/integration/web/alertprofiles_test.py
Dependent on #2738. 
Open for other suggestions when it comes to making these tests clearer and neater.
=> Restructure alert profile tests

doc/index.rst
We enabled GitHub forums for NAV a while back.  They should be mentioned in the docs as a place to get help.
=> Add link to our GitHub discussion forums

python/nav/web/alertprofiles/forms.py, tests/integration/web/alertprofiles_test.py
This was caused by #2667. It changed how the values are saved (as `['AD']` for example instead of `'AD'`). This shows again, that we need even more tests for the alert profiles views.
Thanks to @runeki for finding this bug!
=> Fix form validation with equal and in operator for adding expression with group to filter

bin/naventity, bin/navoidverify
This gets the SNMP parameters for the AgentProxy constructor from the new library functions from ipdepvoll, ensuring compatibility with SNMPv3.
Closes #2747
=> Make `navoidverify` and `naventity` commands SNMPv3 compatible

python/nav/ipdevpoll/__init__.py, python/nav/ipdevpoll/dataloader.py, python/nav/ipdevpoll/jobs.py, python/nav/ipdevpoll/plugins/snmpcheck.py, python/nav/ipdevpoll/shadows/netbox.py, python/nav/ipdevpoll/snmp/common.py, python/nav/mibs/mibretriever.py, python/nav/models/manage.py, requirements/base.txt, tests/unittests/ipdevpoll/snmp/common_test.py
This adds SNMPv3 support to ipdevpoll and the asynchronous SNMP libraries of NAV.
Summary:
- Individual SNMP attributes were still stored directly on Netbox objects ("shadow" objects, not Django models).  The pre-existing `SNMPParameters` namedtuple was changed into a dataclass with all necessary parameters for establishing SNMP v1/v2c/v3 communication, and each `Netbox` object now has an `snmp_parameters` attribute attached to it (unless it has no SNMP profile, that is).
- SNMPv3-related bugs were found and fixed in the `pynetsnmp-2` library during the development of this PR.  This PR updates NAV's required version of this library as a result.
- Additionally, SNMPv3 communication may lead to another type of timeout error being raised in unexpected places, so the `SnmpTimeoutError` from …
=> Add initial SNMPv3 support to ipdevpoll

tests/integration/web/alertprofiles_test.py
Another improvement to the alert profiles tests.
=> Add test for adding profile with time periods

python/nav/web/alertprofiles/forms.py, tests/integration/web/alertprofiles_test.py
Add more tests to make sure that all kind of values can be posted for all different operators.
That also revealed that only in case of the equal operator with values being selected from a list that value is then sent as a list. In case of sysname the value is still a string and therefore should not be cleaned the same way. 
See the second commit for the specific test for that.
=> Add more expression operator tests for alert profiles and fix cleaning in ExpressionForm

bin/naventity, python/nav/ipdevpoll/snmp/common.py
This has been replaced by SNMPParameters.factory() and no callers are left.
=> Remove unused function snmp_parameter_factory

python/nav/models/manage.py, tests/integration/models/netbox_test.py
There is no code left referencing these deprecated properties, they can safely be removed now.
=> Remove deprecated Netbox SNMP properties

bin/naventity, python/nav/arnold.py, python/nav/ipdevpoll/snmp/common.py, python/nav/models/manage.py, python/nav/portadmin/snmp/base.py, python/nav/web/portadmin/views.py, tests/unittests/models/netbox_test.py
=> Allow write-enabled SNMP profiles to be used for reading when no read-only profiles are available

python/nav/web/alertprofiles/views.py, tests/integration/web/alertprofiles_test.py
When trying to update an alert profile with an id that wasn't int a value error was thrown and not caught. This PR fixes that and adds corresponding tests.
=> Catch updating alert profile with non int id

python/nav/web/seeddb/page/netbox/edit.py, tests/integration/seeddb_test.py
This fixes a regression that appeared once deprecated attributes were removed from the `Netbox` model in #2754 .  The regression causes SeedDB to crash when making changes to Netbox objects.
We had no tests in place to detect this issue, which also was not discovered by other linting tools, since the attribute accesses are dynamic.
This also adds a simple test to ensure the audit logging comparison doesn't crash.
(this regression was only on master, it never made it into a release)
=> Fix SeedDB edit netbox regression

python/nav/web/maintenance/forms.py, python/nav/web/maintenance/utils.py, python/nav/web/maintenance/views.py, tests/integration/web/maintenance/views_test.py
Catches posting maintenance tasks with invalid netbox keys as well as posting maintenance tasks with end time before start time.
Also adds tests for those cases.
=> Add more validation for posting maintenance tasks

python/nav/ipdevpoll/snmp/common.py
The `SNMPParameters` class expects its SNMP version attribute to be an integer.  However, some (or perhaps all) SNMPv1/v2c management profiles tend to store the version numbers as strings, for some reason.
The net result is that the `as_agentproxy_args()` method would fail to provide a `community` argument to SNMP v1/v2 sessions because it was unable to compare an integer version number to a string.  This would cause `ipdevpoll`/`navoidverify`/`naventity` to **always** use `public` as the SNMP community of all v1/v2c sessions.
Fortunately, this did not make it into a release.
=> Fix SNMP v1/v2c regression in async libraries

python/nav/web/portadmin/utils.py, python/nav/web/portadmin/views.py, python/nav/web/static/js/src/portadmin.js, python/nav/web/templates/portadmin/portlist.html
Adds frontend elements for changing PoE state in portadmin
=> Frontend for configuring PoE in Portadmin

python/nav/ipdevpoll/snmp/common.py, tests/unittests/ipdevpoll/snmp/common_test.py
This fixes #2767 by moving the responsibility for "parsing" the snmp version value of a profile from the `SNMPParameters.factory()` method to the `ManagementProfile` object itself.
Regression tests included.
=> Parse SNMP profile version numbers using existing `ManagementProfile.snmp_version` property

python/nav/web/seeddb/page/netbox/edit.py, python/nav/web/seeddb/page/netbox/forms.py, tests/integration/seeddb_test.py
Another thing that popped up during the pentest.
=> Catch error when adding netbox with invalid ip

python/nav/web/seeddb/page/netbox/forms.py, tests/integration/seeddb_test.py
Another things that was discovered by the pentest.
=> Catch error when adding netbox with non existing profiles

.dockerignore, Dockerfile, constraints.txt, doc/howto/generic-install-from-source.rst, doc/howto/manual-install-on-debian.rst, doc/requirements.txt, tests/requirements.txt, tox.ini
This adds a `constraints.txt` file where constraints on third party libraries can be specified.
The initial version of this file constrains `ciscoconfparse` specifically on Python versions less than 3.8 to be a version below the failing 1.8 version.
Documentation and build scripts are updated to include the new constraints file.
An existing "constraint" existed in the test environment requirements, because early `ciscoconfparse` releases in the 1.7 series did not declare dependencies (these versions were later yanked from PyPI).  This constraint is likely why our test suite never discovered this problem on Python 3.7.
Closes #2770
=> Constrain `ciscoconfparse` on Python 3.7

python/nav/web/portadmin/views.py
Fixes #2773
stop poe error from making portadmin unusable, instead disable poe and log error
=> Do not make portadmin readonly if poe error

python/nav/web/useradmin/views.py, tests/integration/web/useradmin_test.py
=> Import sudo function from correct module

CHANGELOG.md, python/nav/ipdevpoll/snmp/common.py, tests/unittests/ipdevpoll/snmp/common_test.py
If the `snmpVersion` argument to `AgentProxy` is not a version string prefixed by the letter `v`, `AgentProxy` will silently default to `v2c`.
Using `2c` as a value works, since it defaults then to `v2c`.  Using `3` also seems to work, as providing further SNMPv3 configuration arguments to the Net-SNMP library seems to automatically set the session version to `v3`, regardless of the version parameter.
However, using `1` will not work, as that will also silently default the session to `v2c`, making SNMPv1 communication impossible.
Fixes #2779 
Fixes #2772
=> Ensure `AgentProxy.snmpVersion` is prefixed by `v`

python/nav/web/maintenance/views.py, tests/integration/web/maintenance/views_test.py
Due to the convoluted logic of the edit() function, multiple variables may be referenced before proper assignment unless they are given a value of `None` first.
Unfortunately, at least two such variables were potentially referenced without being initialized first.
This ensures all variables that may remain "unassigned" are initialized to `None` at the start of the function.
Fixes #2783
=> Initialize variables that are potentially referenced before assignment in maintenance `edit()` view

python/nav/web/portadmin/utils.py, tests/unittests/web/portadmin/utils_test.py
This changes the authorization logic for editing interface in PortAdmin.  Originally, an interface is only considered "editable" if its native VLAN value is one of the VLANs the logged-in user is allowed to edit.  For an admin, this list of VLANs consists of all the VLANs that PortAdmin found to be configured on a switch.  However, if a port is configured with an invalid native VLAN value, or, as is supported on platforms like JunOS, no default VLAN value is set at all, PortAdmin was unable to determine that such a port was editable at all.
This change ensures the VLAN verification is outright skipped if the user has admin privileges in NAV.  All interfaces will be marked as editable.
Fixes #2477
=> Always allow admins to edit any interface in PortAdmin

python/nav/portadmin/handlers.py, python/nav/portadmin/snmp/cisco.py, python/nav/web/portadmin/views.py, tests/unittests/portadmin/portadmin_poe_cisco_test.py
During navref, UIA mentioned that the new PoE Status column did not show up for their Cisco equipment.
Turns out this is because `get_poe_states`  fails if even a single interface does not have a related POEPort object.
This was originally intended functionality, even the cisco PoE tests reflects this behaviour. But I realize that a device not having a relation to a POEPort device simply means it does not support PoE, and in that case it should not crash the entire function. It should instead set the state for that interface to `None` as specified in the docstring for `get_poe_states` 
This PR fixes this and updates tests accordingly. It also updates `set_poe_state` to behave similarly when it comes to missing PoE indexes
Also fixes a small issue with tests where the property for certain …
=> Fix PoE config not showing up for Cisco if interface is missing POEPort

python/nav/web/templates/portadmin/portlist.html
Fixes problem that occurs if some ports support PoE and some dont. The lines that do not suppot PoE will not have a dropdown, so the space will not be occupied by anything. This causes the save button to move to the left, as seen below.
This PR makes it so the space is always occupied if the PoE column is active.
Also remove random vlan tag that shouldnt be there
=> Fix save button moving for ports without PoE support

python/nav/web/static/js/src/portadmin.js
Fixes problem where if you change the PoE value and save, then try to go back to the original state the save button will not be active.
this was because the orig-value for the dropdown menu was not updated when saving. This PR updates the value on save and fixes the issue.
=> Fix PoE State in portadmin not updating orig-value

doc/howto/index.rst, doc/howto/mod_auth_mellon_feide.rst, doc/reference/web_authentication.rst, python/nav/etc/webfront/webfront.conf, python/nav/web/auth/__init__.py, python/nav/web/auth/remote_user.py
This piggy-backs on the remote user functionality.
=> Make mod-auth-mellon (SAML!) work for logins

requirements/base.txt
Because 2.8.4 will not build on Python 3.11.
Closes #2793
=> Upgrade psycopg2 to 2.9.9

python/nav/pgsync.py, tests/unittests/buildconf_test.py, tests/unittests/config_test.py, tests/unittests/pgsync_test.py
Ensure that the stuff that uses pkg_resource is tested, so that we can know it all still works after replacing pkg_resources with importlib.
Preparation for #2791.
=> Test pkg_resource usage

pyproject.toml, python/nav/buildconf.py, python/nav/config.py, python/nav/pgsync.py, python/nav/statemon/checker/RadiusChecker.py, python/nav/util.py, requirements/base.txt
=> Replace pkg_resources with importlib

doc/_static/custom.css, doc/conf.py, doc/requirements.txt
=> Use read the docs sphinx theme instead of bootstrap theme

requirements/optional.txt
python-ldap 3.4.0 cannot be built against newer versions of the OpenLDAP library, which no longer provide `libldap_r`, just `libldap` (which apparently now have the same re-entrant capabilities that were unique to `libldap_r` before).
=> Upgrade python-ldap from 3.4.0->3.4.4

tests/unittests/statemon/conftest.py, tests/unittests/statemon/host_test.py, tests/unittests/statemon/icmp_test.py
I accidentally discovered that several of the statemon tests were in fact broken.  They expect pping code to use the process PID as a packet ID, and end up using this in their assertions.
However, this is only sort-of true: pping actually uses the process PID modulo 2^16, since the value needs to fit in a 16-bit packet header field.  If the tests ran on a system where the test runner PID is higher than 65536, these tests would fail for no apparent reason.
This would rarely have been encountered, since the test suite most often runs inside newly created VMs or containers that are torn down immediately after the test run.  This way, the test suite would almost always encounter very low PID values.  Running the teste on my workstation with a high uptime was a different story, though.
This …
=> Fix broken statemon tests

python/nav/web/webfront/views.py
Nothing in there can ever raise a ldap.Error. my guess this is copy pasted from a bit further up in the same function
=> Remove try-except block that does nothing

python/nav/web/auth/remote_user.py, python/nav/web/auth/sudo.py, python/nav/web/auth/utils.py, python/nav/web/webfront/views.py, tests/integration/conftest.py, tests/integration/web/auth/conftest.py, tests/integration/web/auth/middleware_test.py, tests/integration/web/auth/sudo_test.py, tests/integration/web/webfront_test.py, tests/unittests/general/web_middleware_test.py, tests/unittests/general/webfront_test.py
For #2804 (might not solve it fully depending on how many changes to session id we want to do)
Cycles session ID on login. Or more generally, every time a different user is made into the active account for the session, so this includes the sudo/desudo functions where the logged in account is changed.
Had some issues testing against sessions with a session scoped `client` fixture. Changing this to `function` scoped and ensuring I get a fresh client for each test was a lot better
=> Cycle session ID on login

tests/unittests/general/conftest.py, tests/unittests/general/web_middleware_test.py, tests/unittests/general/webfront_test.py
Fixes #2841 
Only reasonable way to share code like this between files is via a fixture afaik. Could have defined the fixture to return the class itself and not an instance of the class, but that felt weird. This should work fine
=> Define FakeSession as a fixture

python/nav/ipdevpoll/pool.py, python/nav/mibs/mibretriever.py, requirements/base.txt, tests/requirements.txt
Because Twisted 20 won't build for Python 3.11.
Closes #2792
=> Upgrade Twisted to a version compatible with both Python 3.7 and 3.11

tests/integration/web/auth/conftest.py, tests/integration/web/auth/middleware_test.py, tests/integration/web/auth/sudo_test.py
Stops the following warning:
RemovedInDjango40Warning: Passing None for the middleware get_response argument is deprecated
=> Remove deprecation warning for Django 4.0 in tests

python/nav/smidumps/DNOS-SWITCHING-MIB.py
=> Ensure that backslashes are escaped correctly

NOTES.rst, doc/howto/index.rst, doc/howto/securing-nav-in-production.rst, python/nav/django/settings.py, python/nav/etc/webfront/webfront.conf, python/nav/web/security.py
Closes #2194
Use it (for now) for setting secure cookies and the most basic form of XSS-protection.
=> Create new config section for web security settings

python/nav/django/settings.py, python/nav/web/security.py
=> Add support for http header X-Frame-Options

python/nav/activeipcollector/manager.py, tests/unittests/general/prefix_ip_collector_test.py
Don't test epoch values against naive datetimes
When running the test suite on a machine set to the UTC timezone, `test_find_timestamp` would fail, because the datetime object used to seed the value is timezone-naive.  The test would work fine in UTC+1 timezones, but not in other timezones. 
This also refactors the convoluted logic of the function itself.
=> Fix activeipcollector `get_timestamp` function implementation and its broken timezone-naive test

doc/_static/custom.css
Closes #2833.
Some other little improvements to the `custom.css` file.
=> Fix contrast in docs footer

.github/workflows/build-and-test.yml, tests/docker/Dockerfile, tox.ini
In production we are running on Python 3.7 and 3.9 (soon also to be running on 3.11) so speed up tests by not running them on Python 3.8.
=> Stop testing on Python 3.8

.github/workflows/build-and-test.yml, .github/workflows/publish-test-results.yml, python/nav/web/webfront/views.py, tests/docker/Dockerfile, tox.ini
Small steps: let's run on on 3.10 before we tackle 3.11
=> Test on python 3.10

doc/intro/getting-organized.rst, doc/intro/getting-started.rst, doc/intro/install.rst, doc/overview.rst
When working on #2641 I noticed that a lot of things are outdated in the documentation. I am planning on going through it with a fine comb and fix anything that sticks out to me.
Always open for disagreements on my changes. 
I also found the line "For now, the key information here is the `Last updated` field of the top-left detail panel." in `getting_started.rst`, while I cannot find such a field in the picture below it. So that would need to be changed, but I don't know to what.
=> Clean up overview/intro docs

pyproject.toml
For some unknown reason, pydantic was added to the dependency list in pyproject.toml, but NAV has no such dependency.  This removes it.
=> Remove nonsensical pydantic requirement

Dockerfile
We are working on replacing SASS compilation (and later JS bundling) with webpack, which will require Node and NPM.  This change adds these tools to the Docker-based development environment so everything can be built there.
This is needed for #2849 to be completed.
=> Install Node/NPM in docker dev environment

tests/integration/web/crawler_test.py
On (some?) 500-errors, content Page.content_type does not have the method "lower", triggering a new exception that makes more of a hassle finding what caused the 500.
A request that returns with a 500 response-code has no HTML to validate anyway so let's just bail.
=> Preserve 500-error in test

python/nav/ipdevpoll/jobs.py, python/nav/statemon/db.py
Closes #2847.
I was not able to reproduce 
```
tests/integration/watchdog_test.py::test_get_status_cache_does_not_raise
/source/.tox/integration-py310-django32/lib/python3.10/site-packages/django/core/cache/backends/filebased.py:36: RuntimeWarning: Pickled model instance's Django version 3.2.23 does not match the current version 3.2.24.
return pickle.loads(zlib.decompress(f.read()))
```
=> Fix warnings during integration tests

python/nav/django/settings.py, python/nav/web/session_serializer.py
Replaces #2852 and does not depend on #2828
> The default has been JSONSerializer since after Django 1.6. /../  PickleSerializer has been deprecated since Django 4.1 and was removed in Django 5.0.
If using `signed_cookies` as the session engine, serializing with pickle is a security problem. We do not use signed_cookies, so we can continue to use PickleSerializer.
This vendored version makes the serializer incompatible with the signed_cookies engine just in case.
See also #2865
=> Vendor the PickleSerializer

python/nav/bin/navclean.py, python/nav/bin/navsynctypes.py, tests/integration/bin_test.py, tests/integration/conftest.py, tests/requirements.txt
The `navclean` and `navsynctypes` scripts were broken in NAV 5.9.0, after the method of script installation was modernized.
This PR changes the test suite to test-run the scripts defined for installation in `pyproject.toml`, rather than running them in-place in the `nav.bin` package, to ensure that they are truly compatible with being executed by end-users in an installed system.
Fixes #2874
=> Fix broken `navclean` and `navsynctypes`  scripts

.github/workflows/build-and-test.yml
`CODECOV_TOKEN` is already added to the repository secrets.
=> Upgrade codecov-action to v4

.github/workflows/towncrier.yml, .gitignore, .pre-commit-config.yaml, CHANGELOG.md, changelog.d/+towncrier-changelog.added.md, doc/hacking/hacking.rst, doc/hacking/release-procedure.rst, pyproject.toml, requirements/optional.txt
To avoid merge conflicts on direct changes to `CHANGELOG.md` for every PR.
Also adds towncrier to pre-commit and Github Actions.
=>  Add towncrier to produce changelog

tools/docker/full-nav-restore.sh
After the Docker development container was re-engineered (in #2859) to run as a non-root user, this helper script stopped working, as it now needs sudo to run the nav start/stop command.
This doesn't constitute a user-visible change, so I don't think we will need a news fragment for this.
=> Fix broken `full-nav-restore.sh` script

.github/workflows/build-and-test.yml, NOTES.rst, changelog.d/+pg11.changed, doc/howto/generic-install-from-source.rst, docker-compose.yml
Realistically, nothing in NAV currently uses any PostgreSQL syntax newer than version 9.6.  However, this version of PostgreSQL has been EOL for many years, and we cannot even dump production data from modern PostgreSQL versions and expect to load them into our development installs by now.  Also, we expect to update to a newer Django release soon, and Django has deprecated support for PostgreSQLs older than 12.
PostgreSQL 13 ought to be our target, but the next NAV release should still be able to run on Debian Buster, which means PostgreSQL 11 must be the minimum for this release.  We can move to require PostgreSQL 13 in NAV 5.11.
This ensures that the dev environment will run PostgreSQL 13.  The Docker test environment and the GitHub test environments should be running PostgreSQL 11 …
=> Update PostgreSQL requirement to version 11

NOTES.rst, changelog.d/+py37-deprecation.deprecated.md
=> Add deprecation warnings for Python 3.7 in upcoming feature releases

changelog.d/2898.fixed.md, python/nav/web/sass/nav/_select2.scss
Selector labels in forms did once have a visible delete icon (the X), not sure when they disappeared.  It seems the image they refer to has never been in the NAV code under that name, even if I'm sure I've seen it work at some point.
=> Add back missing delete icon for form selectors

README.rst, changelog.d/2907.removed.md, doc/hacking/hacking.rst, doc/hacking/release-procedure.rst, doc/index.rst
We are closing down our IRC support channel due to many years of low activity levels.  We have several other means of team and user communication that are far more popular.
This removes references to the IRC channel from our docs.
=> Remove all IRC channel references from documentation

.github/workflows/publish-test-results.yml
Closes #2862.
This will only publish test results if the branch the workflow "Build NAV and run full test suite" is running on is not master.
Reference: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onworkflow_runbranchesbranches-ignore
Does this workflow usually fail on pushes to other branches? Because the commit https://github.com/Uninett/nav/commit/3e434bc8f6c50284f1fd0b87189a0103d158d949#diff-208a7f7ef0a1174d68708f24502994bd2a136c75128806eb0cf63c0a70679321 does not do anything about this as far as I understand it. 
See https://github.com/EnricoMi/publish-unit-test-result-action/releases/tag/v2.15.0 for the change in the publish Github action.
=> Do not publish test reports on pushes to master

changelog.d/2887.added.md, python/nav/web/utils.py, requirements/base.txt, tests/unittests/web/qrcode_test.py
First step for #2586.
Not used anywhere yet, just the first step. Can be tested by changing the function itself to save the picture using `img.save(path)`.
I am uncertain about the way of getting the font, but to be able to change the font size we need to get a font from somewhere.
=> Add functionality to produce QR codes

NOTES.rst, changelog.d/+py37-deprecation.deprecated.md
Our deprecation of Python 3.7 is a de-facto deprecation also of Python 3.8, since we will only explicitly target that and newer versions.  The notes and changelogs should be more explicit about this.
=> Also deprecate Python 3.8

changelog.d/+2669.fixed.md, python/nav/asyncdns.py
Fixes #2669 
Limits concurrent parallel lookups to 100 at a time.
Tested manually that machine tracker no longer crashes from hitting the file descriptor limit with `ulimit` set as low as 200 on a search with 4096 results.  This would previously crash instantly
The amount of parallel lookups should perhaps be configurable but that can be separate pr if we see the need
A practical change I made is that saving the results from a lookup to the dict `self.results` will now happen during the parallel lookups, instead of at the end. I made this change simply because using `Cooperator` changes how the `DefferedList` we use look like. Instead of all the separate lookup tasks being in the list, the list now contains 100 iterators. 
I dont know how to add a callback to the list that will actually …
=> Reduce number of concurrent DNS lookups in Machine Tracker

changelog.d/2913.fixed.md, doc/reference/backend-processes.rst, python/nav/bin/navclean.py, python/nav/etc/cron.d/dbclean, python/nav/models/sql/changes/sc.05.10.0001.sql
Instead of immediately closing the ARP records read from a netbox as soon as its pping up/down status flaps, we should wait for the netbox to stay down for longer.  At this point, we cannot accomplish this usefully as a PostgreSQL rule or trigger, so this suggests removing the old database rule and replacing it with a new argument to the already-existing `navclean` command.  In this way, the expiry interval is even configurable for end users (or can be disabled entirely).
The terminology used in the `navclean` code was heavily centered around the concept on deletion, so this PR also introduces a renaming of this concept to just the generic "cleaning", since the new cleaner type doesn't actually delete records, it just sets a timestamp in them.
Fixes #2910
=> Delay ARP record closures for devices that have been down for a while

changelog.d/2924.fixed.md, python/nav/ipdevpoll/plugins/paloaltoarp.py
This resolves #2924 by making the parse_arp function index agnostic.
=> Make parse_arp index agnostic

changelog.d/2910.fixed.md, python/nav/models/sql/changes/sc.05.10.0002.sql
Unfortunately, #2913 (43d5543be92494877c92e082373ceaebd24568e6) deleted the incorrect database rule and made it into a release.  This reinstates the rule, ensures data integrity and deletes the *correct* rule: `netbox_status_close_arp`
Fixes #2910
=> Reinstate database rule `netbox_close_arp` and delete `netbox_status_close_arp` instead

.github/workflows/build-and-test.yml, .github/workflows/dockercompose.yml, .github/workflows/linter.yml, .github/workflows/publish-test-results.yml
Since upgrading the codecov action to version 4 uploading coverage reports without a token (so when creating a PR from a fork) is severely rate limited, which resulted often enough in our tests seemingly failing, even though it was only the coverage upload failing. (Reference: https://docs.codecov.com/docs/codecov-uploader#supporting-token-less-uploads-for-forks-of-open-source-repos-using-codecov)
Workflows that are triggered by other workflows are always run within the context of the main repository, instead of within the fork (except for workflows triggered by pushes to main in a fork, they are run within the context of the fork). This means that that way we can have access to the secret CODECOV_TOKEN and avoid the rate limitations.
Since we already upload our coverage results as …
=> Factor out codecov upload

.github/workflows/dockercompose.yml, doc/hacking/snmp-tunnels.rst, doc/hacking/using-docker.rst
GitHub Actions no longer supports the v1 Docker Compose command docker-compose, so we need to switch over to docker compose.
Reference: https://github.com/orgs/community/discussions/116610
=> Replace docker-compose in workflow with docker compose

python/nav/alertengine/base.py, python/nav/metrics/lookup.py, python/nav/web/ipdevinfo/host_information.py
This was introduced in Python 3.8: https://docs.python.org/3/whatsnew/3.8.html#functools
=> Use lru_cache as decorator

python/nav/alertengine/dispatchers/sms_dispatcher.py, python/nav/bin/navmain.py, python/nav/django/validators.py, python/nav/ipdevpoll/config.py, python/nav/ipdevpoll/log.py, python/nav/ipdevpoll/plugins/dot1q.py, python/nav/ipdevpoll/plugins/prefix.py, python/nav/models/fields.py, python/nav/models/manage.py, python/nav/models/profiles.py, python/nav/startstop.py, python/nav/statemon/abstractchecker.py, python/nav/statemon/checker/FtpChecker.py, python/nav/statemon/checker/MysqlChecker.py, python/nav/statemon/checkermap.py, python/nav/web/geomap/db.py, tests/integration/models/model_test.py
These methods have been added to Python 3.9: https://peps.python.org/pep-0616/
They remove the prefix/suffix if it exists and do nothing to the string if not.
=> Use removeprefix and removesuffix string methods

.github/workflows/build-and-test.yml, NOTES.rst, changelog.d/2892.changed.md, doc/howto/generic-install-from-source.rst
Closes #2892.
After dropping support for Python 3.7 NAV will not run on Debian Buster anymore, only Debian Bullseye and therefore we can update our required PostgreSQL version to 13.
=> Update PostgreSQL requirement to version 13

.git-blame-ignore-revs, python/nav/bin/pping.py, python/nav/buildconf.py, python/nav/daemon.py, python/nav/debug.py, python/nav/django/templatetags/report.py, python/nav/django/templatetags/string_manipulation.py, python/nav/errors.py, python/nav/eventengine/topology.py, python/nav/ipdevpoll/__init__.py, python/nav/ipdevpoll/jobs.py, python/nav/ipdevpoll/plugins/arp.py, python/nav/mibs/cpqpower_mib.py, python/nav/mibs/juniper_mib.py, python/nav/models/images.py, python/nav/portadmin/snmp/base.py, python/nav/smsd/navdbqueue.py, python/nav/statemon/checker/PostgresqlChecker.py, python/nav/web/networkexplorer/mixins.py, python/nav/web/radius/db.py, python/nav/web/seeddb/page/service/edit.py, python/nav/web/webfront/__init__.py, python/nav/web/webfront/utils.py
This should fix the problems in #2909.
=> Reformat files using new black version (24.4.2)

.github/workflows/build-and-test.yml, tests/docker/Dockerfile, tests/integration/conftest.py
`snmpsimd.py` was renamed to `snmpsim-command-responder`(reference:  https://docs.lextudio.com/snmpsim/changelog#revision-1-0-0-released-on-nov-13-2022)
The lock on pyasn1 can also be removed since the never versions of snmpsim are compatible with it.
This reverts parts of #2622 and #2946.
=> Update snmpsim to newer version

.github/workflows/build-and-test.yml
To make sure that all dependencies still work. We already build the docker image daily, but as we've seen with `snmpsim` (#2946) that was not enough.
=> Run tests on schedule (daily)

python/nav/Snmp/pynetsnmp.py, python/nav/bin/navclean.py, python/nav/eventengine/severity.py, python/nav/ipdevpoll/plugins/modules.py, python/nav/ipdevpoll/plugins/paloaltoarp.py, python/nav/ipdevpoll/snmp/common.py, python/nav/jwtconf.py, python/nav/models/manage.py, python/nav/napalm.py, python/nav/portadmin/handlers.py, python/nav/portadmin/napalm/juniper.py, python/nav/portadmin/snmp/base.py, python/nav/portadmin/snmp/cisco.py, python/nav/web/alertprofiles/forms.py, python/nav/web/portadmin/utils.py, python/nav/web/utils.py, tests/integration/conftest.py
Dependent on #2949.
See https://peps.python.org/pep-0585/. 
Since Python 3.9 one can simply use the build-in version.
=> Remove Dict, List, Tuple and Type imports from Typing

tests/docker/Dockerfile
why: nodejs version 14 gives a deprecation warning when building the test docker image. Version 18 is the oldest nodejs version that is not deprecated.
=> Use nodejs version 18 instead of version 14 in when building test docker image

.github/workflows/build-and-test.yml, tests/docker/Dockerfile, tests/requirements.txt
snmpsim belongs inside the tox test environments, and is required for several tests.  Not sure why it was being installed explicitly in the Dockerfiles and workflows, when the correct approach is to name it in the test requirements (I'm guessing because it is used as a command and not as a library by the test suite).  This way, it doesn't need to be referenced multiple times.
Also, it appears that snmpsim is once again incompatible with pyasn1, so this also introduces a version constraint for that.
=> Fix more snmpsim problems

.pre-commit-config.yaml, pyproject.toml
This version automatically ignores .gitkeep files. It reverts #2942.
=> Upgrade pre-commit to towncrier 24.8.0

changelog.d/+macos-testsuite-fixes.fixed.md, python/nav/Snmp/__init__.py, tests/integration/conftest.py, tox.ini
This extracts MacOS and NixOS-related commits from #2675 .  They should not affect the test suite on Debian-derived or FHS-compatible Linux OS-es, but will aid in making it run properly on MacOS or NixOS.
=> Fix various issues with running test suite on "non-standard" platforms

python/nav/web/auth/utils.py, tests/conftest.py, tests/functional/conftest.py, tests/integration/conftest.py
Instead of creating a "fake" admin session directly in the database, this changes the overloaded `selenium` fixture to log in to the NAV interface as an admin, using a username and password, before handing the selenium driver to the calling test.
It seems as though our recent fixes to avoid session fixation may cause the whole "session fakery" to become flaky, as the session cookie might be reset by loading a page, causing the old selenium fixture to time out waiting for the expected cookie.
There's also the old issue of whether the faked session will be properly committed to the database and be visible to the web server process that runs outside of the test session.
These issues can all be circumvented by just simulating a "normal" login.
=> Replace session fakery by login simulation in Selenium functional tests

.github/workflows/build-and-test.yml
Currently, if a PR is made from a repo-local branch, the full test suite runs twice, because it triggers on both the branch push and the PR event.
We do not usually keep long-lived feature branches, so it should be ok to restrict full test runs to the important branches: `master` and any branch that matches the stable branch pattern.
As discussed with @johannaengland
=> Restrict which branch pushes cause a full CI run

python/nav/web/templates/seeddb/_filter_form.html
A little fix to #2981 that I found while comparing the html of old and new filter forms. 
Before it was `<div id="div_id_net_type" class="ctrlHolder ">` and now it is `<div id="div_id_net_type" class="ctrlHolder">`
Not sure if it actually makes a difference?
=> Remove space in div class name in filter form

.github/workflows/towncrier.yml
Since dependabot only updates the GitHub actions these pull requests do not need a changelog fragment.
=> Disable towncrier check on dependabot PRs

python/nav/web/seeddb/page/vlan.py, python/nav/web/templates/seeddb/_filter_form_columns.html, python/nav/web/templates/seeddb/list.html
Closes #2991.
Using pattern established by the `RoomFilterForm` refactor (#2981). 
I added another template. If there is a nicer way of fixing it, please let me know!
=> Remove crispy-forms from `VlanFilterForm`

python/nav/web/seeddb/forms/__init__.py
Using pattern established by the `RoomFilterForm` refactor
Closes #2986
=> Remove crispy-forms from `NetboxTypeFilterForm`

changelog.d/2979.fixed.md, python/nav/web/alertprofiles/views.py, tests/integration/web/alertprofiles_test.py
=> Fix RuntimeError when re-ordering filters within an Alert Profiles filter group

changelog.d/2269.fixed.md, python/nav/web/seeddb/page/netbox/edit.py, tests/integration/seeddb_test.py
Fixes https://github.com/Uninett/nav/issues/2269
=> Fix seeddb netbox-edit form so that empty function field will remove function info from netbox

changelog.d/+ipdevinfo-tooltip-typo.fixed.md, python/nav/web/templates/ipdevinfo/port-details-main-frag.html
When an aggregate link is downgraded, a special mouseover/tooltip is added to the "Degraded" label.  This fixes a slight grammar/typo issue with this sentence.
=> Fix typo in ipdevinfo tooltip

changelog.d/2966.changed.md, tests/integration/web/crawler_test.py
This is a necessary step to move the test web server setup from `tests/integration/conftest.py` to a test suite fixture in the future:
Before this PR, a reachability test and a HTML validation test was dynamically generated for each reachable page, by crawling a NAV web server at test discovery time, and using this to parametrize the reachability and validation tests (which sort of artificially inflated the number of tests in the test suite).
However, it is much more useful to make a resource fixture for the web server, so tests that need it can declare their dependency on it.  Even if it were possible to use a fixture as input to test parametrization, it would mean that the test discovery phase was still dependent on a web server already running.
This leaves us with the suggestion of …
=> "Un-parametrize" webcrawler tests

tests/conftest.py, tests/functional/conftest.py, tests/integration/conftest.py, tests/integration/web/crawler_test.py
This cleans up the test suite somewhat, by changing how gunicorn is launched to provide a fully operational NAV web ui for the test suite.
Gunicorn is needed both by the integration and the functional test suites, but its launch was duplicated in both suites' `conftest.py` files.  Also, as part of the `pytest_configure()` and `pytest_unconfigure()` functions of those modules, the gunicorn server would *always* be launches on every test session, regardless of which tests were selected.
This changes the mechanism to properly function as a pytest fixture, which means that tests can now explicitly declare a dependency on the gunicorn test web server.   This ensures it will only ever be launched when tests that use it are selected.
The PR ensures existing tests that need the web server are …
=> Change test suite web server (gunicorn) launch to a proper pytest fixture

changelog.d/2945.added.md, pyproject.toml, python/nav/bin/update_ouis.py, requirements/base.txt, tests/integration/update_ouis_test.py
Closes #2958
Reliant on #2896
Adds a script that downloads a document of all OUIs and uses this to update OUI records in the database.
Django 3.2 didnt have great tools for updating database in a clean way so old ones are removed and  current ones are updated (if an OUI got registered under a different name for instance), but it does have great tools for creating a lot of rows and deleting a lot of rows, so thats what I went with. Open for suggestions on improvements.
=> Add script for updating OUI records

pyproject.toml, python/nav/web/seeddb/__init__.py, python/nav/web/seeddb/page/cabling.py, python/nav/web/seeddb/page/location.py, python/nav/web/seeddb/page/management_profile/__init__.py, python/nav/web/seeddb/page/netbox/__init__.py, python/nav/web/seeddb/page/netbox/edit.py, python/nav/web/seeddb/page/netboxgroup.py, python/nav/web/seeddb/page/netboxtype.py, python/nav/web/seeddb/page/organization.py, python/nav/web/seeddb/page/patch/__init__.py, python/nav/web/seeddb/page/prefix.py, python/nav/web/seeddb/page/room.py, python/nav/web/seeddb/page/service/__init__.py, python/nav/web/seeddb/page/usage.py, python/nav/web/seeddb/page/vendor.py, python/nav/web/seeddb/page/vlan.py, tests/unittests/models/fields_test.py
This is leftover from before Django had its build-in `reverse_lazy` function. Now we can simply use Django's own function.
Also removes another duplicate import from a test. And adds "F81" to ruff's ruleset.
=> Remove `reverse_lazy` helper function

changelog.d/2982.added.md, doc/reference/alerttypes.rst, python/nav/etc/alertmsg/deviceState/deviceDeletedFan-email.txt, python/nav/etc/alertmsg/deviceState/deviceDeletedFan-sms.txt, python/nav/etc/alertmsg/deviceState/deviceDeletedPsu-email.txt, python/nav/etc/alertmsg/deviceState/deviceDeletedPsu-sms.txt, python/nav/ipdevpoll/shadows/__init__.py, python/nav/models/sql/changes/sc.05.05.0002.sql
Closes #2982 
This PR adds alerts for deviceDeletedFan and deviceDeletedPsu. These are used to create events when PowerSupplyOrFan objects are deleted
=> Create events when PowerSupplyOrFans are deleted

changelog.d/2948.added.md, python/nav/jwtconf.py, python/nav/web/jwtgen.py, requirements/base.txt, tests/unittests/web/jwtgen_test.py
#2481
partial replacement for #2569 
Adds functions for generating access and refresh Tokens of the Jason Web variety.
The expiry values should probably be configurable, but I'd rather do that in a separate PR since it would require 
deciding the granularity of expiry (seconds, minutes, hours), updating docs etc etc ..
=> Add module for generating JWTs

tests/integration/api_test.py, tests/integration/bin_test.py, tests/integration/models/alert_test.py, tests/integration/models/fields_test.py, tests/integration/models/netbox_test.py, tests/integration/web/info_test.py, tests/integration/web/templatesyntax_test.py, tests/integration/widget_test.py, tests/unittests/api/api_test.py, tests/unittests/general/logengine_test.py, tests/unittests/ipdevpoll/config_test.py, tests/unittests/ipdevpoll/descrparsers_test.py, tests/unittests/ipdevpoll/mibs_test.py, tests/unittests/snmptrapd/weathergoose_test.py, tests/unittests/statemon/icmp_test.py, tests/unittests/watchdog/tests_test.py, tests/unittests/web/sortedstats/sortedstatsconfig_test.py, tests/unittests/web/webfront_test.py
One parts of removing unused imports in order to add more rules to ruff.
=> Remove unused imports in tests

python/nav/bin/navdump.py, python/nav/django/settings.py, python/nav/models/fields.py, python/nav/report/matrixIPv6.py, python/nav/web/seeddb/page/prefix.py, tools/eventgenerators/devicenotice.py
Most of these were from when  switching from Django version 1 to 2, where checks like `if django.VERSION[:2] == (1, 8):` were done. This was introduced in e.g. #1899. Since we are currently only supporting Django 3.2 and the adaptations have been removed these imports are not necessary any longer. 
Other Django imports are also from code that has been removed by now.
=> Remove unused Django imports

python/nav/ipdevpoll/snmp/pynetsnmp.py, python/nav/web/seeddb/page/netbox/forms.py
Another part to adding `F401` to the ruff rules. 
Also add `__all__` to `pynetsnmp` to make ruff happy-
=> Remove unused third party imports

tests/requirements.txt, tox.ini
This adds the `pytest-xvfb` plugin as a test requirement and removes the now redundant tox commands to set up an Xvfb server before the functional test suite runs.  Additionally, it simplifies the bootstrap of Xvfb in the javascript test environment.
This is part of wider strategy to make running the test suite more independent of tox: Tox is there to help us set up test matrices as separate environments, but the test suite itself should really be able to run on manually built environments.
=> Simplify Xvfb bootstrap in test suite

tests/unittests/general/util_test.py, tests/unittests/general/webfront_test.py
As preparation to add `E712` to ruff rules.
=> Use is instead of == to compare to True/False in tests

python/nav/models/fields.py
While cleaning up other things in order to add new rules to ruff I stumbled over this adaptation that was introduced in #1752, but never removed. Since we're running on Django 3.2, this can be removed.
=> Remove adaptation for Django 1.8

python/nav/web/templates/threshold/set_threshold.html, python/nav/web/threshold/forms.py
Fixes #3050
url:
http://localhost/threshold/ Adding a new rule and editing existing rules are controlled by this form
=> Uncrispify ThresholdForm

python/nav/web/alertprofiles/forms.py, python/nav/web/templates/alertprofiles/subscription_form.html
Fixes #3053 
Url: http://localhost/alertprofiles/profile/time-period/1000/subscriptions/
=> Uncrispify AlertSubscriptionForm

python/nav/web/crispyforms.py, python/nav/web/templates/custom_crispy_templates/submit_field.html
Some forms in NAV currently use [LabelSubmit](https://github.com/Uninett/nav/blob/6c83dcfb135099f92b347c1344ac6172a95128c1/python/nav/web/crispyforms.py#L38-L41), which is a submit button with a label with the content `&nbsp;` in it to align it within a row. [Template of LabelSubmit](https://github.com/Uninett/nav/blob/6c83dcfb135099f92b347c1344ac6172a95128c1/python/nav/web/templates/custom_crispy_templates/submit_field.html)
I stumbled over it while working on #2991, because it is used in `VlanFilterForm`.
I simply added a boolean attribute `label` to the `SubmitField` class and when that one is set to true this label is added above the submit button.
If I should handle this differently, e.g. adding a new template/class, please let me know.
=> Make it possible to use SubmitField for LabelSubmit

python/nav/web/alertprofiles/forms.py
=> Remove unused import

python/nav/web/templates/custom_crispy_templates/field_helptext_as_icon.html
Whitespace showed up on checkboxes without this.
Diff is large cause of indentation changes
=> Add spaceless wrapper around helpfield template

python/nav/web/alertprofiles/forms.py, python/nav/web/templates/alertprofiles/base_detail.html
Fixes #3054
Alertprofiles loads the forms in its `base_details.html` file, meaning all the different forms on the alertprofile page (the various tabs) are loaded in the same place. So the HTML cannot be completely uncrispified until all the Forms are uncrispified
url: http://localhost/alertprofiles/matchfields/
=> Uncrispify MatchFieldForm

.github/workflows/build-and-test.yml
GitHub uses `?` to indicate zero or more characters instead of the regex `+`. 
Reference: https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
=> Fix branch specification for test workflow

python/nav/web/sortedstats/forms.py, python/nav/web/templates/sortedstats/sortedstats.html
Closes #3063. 
Url: http://localhost/stats/
=> Uncrispify `ViewForm` in sortedstats

python/nav/web/alertprofiles/forms.py
Closes #2999.
Url: /alertprofiles/profile/<profile-id\>/
=>  Remove crispy-forms from `AlertProfilesForm` in alert profiles

python/nav/web/alertprofiles/forms.py
Fixes #3076 
I assume that the column containing `HTML('')` was there to act as a fake column so the formatting of the other columns was correct. If this is removed, then one of the columns get sent far to the right.
A `FormColumn` with an empty `fields` argument seems to accomplish the exact same thing.
URL: http://localhost/alertprofiles/address/
=> Uncrispify AlertAddressForm

python/nav/web/alertprofiles/forms.py
Fixes #3085 
url: http://localhost/alertprofiles/filter-groups/
=> Uncrispify FilterGroupForm

python/nav/web/templates/alertprofiles/base_detail.html
=> Uncrispify alertprofiles/base_detail.html

python/nav/web/ipdevinfo/forms.py, python/nav/web/templates/ipdevinfo/search.html
=> Uncrispify `SearchForm` in ipdevinfo

changelog.d/+remove-block-template-vlan.removed.md, python/nav/web/templates/seeddb/edit_vlan.html
This was added in https://github.com/Uninett/nav/commit/78f3127fa5eea1eb33a4854e099f29f0e3df1cfe and https://github.com/Uninett/nav/commit/b74c30689d47beae6332a6c001e2dcff1237403c, but when this block was removed in https://github.com/Uninett/nav/pull/2153/ it was forgotten. 
So now we can remove it!
=> Remove unused block in `edit_vlan` template in seedDB

python/nav/web/seeddb/page/service/edit.py, python/nav/web/templates/seeddb/service_netbox_form.html, python/nav/web/templates/seeddb/service_property_form.html
Closes #3102.
Urls:
http://localhost/seeddb/service/add/ (here one needs to click around a bit, it's a multiple step form)
http://localhost/seeddb/service/edit/<id\>
=> Uncrispify service forms in seedDB

python/nav/web/templates/webfront/preferences.html, python/nav/web/webfront/forms.py
Fixes #3100 
Not sure if the `form_action` value is correct. tried to set it to `reverse('webfront-preferences-setwidgetcolumns')` directly but that created some errors, but just giving the string without reversing seems to have worked fine?
We dont have a separate uncrispy class for `NavSubmit`, but it seems a `NavSubmit` button is pretty much just a smaller submit button using the css classes `button small`, so I just used a `SubmitField` with the additional css. 
Is it even necessary to include `button` as a class? It seems to look and behave exactly the same with just `small`
=> Uncrispify ColumnsForm

python/nav/web/templates/seeddb/list_netbox.html
Url: http://localhost/seeddb/netbox/
This was added in #1492, but from what it looks like was never actually used.
=> Remove unused `load crispy_form_tags` from netbox list in seedDB

python/nav/web/seeddb/forms/__init__.py, python/nav/web/templates/seeddb/_form_fields.html, python/nav/web/templates/seeddb/edit.html
Changes again most changes done in #2994 and instead uses our newest way of uncrispifying forms.
Urls:
http://localhost/seeddb/netboxgroup/add/
http://localhost/seeddb/netboxgroup/edit/<id\>
=> Switch `DeviceGroupForm` in seeddb to new uncrispy way

python/nav/web/maintenance/forms.py, python/nav/web/templates/maintenance/new_task.html
Fixes #3116 
url: http://localhost/maintenance/new/
=> Uncrispify MaintenanceTaskForm

python/nav/web/templates/seeddb/management-profile/edit.html
Closes #3104. 
Urls: 
http://localhost/seeddb/management-profile/edit/<id\>/
http://localhost/seeddb/management-profile/add/
=> Uncrispify management profile forms in seedDB

python/nav/web/seeddb/page/management_profile/forms.py
Reverts changes done in #3092. Makes sure that all things in seedDB that have been uncrispified use the same way. 
Dependent on #3126.
=> Use new helper function for management profile filter form in seedDB

.github/workflows/build-and-test.yml
PhantomJS development has ceased.  Our CI test suite currently fails because the outdated version of PhantomJS we're using for the JS tests is trying to use OpenSSL features that are no longer present in more recent versions of OpenSSL:
```
15 10 2024 05:25:09.525:ERROR [launcher]: PhantomJS stdout: 
15 10 2024 05:25:09.525:ERROR [launcher]: PhantomJS stderr: Auto configuration failed
140546702575424:error:25066067:DSO support routines:DLFCN_LOAD:could not load the shared library:dso_dlfcn.c:185:filename(libproviders.so): libproviders.so: cannot open shared object file: No such file or directory
140546702575424:error:25070067:DSO support routines:DSO_load:could not load the shared library:dso_lib.c:244:
140546702575424:error:0E07506E:configuration file routines:MODULE_LOAD_DSO:error …
```
=> Fix PhantomJS test problems

python/nav/web/sass/nav/my_account.scss, python/nav/web/templates/webfront/_navbar_link_form.html, python/nav/web/templates/webfront/preferences.html, python/nav/web/webfront/forms.py
Closes #3099, #3107
http://localhost/preferences/ under 'My stuff' quick links
Difference from the original implementation: the `hidden` input in each form became a part of the `<row>`. Functionally and visually it bears no difference whatsoever, yet simplifies the form template considerably.
=> Uncrispyfy NavbarlinkForm and NavbarLinkFormSet

.pre-commit-config.yaml
The newest release of [MegaLinter](https://github.com/oxsecurity/megalinter/releases/tag/v8.1.0) has upgraded the black and ruff to the newest versions (black 24.10.0, ruff 0.6.9). This PR changes the pre-commit accordingly. 
No actual formatting/linting changes necessary.
=> Upgrade linter versions to same as MegaLinter

python/nav/web/crispyforms.py, python/nav/web/macwatch/forms.py, python/nav/web/templates/macwatch/addmacwatch.html
Fixes #3109 
when this and #3108 is merged then `NavSubmit` can be removed (realistically the one that is merged last will also delete it)
Urls:
http://localhost/macwatch/add/
=> Uncrispify MacWatchForm

python/nav/web/ipdevinfo/forms.py, python/nav/web/templates/ipdevinfo/modules.html
Closes #3060.
Url: ipdevinfo/<netbox_sysname>/modules/\<perspective> (where perspective is `swportstatus`, `swportactive`, or `gwportstatus`
=> Uncrispify `ActivityIntervalForm` in ipdevinfo

python/nav/web/status2/forms.py, python/nav/web/templates/navlets/status2_edit.html
Closes #3133. 
To get there: 
From homepage add a Status widget, then click on edit in that widget.
=> Uncrispify `StatusWidgetForm` in navlets

python/nav/web/radius/forms.py, python/nav/web/templates/radius/error_log.html
Fixes #3123 
http://localhost/radius/logsearch
=> Uncrispify ErrorLogSearchForm

changelog.d/3186.fixed.md, python/nav/web/api/v1/views.py, tests/integration/api_test.py
Django REST Framework's default regexp pattern for matching object primary keys explicitly disallowed `.` characters in IDs.  Periods are perfectly acceptable in room and location identifiers, and should be allowed.
This changes the lookup regex used for rooms and locations.
Fixes #3186
=> Allow periods in room/location IDs in API

python/nav/web/seeddb/forms/__init__.py, python/nav/web/seeddb/page/service/edit.py, python/nav/web/templates/seeddb/edit.html, python/nav/web/templates/seeddb/edit_prefix.html, python/nav/web/templates/seeddb/edit_vlan.html, python/nav/web/templates/seeddb/list.html, python/nav/web/templates/seeddb/service_netbox_form.html, python/nav/web/templates/seeddb/service_property_form.html
=> Uncrispify all of seedDB

python/nav/web/crispyforms.py, python/nav/web/sortedstats/forms.py, python/nav/web/templates/custom_crispy_templates/submit.html, python/nav/web/templates/custom_crispy_templates/submit_field.html
=> Remove now unused crispy LabelSubmit

python/nav/web/crispyforms.py, python/nav/web/templates/custom_crispy_templates/form_div.html
Adds a blank div as replacement for the crispyforms `Div` class.
Part of the uncrispyfication (#2794).
Arnold `ManualDetentionForm` and `DetentionProfileForm` use `Div`s with a specific class added to it
to make it hide and reappear. Tried to recreate the effect using widget manipulation, changes to `arnold.scss `etc etc..
Using a `FormRow` worked the best, but still wasnt perfect (it messed up the margins for some reason). As a `FormRow` is just a div with the "row" css class added to it, it seems reasonable to have a class for blank div that you can do whatever you want with.
=> Add class representing a Div

python/nav/web/templates/alertprofiles/base_detail.html, python/nav/web/templates/alertprofiles/subscription_form.html, python/nav/web/templates/alertprofiles/timeperiod_edit.html, python/nav/web/templates/alertprofiles/timeperiod_form.html, python/nav/web/templates/arnold/justifications.html, python/nav/web/templates/devicehistory/history_search.html, python/nav/web/templates/devicehistory/history_view.html, python/nav/web/templates/ipdevinfo/modules.html, python/nav/web/templates/ipdevinfo/search.html, python/nav/web/templates/ipdevinfo/sensor-details.html, python/nav/web/templates/macwatch/addmacwatch.html, python/nav/web/templates/maintenance/new_task.html, python/nav/web/templates/messages/save.html, python/nav/web/templates/navlets/alert_edit.html, python/nav/web/templates/portadmin/base.html, python/nav/web/templates/seeddb/netbox_wizard.html, python/nav/web/templates/sortedstats/sortedstats.html, python/nav/web/templates/status2/status.html, python/nav/web/templates/threshold/set_threshold.html, python/nav/web/templates/useradmin/group_detail.html, python/nav/web/templates/webfront/login.html, python/nav/web/templates/webfront/preferences.html
We decided that the template [`web/templates/custom_crispy_templates/_form_content.html`](https://github.com/Uninett/nav/blob/10fe3c60ff833c8b130f1016cd5c8be0152fb02d/python/nav/web/templates/custom_crispy_templates/_form_content.html) has enough fallback by itself
For more information see #3140 and #3157.
=> Remove fallback form rendering from uncrispified forms

python/nav/web/crispyforms.py, python/nav/web/templates/custom_crispy_templates/form_row.html
As discussed in #3169. This makes it a bit tidier.
=> Make `css_classes` argument optional for `FormRow`

python/nav/web/useradmin/forms.py
As preparation of completely getting rid of crispyforms I found some occurrences where we already removed crispy from the actual forms, but the imports were not removed yet.
=> Remove unused imports from `crispy_forms_foundation`

python/nav/web/templates/auditlog/base.html, python/nav/web/templates/info/location/upload.html, python/nav/web/templates/info/room/upload.html, python/nav/web/templates/webfront/login.html
Another thing in preparation of completely removing crispy forms. These were forgotten in previous uncrispify PRs.
=> Remove unused loading of crispy_forms_tags in templates

python/nav/web/styleguide.py, python/nav/web/templates/styleguide.html
Closes #3179. 
Url: http://localhost/styleguide/
It looks slightly different now, but I think this is okay given it's the styleguide and this can be adapted in #3180.
=> Uncrispify `StyleFormTwo` in styleguide

python/nav/web/arnold/forms.py, python/nav/web/templates/arnold/manualdetain-step2.html
Fixes #3170 
Relies on #3169 
Its the second-step form after entering an IP address/mac address into http://localhost/arnold/manualdetention/
=> Uncrispify ManualDetentionForm

python/nav/web/crispyforms.py, python/nav/web/templates/custom_crispy_templates/_form_field.html, python/nav/web/templates/custom_crispy_templates/form_checkbox.html
Replacement for the crispy-reliant `Checkbox`. Needed for #3174 
I think only `DetentionProfileForm` uses this, so once that is uncrispified this new checbox should probably be renamed to just "CheckBox" and the old be removed
=> Add non-crispy checkbox

python/nav/web/templates/navlets/portadmin_view.html
This was forgotten in #3113.
How to get there:
Add a widget with the type "Portadmin" to the dashboard
=> Uncrispify portadmin navlet html template

python/nav/web/crispyforms.py
After #3057, #3052 and #3058 were merged nothing uses `HelpField` anymore, so we can remove it.
=> Remove now unused crispy `HelpField`

python/nav/web/arnold/forms.py, python/nav/web/templates/arnold/edit_detention_profile.html
Fixes #3174 
http://localhost/arnold/predefined/add
or http://localhost/arnold/predefined/edit/<id>
=> Uncrispify DetentionProfileForm

python/nav/web/arnold/forms.py, python/nav/web/crispyforms.py
After the crispy CheckBox has been removed in #3209 this can be renamed.
=> Rename `FormCheckBox` to `CheckBox`

python/nav/web/arnold/forms.py, python/nav/web/crispyforms.py
Closes #3191. Its template `custom_crispy_templates/horizontal_checkbox.html` is still in use in `web/templates/webfront/_navbar_link_form.html`, so not removing that one.
=> Remove unused crispy `CheckBox`

python/nav/web/sass/nav/custom.scss
As discovered in #3196 the css class `checkboxinput` has not been in use since the commit 43f861e (in 2013). Therefore we can simply remove it.
=> Remove unused css classes `checkboxinput`/`input-align`

changelog.d/3176.changed.md, doc/howto/generic-install-from-source.rst, doc/howto/manual-install-on-debian.rst, setup.py, tools/docker/build.sh
With `libsass` out of the way, and `setuptools_scm` long since updated, we no longer rely on having a minimal `setup.py` present.  It can be removed to complete the transition to `pyproject.toml`.
This PR removes the script and updates documentation and some scripts that referenced the old `setup.py` ways (which means this also fixes #3141)
=> Remove `setup.py` once and for all

python/nav/bin/macwatch.py, python/nav/bin/radiusparser.py, python/nav/bin/snmptrapd.py, python/nav/eventengine/severity.py, python/nav/eventengine/topology.py, python/nav/portadmin/snmp/base.py, python/nav/portadmin/snmp/cisco.py, python/nav/smsd/gammudispatcher.py, python/nav/statemon/checker/MysqlChecker.py, python/nav/statemon/db.py
As a preparation to add `F841` to ruff
=> Remove unused error variables

NOTES.rst, changelog.d/2794.removed.md, python/nav/django/settings.py, python/nav/web/crispyforms.py, requirements/base.txt
Removes `crispy-forms-foundation` and `django-crispy-forms` from requirements and necessary settings for those. Also changes some wording to not directly reference crispy
=> Remove `crispy-forms-foundation` and `django-crispy-forms` from requirements

python/nav/web/templates/styleguide.html
Fixes #3180 
@podliashanyk may have other suggestions or improvements, but she's on vacation, and we want to remove the original wording before we make a new release.  This can easily be improved further at a later date.
=> Fix obsolete crispy-forms references in UI styleguide

changelog.d/3225.fixed.md, python/nav/netmap/stubs/__init__.py, tests/unittests/netmap/stubs_test.py
=> Fix broken `__eq__` implementation of Netbox stub class

python/nav/web/static/js/src/webfront.js, python/nav/web/webfront/views.py, tests/integration/web/webfront_test.py
This is not an actual bug, but something I noticed when working on #3150. 
The "Delete dashboard" button is already not shown when there is only one dashboard, so it is not possible for a user to try to delete their last dashboard.
So to reproduce this you need to change this line to actually show that button:
https://github.com/Uninett/nav/blob/27b12b527aac40a9702cc515981346e21eab89bf/python/nav/web/templates/webfront/index.html#L147
After that when trying to delete the last dashboard an alert box will be added with the content `[Object object]` instead of showing the correct error message `Cannot delete last dashboard`.
Before: 
After:
=> Show error message on trying to delete last dashboard

changelog.d/3150.fixed.md, python/nav/web/webfront/views.py, tests/integration/web/webfront_test.py
This will disable deleting of a dashboard if it is the default on and show an alert box why it was not possible to delete the dashboard.
=> Disable deleting of default dashboard

tests/unittests/django/templatetags/info_test.py, tests/unittests/general/bulkparse_test.py, tests/unittests/ipdevpoll/prefix_test.py, tests/unittests/models/fields_test.py, tests/unittests/netmap/metadata_nx_test.py, tests/unittests/netmap/topology_layer2_testcase.py, tests/unittests/netmap/topology_layer3_testcase.py, tests/unittests/web/ldapauth_test.py
Just like #3028 and #3029 another part in adding `F841` to ruff.
=> Remove unused test variables

pyproject.toml
This is just my suggestion. so please add your opinion if and why you think this is not a great idea.
=> Add `F401` (unused imports) rule to ruff config

changelog.d/+migration-one-default-dashboard.fixed.md, python/nav/models/sql/changes/sc.05.12.0001.sql, python/nav/models/sql/changes/sc.05.12.0002.sql
Another part of fixing #3150.
As mentioned in there it is possible to delete ones default dashboard and no other is set to be default instead, essentially meaning a user can have no default dashboards. We also observed that it has somehow been possible to set multiple dashboards as default (see #2680), we still don't know how that has been possible and if it is still possible. 
This PR adds two migrations:
- the first one will find all accounts that have no default dashboard and set one to default
- the second one will find all accounts that have more than one default dashboard and remove the default marker from all but one 
Since it has not been possible to delete the last dashboard (as seen in #3232) we can assume that each account has at least one dashboard.
=> Ensure every account has exactly one default dashboard

python/nav/web/static/js/src/webfront.js, python/nav/web/templates/webfront/index.html
Dependent on #3233. Another potential part of the fix for #3150.
This hides the "Delete dashboard" button for the default dashboard. Up for discussion if this is how we want to prevent the user from trying to delete the default dashboard.
But this is how it is done for the case where the current dashboard is the last dashboard. 
Before:
After:
=> Hide "Delete dashboard" button for default dashboard

changelog.d/2908.fixed.md, python/nav/models/sql/changes/sc.05.12.0100.sql
For some long-forgotten reason, there are limits configured on the length of dropdown lists in Alert Profiles: One value per match field is set in the database.  The limits are set to 1000 for all fields, but some users do in fact have more than 1000 communication rooms registered in their NAV installations.
The code does not allow unlimited lengths, so a quickfix for now is to increase the limit ten-fold.  A more long-term fix would be to look into why there are limitations at all (aside from the fact that selecting from a dropdown with > 1000 values and no search functionality is bad UX)
Fixes #2908
=> Update list limits for alert profiles dropdowns

changelog.d/3229.added.md, python/nav/maintengine.py, tests/integration/maintengine_test.py
This changes the `maintengine` to automatically cancel active maintenance tasks if they have no valid components referenced (i.e. if the task has 0 components, or all referenced components have been deleted from the database).
It does not cancel scheduled tasks, as they may still become valid before they are activated (someone could still be editing them).
Fixes #3229
Fixed #2243
=> Cancel  scheduled maintenance tasks when all their components are missing

changelog.d/3238.added.md, python/nav/web/alertprofiles/forms.py
This makes multiple choice drop down lists in Alert Profiles filter searchable using `select2`, which makes it a lot easier to find desired values when the choice lists become huge.
Fixes #3238
Url: http://localhost/alertprofiles/filters/add-expression/
=> Make alert profiles match value dropdown lists searchable using `select2`

changelog.d/3228.fixed.md, python/nav/django/templatetags/maintenance.py, python/nav/models/fields.py, python/nav/models/manage.py, python/nav/models/msgmaint.py, python/nav/models/sql/changes/sc.05.12.0010.sql, python/nav/web/maintenance/utils.py, python/nav/web/maintenance/views.py, python/nav/web/templates/maintenance/details.html, python/nav/web/templates/maintenance/frag-component-trail.html, python/nav/web/templates/maintenance/new_task.html
This fixes #3228, but it was not feasible without a significant refactoring of the maintenance task UI codebase.
The codebase originally stems from a time before Django was added to NAV, and was significantly convoluted compared to what it needs to be.  This PR makes it slightly less so, but there is still some way to go:
There was a lot of processing and custom validation code for the component fields of the maintenance task forms, which ended up producing large hierarchies of dicts and lists (some of which were fed directly to templates), instead of re-using ORM functionality.  While much of the processing would be best encapsulated in Django Forms, this refactor mostly concerns itself with using ORM objects where we can.
The ultimate goal was really only to be able to display deleted …
=>  Refactor maintenance task views to improve display of deleted components #3230 

pyproject.toml
As #3026, up for discussion. This also adds `F842` - Local variable {name} is annotated but never used.
=> Adds unused variable rule (`F841`) to ruff

pyproject.toml
Ignored rules: Module level import not at top of cell, bare except, lambda assignments, star imports
As usual, this is up for discussion which rules we would like to have and which not. 
Dependent on #3035.
After this is merged #3005 can be merged as well.
=> Use default rules for ruff

.github/workflows/linter.yml
Otherwise only changes in a PR will be checked.
This was forgotten to change back when merging #2941, but it is convenient, now we can wait until #3045 is merged.
=> Only lint whole codebase on pushes to master

.pre-commit-config.yaml
This is the same as in the newest MegaLinter release ([8.3.0](https://github.com/oxsecurity/megalinter/releases/tag/v8.3.0))
=> Upgrade ruff to 0.8.0

changelog.d/3249.added.md, python/nav/portadmin/handlers.py, python/nav/portadmin/management.py, python/nav/portadmin/snmp/base.py, python/nav/portadmin/snmp/cisco.py, tests/unittests/portadmin/conftest.py, tests/unittests/portadmin/portadmin_test.py
This fixes #3249 in two rounds, after introducing/updating tests for the issue at hand:
* It first adds a "simple" solution by changing the Management Factory.
* If then refactors the management handler selection to something that should be more maintainable in the future.
=> Select generic `SNMPHandler` for Cisco Small Business switches in PortAdmin

NOTES.rst, changelog.d/3147.changed.md, doc/reference/ipdevpoll.rst, doc/reference/management-profiles.rst, python/nav/ipdevpoll/plugins/paloaltoarp.py, python/nav/models/manage.py, python/nav/web/seeddb/page/management_profile/forms.py, tests/integration/ipdevpoll/plugins/paloaltoarp_test.py, tests/unittests/ipdevpoll/plugins_paloaltoarp_test.py
Deprecate the `[paloaltoarp]` section of `ipdevpoll.conf` in favor of using management profiles to configure HTTP-based fetching of ARP information from Palo Alto PIO-OS firewalls, analogous to how configuration of SNMP-based fetching is done.
The new management profile protocol to configure HTTP-based fetching has been given the name `HTTP API`~~`HTTP REST API` for now, but this name might be missing the mark since there really isn't anything REST-related about the management profile type.~~ Perhaps `HTTP WITH API KEY`, would be a more fitting name?
Fixes #2894
=> Configure HTTP-based ARP information fetching from Palo Alto PAN-OS firewalls using management profiles 

NOTES.rst, changelog.d/3252.fixed.md, python/nav/etc/ipdevpoll.conf, python/nav/ipdevpoll/plugins/arp.py, python/nav/ipdevpoll/plugins/paloaltoarp.py, tests/unittests/ipdevpoll/plugins_arp_test.py
Fixes #3252 by the following strategy:
1. Makes the SNMP `arp` plugin a sort of "fallback" plugin: If it detects that ARP mappings have already been added to the container registry, it skips all SNMP-based processing of ARP, to avoid stepping on some other plugin's toes.
2. Changes the default run order of plugins in the `ip2mac` ipdevpoll job: Vendor specific plugins like `paloaltoarp` should run first, and if they they either declined to run, or didn't find anything, it cannot hurt that SNMP-based collection is run.
=> Abort SNMP-based ARP collection if ARP records seem to have been collected earlier in the same ipdevpoll job run

changelog.d/3259.fixed.md, python/nav/web/graphite/views.py, tests/integration/web/graphite_test.py
This adds what amounts to a dirty hack to the graphite-web proxy view (i.e. it reaches into Django internals) to prevent Django from doing a full error response log when proxying 5xx class errors from graphite-web.  It does so by tricking `django.utils.log.log_response()` into thinking that the response has already been logged (since our view function has no other control over how its return values are logged by Django).
The reason for the 5xx response codes are not bugs in our view code, and does not need to trigger site admin e-mails.
Adds regression tests and fixes #3259
=> Stop logging proxied 5XX Graphite errors

changelog.d/3207.fixed.md, python/nav/web/navlets/room_map.py
Fixes #3207
Seemed like the form sent a request to home (/) directly, when it probably should have been sent to /search/ instead. This at least makes it so if you search for a room and it finds a match it opens the page for the room,
and if there is no match then it still shows the search page but with the message that nothing was found.
If this is how the map widget is supposed to function is uncertain to me, I don't actually know how it originally worked before it broke (if it ever worked)
=> Fix room map widget search not doing anything

tests/docker/Dockerfile, tests/docker/Makefile, tests/docker/scripts/entrypoint.sh
This upgrades the test container image used for local integration testing to Ubuntu 24.04, which brings it more in line with the current `ubuntu-latest` tag used on Github Actions.
It also fixes some problems with the image, highlighted by the upgrade to Ubuntu 24: 
- The way privilege escalation for management inside the container works has been turned on its head.  The container now starts privileged and drops to a non-privileged user after startup-maintenance has been performed.  The main way to elevate privileges inside the container is now through `sudo`, not `gosu` (which claims it was never intended for privilege escalation and will not not work if you try it).
- Cache mounts for APT packages are added to the definition, in an attempt to make image builds faster.
- Syntax …
=> Upgrade test container image to Ubuntu 24.04

changelog.d/3262.fixed.md, python/nav/web/ipdevinfo/views.py, tests/integration/web/ipdevinfo_test.py
=> Ignore case of sysname in IP device info

changelog.d/3291.fixed.md, python/nav/bin/update_ouis.py
Got 418 error when trying to download the OUI textfile with `requests` without changing the user agent.
Seems like the server filters out requests with certain user-agent values (or potentially lack thereof).
=> Add user-agent header when downloading OUI textfile

Dockerfile
While working on #3290 I realized the top-level development `Dockerfile` we use had the same problem of the cache mounts being ineffective.
This ensures the apt cache mounts are *actually persisted* between invocations.  The Docker Ubuntu/Debian images come with a default rule to wipe the cache directories after each apt command, in order to avoid bloating up Docker images with unnecessary cache data.  When cache mounts are used, the caches aren't actually stored inside the image, and wiping them would be counterproductive.
=> Stop wiping apt cache after every apt command in development Docker image

.gitignore
Files found via:
```
$ git ls-tree -r master --name-only | egrep "^\."
.codecov.yml
.dockerignore
.git-blame-ignore-revs
.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/dependabot.yml
.github/workflows/build-and-test.yml
.github/workflows/dockercompose.yml
.github/workflows/linter.yml
.github/workflows/publish-test-results.yml
.github/workflows/towncrier.yml
.gitignore
.mega-linter.yml
.pre-commit-config.yaml
.readthedocs.yaml
.sonarcloud.properties
```
Interestingly, it also says that `.dockerignore` is untracked!?
=> Add dot-files that git must keep to .gitignore

changelog.d/3251.security.md, python/nav/ipdevpoll/plugins/paloaltoarp.py
Fixes https://github.com/Uninett/nav/issues/3251
=> Omit PaloaltoArp API key when logging

changelog.d/3261.added.md, tests/integration/web/devicehistory_test.py
After discovering and fixing a bug in the device history search in #3258 I realized there were no tests for the device history search. So this PR adds some.
=> Add tests for device history search

changelog.d/3292.added.md, python/nav/web/machinetracker/forms.py, python/nav/web/machinetracker/utils.py, python/nav/web/machinetracker/views.py, python/nav/web/templates/machinetracker/interface_tracker.html, python/nav/web/templates/machinetracker/ip_search.html, python/nav/web/templates/machinetracker/ip_tracker.html, python/nav/web/templates/machinetracker/mac_search.html, python/nav/web/templates/machinetracker/mac_tracker.html, python/nav/web/templates/machinetracker/netbios_search.html, python/nav/web/templates/machinetracker/netbios_tracker.html, python/nav/web/templates/machinetracker/switch_search.html, python/nav/web/templates/machinetracker/uplink_tracker.html
Fixes #3292 
Adds option for showing vendor name on all Machinetracker searches. Uses mac address to look up vendor name with the OUI table. This obviously requires the table to be populated, which will currently not happen automatically.
It can be populated by running the `navoui` command. I assume you can just run it normally when NAV is running locally, but with docker atleast `docker exec -ti nav-nav-1 navoui` should work
Sonarcloud is complaining about html stuff that im not too familiar with, hopefully @podliashanyk can take a look
During testing ive gotten results with the mac address 00:00:00:00:00:00. Im not sure what this is supposed to represent, a real mac address or if its a placeholder/indication of no mac address, but there is a vendor that has the 00:00:00 OUI registered, …
=> Add option for showing vendor name in Machinetracker searches

tests/functional/conftest.py
The functional tests run fine locally, but have lately started failing when run on GitHub Actions.  Screenshots from the test reports seem to indicate that the web browser is still stuck on the NAV front page even after the test has issued a navigation request for a different URL, so it may just be a timing problem.
The main selenium test fixture is supposed to return a selenium web driver where the current browser session is already logged in as an admin, but it seems perhaps the final wait for the login to succeed has been formulated wrong.  The `url_changes` waiter only looks for partial URLs, so explicitly waiting the for the full base url seems to work better.
=> Fix broken functional tests on GitHub actions

.github/workflows/build-and-test.yml, tox.ini
It appears the GitHub ubuntu-latest (24.04) runner is already pre-installed with Chrome, Chromium and chromedriver, so these explicit installation steps are unnecessary.  The chromedriver is installed in an unexpected location, though, so how we find it needed to change as well.
=> Stop installing Chrome and chromedriver explicitly into github workflows

changelog.d/3215.fixed.md, python/nav/web/api/v1/views.py
Fixes #3215 
Is the example of how subnets work necessary?
Should more info be added? Like does it support ipv4 and ipv6? which formats of ip addresses does it support?
from looking at IPy it seems to support a wide range of formats. What is relevant for the user of the API?
Draft mode because I am myself not quite sure what values the filter is supposed to accept
=> Update docs for IP filtering in ArpViewSet

pyproject.toml, requirements/optional.txt
We've fully switched to using `pyproject.toml` for the project definition, but the dependencies were not declared outside of the existing set of requirements files.
The requirements files are fine for defining various environments for testing, but the full dependency list should be declared in the project metadata.
This more or less copies all the existing requirements into the appropriate sections of `pyproject.toml`.  Minimal runtime dependencies, optional runtime dependencies, and also dependency groups for non-runtime requirements, like development or testing of the codebase.
=> Define project dependencies in `pyproject.toml`

changelog.d/3329.fixed.md, python/nav/web/templates/info/room/netboxview.html
Closes #3329.
Relevant link for testing: /search/room/<room_id>/#!netboxinterfaces
The frontend expects timestamps in the format yyyy-mm-dd hh:ii for the filtering/sorting to work.
How the `last seen` cell looked before:
In the case of `Never`:
```
Never<span class="hidden" title="Never"></span>
```
In the case of `Now` (the maxtime is given):
```
Now<span class="hidden" title="Dec. 31, 9999, 11:59 p.m."></span>
```
In the case of a specific date:
```
768 days<span class="hidden" title="Feb. 9, 2023, 11:01 p.m."></span>
```
How the frontend expects it to be:
```
51 days<span class="ui-helper-hidden" title="2012-06-11 18:19:30.491431"></span>
```
See also the [frontend tests](https://github.com/Uninett/nav/blob/c3a9bedd7918b46382d632f2f4ee3b945d8ca040/python/nav/web/static/js/test/info/glob …
=> Send timestamp in correct format in netboxview

changelog.d/3268.added.md, python/nav/models/api.py, python/nav/models/sql/changes/sc.05.14.0001.sql, python/nav/web/jwtgen.py, tests/unittests/models/jwtrefreshtoken_test.py, tests/unittests/web/jwtgen_test.py
Adds a model representing a JWT refresh token. Contains a hash of the real token. Refresh tokens can then effectively be authenticated by comparing the hash to incoming token to hashes in the database.
The model contains relevant information about the token that can be displayed in the frontend.
The function `is_active` in `jwtgen.py` exists so the logic for whether a token is active or not can be shared between the frontend and the API. The frontend will use `JWTRefreshToken.is_active` (which uses`jwtgen.is_active` internally), while the API will use `jwtgen.is_active` directly.
=> Add model for JWT refresh token

changelog.d/3243.removed.1.md, python/nav/models/profiles.py, python/nav/models/sql/changes/sc.05.14.0002.sql, python/nav/web/templates/webfront/preferences.html, python/nav/web/webfront/__init__.py, python/nav/web/webfront/forms.py, python/nav/web/webfront/urls.py, python/nav/web/webfront/views.py
Every dashboard has its own setting on how many columns it has
Closes #3243. 
I did some digging and this has not been in use since 2016 (c7cebd9210d02fbfbcdba92b033ae22300566fb4)
=> Remove unused `ColumnsForm`

pyproject.toml
[PEP-639](https://peps.python.org/pep-0639/) explicitly defines the `license` field of the project to be an SPDX license expression, also obviating the need for a license classifier.
This cleans up `pyproject.toml` to comply with this.
=> Comply with PEP 639 license spec

tox.ini
This defaults tox environments to using Django 4.2 if no django term was part of the environment name. The file declared several environments that did not work because the Django version did not have a default fallback value.
=> Set default Django version for testing

changelog.d/3360.fixed.md, python/nav/web/devicehistory/forms.py, python/nav/web/devicehistory/utils/history.py, python/nav/web/devicehistory/views.py, tests/integration/web/devicehistory_test.py
Closes #3360.
When redirecting to device history from location search the location parameter was not handled properly since the empty form was not valid, since it is not bound (contains no data).
Initial values are good for pre-populating HTML templates, but they are not used as default values: [(ref](https://docs.djangoproject.com/en/5.2/ref/forms/fields/#django.forms.Field.initial).
So we have to set these defaults manually when instantiating the form when no other parameters are given.
=> Add default values to empty `DeviceHistory` form

.github/workflows/linter.yml
For now to avoid https://github.com/oxsecurity/megalinter/issues/5358.
=> Lock MegaLinter to v8.6.0

.readthedocs.yaml, constraints.txt, pyproject.toml
A small dependency storm seems to have crept up on us today alone.
1. The docs would not build on ReadTheDocs because the Net-SNMP library is not installed in the build image. `pynetsnmp` is imported by several NAV modules that are imported for Sphinx autodocs, and these imports would fail if the C library was not present.
2. `snowballstemmer` 3.0.0 was released today, and apparently it breaks under Sphinx 7.4.7, which NAV is pinned to at the moment.  A constraint is needed to keep this package below 3.0.
3. There were incompatible Twisted requirements in the build process.  It seems #2955 and #3340 got their streams crossed, and #3340 did not include the changed Twisted version from #2955.
This PR fixes all three issues to get RTD builds working again.
=> Fix ReadTheDocs builds

changelog.d/3373.fixed.md, python/nav/web/api/v1/views.py
c2b9002 has locked down API permissions for unprivileged users, but this lead to the port view in ipdevinfo to break for unprivileged users, since the API endpoint `api/interface/` is being called to fill that view by the [frontend](https://github.com/Uninett/nav/blob/6fdf19a32fb3509a8a88c7411cff14b85ca5619b/python/nav/web/static/js/src/porttable.js#L199)
This PR lets unprivileged users access that endpoint again.
No tests for now, since I realized that we need functional tests to make sure that the frontend API call does not break anything. But manually tested.
=> Relax permissions for API interface view endpoint

changelog.d/3374.fixed.md, python/nav/web/api/v1/views.py
Needed for subnet matrix tool to work for non-admin users. The [frontend](https://github.com/Uninett/nav/blob/6fdf19a32fb3509a8a88c7411cff14b85ca5619b/python/nav/web/static/js/src/subnetmatrix.js#L65) is using the `prefix/usage/` API endpoint.
This bug was introduced in c2b9002.
Url: http://localhost/report/matrix/
=> Relax permissions for API prefix usage endpoint

python/nav/web/api/v1/auth.py, python/nav/web/api/v1/views.py
Inspired by Django Rest Framework's [IsAuthenticatedOrReadOnly](https://github.com/encode/django-rest-framework/blob/c0202a0aa5cbaf8573458b932878dfd5044c93ab/rest_framework/permissions.py#L163-L173) and our own [LoggedInPermission](https://github.com/Uninett/nav/blob/92442c288ad746add7262886c4e56bcbafc282a2/python/nav/web/api/v1/auth.py#L63-L68) I created a permission class that allows admin users to read/write and non-admin users to only read.
This was suggested by @lunkwill42 in https://github.com/Uninett/nav/pull/3375#pullrequestreview-2842642909.
=> Add read-only for non-admin and read-write for admin permission class

changelog.d/3375.fixed.md, python/nav/web/api/v1/views.py
Dependent on #3376.
Needed for room map widget. The [frontend](https://github.com/Uninett/nav/blob/6fdf19a32fb3509a8a88c7411cff14b85ca5619b/python/nav/web/static/js/src/plugins/room_mapper.js#L110) is using the `room/` API endpoint.
This bug was introduced in c2b9002
=> Relax permissions for API list room endpoint

doc/howto/migrate-data.rst
These full paths were meant as examples, but they seem to confuse users
- the NAV programs are often *not* in these specific locations (they might have been once).
=> Remove full path names from command examples

pyproject.toml
https://pypi.org/project/drf-jwt-multi-auth/
My account should prob be added to the uninett org so I can give the org account co-ownership
=> Use pypi package instead of github url for jwt-drf

python/nav/web/templates/alertprofiles/account_detail.html, python/nav/web/templates/alertprofiles/base_detail.html, python/nav/web/templates/alertprofiles/base_list.html, python/nav/web/templates/alertprofiles/expression_form.html, python/nav/web/templates/alertprofiles/permissions.html, python/nav/web/templates/alertprofiles/profile.html, python/nav/web/templates/alertprofiles/profile_detail.html, python/nav/web/templates/alertprofiles/subscription_form.html
Contributes to https://github.com/Uninett/campus-tasks/issues/45.
**Where to find the forms (ordered by commit):**
Language form: Go to http://localhost/alertprofiles/, click on "Groups and permissions", see language dropdown
Base list form: Applies to multiple sides, but e.g. see http://localhost/alertprofiles/address/ (right below "Add address" button)
Profile form: http://localhost/alertprofiles/profile/ (right below "Profiles" heading)
Add subscription form: http://localhost/alertprofiles/profile/time-period/\<id\>/subscriptions/, under "Add new expression"
Remove subscription form:  http://localhost/alertprofiles/profile/time-period/\<id\>/subscriptions/, when having added a subscription, under "For profile 'name'. Time period ..."
Delete time period from alert profile form: …
=> Add csrf token to forms in alert profiles

python/nav/web/templates/seeddb/bulk_import.html, python/nav/web/templates/seeddb/delete.html, python/nav/web/templates/seeddb/edit_patch.html, python/nav/web/templates/seeddb/list.html, python/nav/web/templates/seeddb/move.html
Contributes to https://github.com/Uninett/campus-tasks/issues/45.
**Where to find the forms (ordered by commit):**
Add patch form: Unclear for now, somewhere in http://localhost/seeddb/patch/, need to add patch data first, but could not find any template for that
Remove patch form (same commit as first): Unclear for now, somewhere in http://localhost/seeddb/patch/
Bulk import form: http://localhost/seeddb/netbox/bulk/
Delete form: Go to http://localhost/seeddb/netbox/, select a IP device, click on "Delete" button
List form: Go to http://localhost/seeddb/netbox/, see form
Move form: Go to http://localhost/seeddb/netbox/, select some IP devices and click on "Move", see form
=> Add csrf token to forms in SeedDB

python/nav/web/templates/info/event/details.html, python/nav/web/templates/info/images/upload.html, python/nav/web/templates/info/netboxgroup/group_edit.html, python/nav/web/templates/info/prefix/details.html, python/nav/web/templates/info/room/fragment_add_sensor.html, python/nav/web/templates/info/room/fragment_add_sensors_sum.html, python/nav/web/templates/info/room/fragment_add_sensorsdiff.html, python/nav/web/templates/info/room/fragment_rack.html, python/nav/web/templates/info/room/netboxview.html, python/nav/web/templates/info/room/roominfo_racks.html
Contributes to https://github.com/Uninett/campus-tasks/issues/45.
**Where to find the forms (ordered by commit):**
Upload pictures form: http://localhost/search/room/900/upload/
Add sensor forms: http://localhost/search/room/900/#!racks, add a rack, then click on "Add sensor"
Rack forms: http://localhost/search/room/900/#!racks, add a rack, then see forms (Renaming and color chooser)
Download CSV form: http://localhost/search/room/900/#!netboxinterfaces, see form under "CSV"
Edit device group form: http://localhost/search/devicegroup/ACCESS/edit/
Event handling form: Go to http://localhost/search/event/1234, select one of the available actions
Add tags to prefix form: Go to http://localhost/search/prefix/225/, see form around "Add tags" button
=> Add csrf token to forms in search

changelog.d/2897.added.md, python/nav/web/sass/nav.scss, python/nav/web/sass/nav/_qr_code.scss, python/nav/web/templates/base.html, python/nav/web/templates/webfront/_qr_code.html, python/nav/web/utils.py, python/nav/web/webfront/urls.py, python/nav/web/webfront/views.py, tests/integration/web/webfront_test.py, tests/unittests/web/qrcode_test.py
Dependent on #3386. Another part to #2586.
This adds a button to 'My Stuff' that when clicked opens a modal displaying a QR code with the link to current page. This modal can be dismissed by clicking on the "X" button or clicking outside of the modal.
=> Add QR Code link to 'My Stuff'

changelog.d/+qr-code-bulk.added.md, python/nav/web/seeddb/__init__.py, python/nav/web/seeddb/page/__init__.py, python/nav/web/seeddb/page/netbox/__init__.py, python/nav/web/seeddb/page/room.py, python/nav/web/templates/seeddb/list.html, python/nav/web/utils.py, tests/integration/seeddb_test.py, tests/unittests/web/qrcode_test.py
The last step to #2586. Dependent on #2897.
=> Make it possible to download a ZIP file containing QR codes of bulk selected netboxes/rooms

AUTHORS.rst, python/nav/web/templates/webfront/about.html
Simen's first PRs are being merged this week, so we should add him to the list of contributors :)
* ~~[ ] Added a changelog fragment for [towncrier](https://nav.readthedocs.io/en/latest/hacking/hacking.html#adding-a-changelog-entry)~~
* ~~[ ] Added/amended tests for new/changed code~~
* ~~[ ] If applicable: Created new issues if this PR does not fix the issue completely/there is further work to be done~~
* ~~[ ] If this results in changes in the UI: Added screenshots of the before and after~~
* ~~[ ] If this adds a new Python source code …
=> Add Simen Abelsen to contributor lists

changelog.d/3273.added.md, doc/howto/using_the_api.rst, python/nav/models/api.py, python/nav/models/sql/changes/sc.05.14.0003.sql, python/nav/models/sql/changes/sc.05.14.0004.sql, python/nav/web/templates/useradmin/base.html, python/nav/web/templates/useradmin/jwt_created.html, python/nav/web/templates/useradmin/jwt_detail.html, python/nav/web/templates/useradmin/jwt_edit.html, python/nav/web/templates/useradmin/jwt_list.html, python/nav/web/templates/useradmin/jwt_not_enabled.html, python/nav/web/templates/useradmin/jwt_not_enabled_content.html, python/nav/web/templates/useradmin/tabs.html, python/nav/web/templates/useradmin/token_card_style.html, python/nav/web/templates/useradmin/token_detail.html, python/nav/web/useradmin/forms.py, python/nav/web/useradmin/urls.py, python/nav/web/useradmin/views.py, tests/integration/web/jwt_test.py
Adds a frontend for managing JWT refresh tokens. You can see which tokens exist, expire existing ones and generate new ones.
Created new issue for audit log #3405, this PR is big enough
The code duplication warning is legit, but its duplicate from the old token code which will be deleted when JWTs are fully implemented and ready to take over for the old token system.
Also adds permission related fields to the JWTRefreshToken model, since these will be used when creating a token. We store the relevant permissions there so they can be displayed as token metadata. They should never be changed (hence why you cant update them in the Edit form) because the values in the actual token are the ones that matter, and those will not be updated when the database is updated. If you want new …
=> Add frontend for JWT refresh tokens

changelog.d/3457.fixed.md, python/nav/web/useradmin/views.py, tests/integration/web/jwt_test.py
Fixes #3457
Makes it so the "Recreate" function Also un-revokes the token if the token was previously revoked.
Recreate button can be found in the Edit form of a refresh token (http://localhost:8000/useradmin/jwt_tokens/edit/<pk>/)
* ~~[ ] Added/changed documentation~~
* ~~[ ] If applicable: Created new issues if this PR does not fix the issue completely/there is further work to be done~~
* ~~[ ] If this results in changes in the UI: Added screenshots of the before and after~~
* ~~[ ] If this adds a new Python source code file: Added the …
=> Unrevoke token on recreate

changelog.d/3449.added.md, python/nav/web/sass/nav.scss, python/nav/web/sass/nav/_tooltip.scss, python/nav/web/static/js/src/info_room.js, python/nav/web/static/js/src/main.js, python/nav/web/static/js/src/plugins/tooltip.js, python/nav/web/static/js/src/portadmin.js, python/nav/web/templates/alertprofiles/filter_form.html, python/nav/web/templates/alertprofiles/matchfield_form.html, python/nav/web/templates/alertprofiles/timeperiods.html, python/nav/web/templates/custom_crispy_templates/field_helptext_as_icon.html, python/nav/web/templates/foundation-5/field.html, python/nav/web/templates/info/room/netboxview.html, python/nav/web/templates/ipdevinfo/frag-disclaimer.html, python/nav/web/templates/ipdevinfo/frag-ipdevinfo.html, python/nav/web/templates/l2trace/l2trace.html, python/nav/web/templates/machinetracker/mac_tracker.html, python/nav/web/templates/webfront/index.html
Part of #2972. 
Adds an implementation for a custom NAV Tooltip. This PR replaces usages of `[data-tooltip]` throughout the codebase, with the exception of one case in the Status tool that should be done in a follow-up task, namely #3463 .
The new tooltip supports alignment from the start or end of the trigger element, and automatic change of alignment if the tooltip extends beyond the viewport.
* Adds nav tooltip styles and event listeners for updating alignment based on viewport
* Replaces usages of [data-tooltip] in various tools with the new implementation
* Replaces usage of [data-tooltip] in reusable form templates, like `foundation-5/field.html` or `custom_crispy_templates/field_helptext_as_icon.html`
**/search/room/100/#!netboxinterfaces**
**/alertprofiles/profile/1026/** …
=> Replace foundation tooltips with custom implementation

changelog.d/+42a720f9.fixed.md, python/nav/web/sass/nav/_modal.scss
Fixes an issue where the close icon overlaps the text in modals, as commented in #3497 and #3505.
* Reduces the font size of the icon to avoid overlap with modal text
* Changes close-modal-icon styles to use explicit css styles instead of extending foundation styles
The change will have the following effect on the Classification Hint modal in #3505.
=> Adjust close modal icon to avoid text overlap

changelog.d/+b607de92.changed.md, python/nav/web/static/js/src/webfront.js, python/nav/web/templates/webfront/_import_dashboard_form_modal.html, python/nav/web/templates/webfront/index.html, python/nav/web/webfront/urls.py, python/nav/web/webfront/views.py, tests/integration/web/webfront_test.py
Part of #2972. Replaces Import Dashboard modal with an HTMX implementation.
* Replaces foundation modal with HTMX
* Adds test coverage for the `import_dashboard` view
* Submit import dashboard form with htmx instead of ajax
=> Replace import dashboard modal

changelog.d/3514.changed.md, python/nav/web/radius/views.py, python/nav/web/static/js/src/radius.js, python/nav/web/templates/radius/account_log.html, python/nav/web/templates/radius/detail_modal.html, python/nav/web/templates/radius/details_table.html, python/nav/web/templates/radius/error_log.html, tests/integration/web/radius_test.py
Part of #2972. 
This PR replaces the foundation modals for the Account Log and Error Log tables. 
I was not able to find any data for Error Logs, but there is some data for Account Log if you select the following parameters:
* Username: mvold
* Time options: Day(s), 5000 days
However, I added tests for the Error Log view that should verify that the modals and refactor are working as expected.
* Replaces Account Detail modal with HTMX
* Replaces Log Detail modal with HTMX
* Add test coverage to Account and Log detail views
* Fixes bug where account and log detail views crash when query returns no results
EDIT: Account not found bug
**Before**:
Account detail view crashes on index error: [/radius/acctdetail/99999999](http://localhost:8000/radius/acctdetail/99999999)
**After**: The modal …
=> Replace radius detail modals with htmx

changelog.d/3550.added.md, python/nav/web/sass/nav/_popover.scss, python/nav/web/templates/styleguide.html
Follow up to #3458, and necessary to position popovers in #3531.
* This PR adds support for positioning the popover on multiple sides: left, top, right and bottom. The side is configured with the `data-side` attribute, as described in the styleguide. 
* The styleguide has been updated with the new `data-side` attribute, and the example was updated to use a `data-side="right" data-align="start"` configuration.
* `data-align="center"` was removed, as it is not likely to be used, and to simplify the code for multiple sides.
* `_popover.scss` was refactored to be more readable and reduce unnecessary nesting. It should be easier to follow the logic now.
I'm a bit uncertain if putting the `data-*` attributes on the `.popover` container was the best idea (the styles become a bit convoluted). We …
=> Add support for positioning popover on multiple sides

changelog.d/2479.added.md, python/nav/Snmp/__init__.py
Fixes #2479. Replaces #3539.
* ~[ ] Added/changed documentation~
* ~[ ] If applicable: Created new issues if this PR does not fix the issue completely/there is further work to be done~
* ~[ ] If this results in changes in the UI: Added screenshots of the before and after~
* ~[ ] If this adds a new Python source code file: Added the [boilerplate header](https://nav.readthedocs.io/en/latest/hacking/hacking.html#python-boilerplate-headers) to that file~
=> Strip null-bytes from bytestrings being made safe for PostgreSQL

python/nav/models/profiles.py, python/nav/web/sass/nav/custom.scss, python/nav/web/templates/webfront/_dashboard_nav.html, python/nav/web/templates/webfront/_dashboard_search_form.html, python/nav/web/templates/webfront/_dashboard_search_results.html, python/nav/web/webfront/urls.py, python/nav/web/webfront/views.py, tests/integration/conftest.py, tests/integration/web/webfront_test.py
Resolves #3556, part of #2344.
Dependent on PR #3553.
No-news as #3551 contains the news fragment.
This PR adds search functionality to the dashboard navigation. A user can search for shared dashboards by dashboard name, account name or account login. Dashboards belonging to the current account are excluded, and the search results show whether the user is currently subscribed.
I added two methods of triggering the search modal: From within the "Add dashboard" popover, and with a separate search button. Having both might be overkill, but I either could be a good solution.
* Adds a dashboard search modal and search results template
* Adds views for displaying a search modal and handling shared dashboard search
* Adds a `name` to the `non_admin_account` fixture, necessary for the tests to …
=> Shared dashboards: Add dashboard search form

changelog.d/2344.added.md, python/nav/models/profiles.py, python/nav/models/sql/changes/sc.05.15.0001.sql, python/nav/web/navlets/__init__.py, python/nav/web/sass/nav/_tooltip.scss, python/nav/web/sass/nav/custom.scss, python/nav/web/static/js/src/webfront.js, python/nav/web/templates/navlets/base.html, python/nav/web/templates/webfront/_dashboard_nav.html, python/nav/web/templates/webfront/_dashboard_nav_shared_indicator.html, python/nav/web/templates/webfront/_dashboard_search_form.html, python/nav/web/templates/webfront/_dashboard_search_results.html, python/nav/web/templates/webfront/_dashboard_settings_form.html, python/nav/web/templates/webfront/_dashboard_settings_shared_form.html, python/nav/web/templates/webfront/index.html, python/nav/web/webfront/__init__.py, python/nav/web/webfront/urls.py, python/nav/web/webfront/views.py, tests/integration/conftest.py, tests/integration/web/webfront_test.py, tests/integration/widget_test.py
This PR will resolve #2344 when all dependent PRs are merged.
This PR resolves #3554 in itself.
Dependent PRs: #3553, #3557 (see dependency graph)
```mermaid
graph LR;
A(#3551: Base PR)
B(#3553: Loading and subscription - merged)
C(#3557: Dashboard search - merged)
D(#3559: Export and import - merged)
A-->B;
B-->C;
B-->D;
```
This PR adds support for sharing dashboards in NAV by modifying the `account_dashboard` table and adds a new `account_dashboard_subscription` table to hold account-dashboard joins.. A dashboard owner can set the dashboard as shared, which in turn will make it visible to other accounts in the follow-up PR.  
* Adds an `is_shared` property to the AccountDashboard model
* Adds new AccountDashboardSubscription to support account subscriptions on a dashboard
* Adds two …
=> Add shareable dashboard functionality
